/**
 * @envoymesh/envoy-harness — public API entry point.
 *
 * Phase 1: types only. The runtime lands in subsequent phases per
 * the design doc §22 (Migration and timeline).
 *
 * See `docs/design.md` for the full design.
 */
export declare const VERSION: "0.0.0";
export { AGENTS_MD_FILENAME, AGENTS_OVERRIDE_FILENAME, AgentRuntimeSchema, AskForApprovalSchema, DEFAULT_PROJECT_DOC_MAX_BYTES, DEFAULT_PROJECT_ROOT_MARKERS, ENVOY_HARNESS_LOCAL_VERSION, HookEventNameSchema, PermissionModeSchema, PermissionProfileNameSchema, SandboxBackendSchema, SkillIdSchema, VerdictEntrySchema, VerdictSchema, VerifierSourceSchema, } from "./types.js";
export type { AgentRuntime, AskDecision, AskForApproval, AskHandler, AskRequest, BashValidationInput, BashValidator, BashVerdict, DiscoveredAgentsDoc, HookDecision, HookEvent, HookEventName, HookFn, HookHandler, LoadedAgentsMd, PermissionMode, PermissionProfileName, ProfileRef, SandboxBackend, SandboxPolicy, SkillId, VerdictEntry, VerifierSource, } from "./types.js";
export { ALL_VALIDATORS, commandSemanticsValidation, destructiveCommandWarning, modeValidation, pathValidation, readOnlyValidation, sedValidation, validateBash, } from "./permissions/bash/index.js";
export { hasUnbalancedQuotes, containsBackticks } from "./permissions/bash/semantics.js";
export { discoverAgentsMd, type DiscoveryOptions } from "./agents-md/index.js";
export { HookRegistry, defaultRegistry, registerHooksFromConfig, runModuleHandler, runShellHandler, type HookMiddleware, } from "./hooks/index.js";
export { DuplicateToolError, ToolRegistry, type ContentBlock, type Message, type Role, type Tool, type ToolCall, type ToolContext, type ToolResult, } from "./tools/index.js";
export type { CompleteInput, ModelAdapter, ModelResponse, } from "./model.js";
export { InMemorySession, newSessionId, type Session, type SessionMetadata, type SessionProvenance, } from "./session.js";
export { PersistedSession, type PersistedSessionCreateOptions, SessionStore, type SessionStoreOptions, createSessionQueryService, makeSessionQueryTool, registerSessionQueryTool, indexSessionDirectory, indexSessionFile, isPathInside, type SessionIndexEntry, type SessionIndexerOptions, type SessionQueryHit, type SessionQueryRequest, type SessionQueryService, type SessionQueryServiceOptions, } from "./session/index.js";
export { Agent, DEFAULT_MAX_ITERATIONS, type AgentOptions, type AgentResult, } from "./agent.js";
export { ActionJournal, type UndoEntry } from "./action-journal.js";
export { BUILTIN_TOOLS, bashTool, makeBashTool, readFileTool, type MakeBashToolOptions, } from "./tools/builtin/index.js";
export { CostTracker, DEFAULT_PRICING, computeCost, type RunCost, type TokenPrice, type Usage, } from "./cost.js";
export { AnthropicAdapter, DeepSeekAdapter, FakeHttpClient, FetchHttpClient, OpenAIAdapter, createProviderAdapter, DEFAULT_PROVIDER_MODELS, isAnthropic2xx, isOpenAI2xx, messagesToAnthropic, messagesToOpenAI, parseAnthropicError, parseChatResponse, parseMessagesResponse, parseOpenAIError, splitSystemAndMessages, toolsToAnthropic, toolsToOpenAI, zodToJsonSchema, SUPPORTED_PROVIDERS, type AnthropicAdapterOptions, type AnthropicToolDefinition, type DeepSeekAdapterOptions, type HttpClient, type HttpRequest, type HttpResponse, type OpenAIAdapterOptions, type OpenAIMessage, type OpenAIToolCall, type OpenAIToolDefinition, type ProviderConfig, type SupportedProvider, } from "./llm/index.js";
export { ArgvError, CliError, EXIT_DATAERR, EXIT_ERROR, EXIT_NOINPUT, EXIT_OK, EXIT_USAGE, BUILTIN_COMMANDS, BUILTIN_INFO_COMMANDS, BUILTIN_TIER2_BATCH2_COMMANDS, BUILTIN_TIER2_BATCH3_COMMANDS, BUILTIN_TIER2_BATCH4_COMMANDS, BUILTIN_TIER2_COMMANDS, ReplCommandRegistry, defaultAskHandler, dispatchCommand, formatHelp, parseArgs, parseCommandLine, run, runRepl, type DispatchResult, type ExitCode, type LineReader, type ParsedArgs, type ReplCommand, type ReplContext, type ReplOptions, type ReplProfile, type ReplProfileLoader, type ReplResult, type SubagentRegistry, type RunOptions, type RunResult, type RunParsedArgs, type SelfEvolveParsedArgs, type CliRunResult, type SelfEvolveRunResult, } from "./cli/index.js";
export { DEFAULT_RULES, approvalRespectedRule, combineVerdicts, concatText, costReasonableForWorkRule, extractKeywords, meshTaskShapeRule, nonEmptyContentRule, outputMatchesObjectiveRule, runVerifierRules, sandboxRespectedRule, type Verdict, type VerifierRule, } from "./verifier/index.js";
export { FakeStdio, MockLspClient, NoopLspClient, StaticLspManager, StdioLspClient, frameLspMessage, makeLspTools, type LspClient, type LspClientMap, type LspDiagnostic, type LspHover, type LspLocation, type LspManager, type LspProcess, type MockLspCall, type MockLspResponseTable, type StdioLspClientOptions, } from "./lsp/index.js";
export { JsonLinesTracer, NullTracer, VerboseTracer, formatVerbose, createJsonlTelemetrySink, createNullTelemetrySink, wrapTracerAsTelemetrySink, assertRedactionInvariant, assertTraceEventShape, InvariantError, type AgentEndEvent, type AgentStartEvent, type ErrorEvent, type ModelResponseEvent, type ToolCallEvent, type ToolResultEvent, type TraceEvent, type Tracer, type WritableStream, type TelemetryCounters, type TelemetrySink, type JsonlTelemetrySinkOptions, type InvariantKind, type RedactionInvariantOptions, } from "./trace/index.js";
export { TomlParseError, parseTeamToml, Team, type AgentRunResult, type AgentSpec, type ScheduleSpec, type TeamConfig, type TeamOptions, type TeamResult, } from "./team/index.js";
export { LocalMeshSubmitter, NOOP_MESH_SUBMITTER_ERROR, NoopMeshSubmitter, TaskInputSchema, defaultBuildSubagentFactory, makeTaskTool, FanOutRegistry, aggregateFanOutResults, type DefaultBuildSubagentFactoryOptions, type FanOutSpec, type LocalMeshSubmitterOptions, type MakeTaskToolOptions, type MeshSubmitter, type RoutingHint, type SubagentInput, type SubagentRecord, type SubagentResult, type SubagentResultSigner, type TaskInput, type TaskResult, } from "./subagent/index.js";
export { BenchmarkSchema, DefaultBenchmarkRunner, FederatedAdoptionRecordSchema, FederatedAdoptionsSchema, FederatedScoreboard, LocalPeerSource, ModelHypothesisProvider, ScoreboardEntrySchema, ScoreboardSchema, SelfEvolve, appendAdoption, appendEntry, buildHypothesisPrompt, hashRuleset, loadRulesetFromFile, parseHypothesisFromLlm, readAdoptions, readBenchmark, readScoreboard, signEntry, verifyEntrySignature, writeBenchmark, writeScoreboard, type AdoptedCandidate, type AdoptResult, type Benchmark, type BenchmarkResult, type BenchmarkRunner, type BenchmarkTask, type FederatedAdoptionRecord, type FederatedAdoptions, type Hypothesis, type HypothesisProvider, type PeerScoreboard, type PeerSource, type PullOptions, type PullResult, type RunOneCycleResult, type Scoreboard, type ScoreboardEntry, type SelfEvolveOptions, type SelfEvolvePaths, type VerifierRuleset, } from "./scoreboard/index.js";
export { assembleFragments, createBoundedFragment, DEFAULT_ASSEMBLY_TOKEN_BUDGET, DEFAULT_FRAGMENT_TOKEN_CAP, type AssembledContext, type BoundedFragmentOptions, type ContextualUserFragment, } from "./context/fragment.js";
export { ConfigLayerSchema, ConfigLoadError, DEFAULT_CONFIG_PATH, HookHandlerSpecSchema, importCodexConfig, importDeepseekConfig, isImportFormat, loadConfig, loadConfigFile, loadConfigStack, loadConfigWithImport, mergeConfigLayers, parseClaudeCodeHooks, resolveAgentRuntimeConfig, resolveConfigPath, applyShellEnvironmentPolicy, ShellEnvironmentPolicySchema, systemPromptOptionsFromConfig, SUPPORTED_IMPORT_FORMATS, type ConfigLayer, type CodexImportResult, type CodexImportWarning, type DeepseekImportResult, type DeepseekImportWarning, type HookHandlerSpec, type ImportCodexOptions, type ImportDeepseekOptions, type ImportFormat, type LoadConfigStackOptions, type LoadedConfigStack, type ParseClaudeCodeHooksOptions, type ParseClaudeCodeHooksResult, type ResolvedAgentRuntimeConfig, type ShellEnvironmentPolicy, type SkippedCcHook, } from "./config/index.js";
export { auditLogPlugin, AuditLogConfigSchema, CalculatorError, calculatorPlugin, CalculatorConfigSchema, confirmToolPlugin, ConfirmToolConfigSchema, evaluateExpression, getBuiltinPlugin, isBuiltinPlugin, isWhitelistedPlugin, loadPlugin, mergePluginConfigs, parsePluginConfigEntry, PLUGIN_WHITELIST, PluginConfigError, PluginConfigParseError, PluginLoadError, PluginRegistry, resolvePluginAllowList, isAllowedPlugin, validatePluginConfig, type AuditLogConfig, type CalculatorConfig, type CapabilityContext, type CapabilityModule, type ConfirmToolConfig, type Disposable, type LoadPluginOptions, type PluginConfigEntry, type PluginLogger, type ResolvedPluginAllowList, type ResolvePluginAllowListOptions, type ZodIssueLike, } from "./plugins/index.js";
export { MCP_TOOL_PREFIX, DefaultMcpClientRegistry, mcpToolName, parseMcpToolName, type McpClient, type McpClientRegistry, type McpCallToolResult, type McpTool, formatMcpResult, registerMcpTools, wireMcpClientsFromConfig, runStdioMcpServer, MCP_SERVER_PROTOCOL_VERSION, type McpToolBridgeResult, type WiredMcpClients, } from "./mcp/index.js";
export { NoopSandboxExecutor, LandlockSandboxExecutor, SeatbeltSandboxExecutor, resolveSandboxExecutor, policyToLandlockGrants, policyToSeatbeltProfile, type SandboxContext, type SandboxExecutor, type SandboxResult, type LandlockGrants, type LandlockLauncherApi, type LandlockSandboxExecutorOptions, type SeatbeltSandboxExecutorOptions, type ResolveSandboxExecutorOptions, } from "./sandbox/index.js";
export { createAskForApprovalShim, createReplStdinProvider, createUserQuestionService, DEFAULT_MULTILINE_SENTINEL, makeAskUserTool, makeSuggestFollowUpsTool, emptyTurnHints, hasTurnHints, mergeTurnHints, type DeferredTask, type TurnHints, type MakeSuggestFollowUpsToolOptions, type AskUserInput, type CreateAskForApprovalShimOptions, type MakeAskUserToolOptions, type ReplStdinProviderOptions, type UserQuestionAnswer, type UserQuestionProvider, type UserQuestionRequest, type UserQuestionService, } from "./interaction/index.js";
export { LocalMemoryStore, buildIndexFragment, buildMemoryFragment, buildMemoryIndex, consolidateMemories, estimateMemoryTokens, hashMemoryBody, parseCitation, parseMemoryFile, renderCitation, serializeMemoryFile, slugify, type ConsolidateOptions, type ConsolidateResult, type LocalMemoryStoreOptions, type Memory, type MemoryCitation, type MemoryMeta, type MemoryStore, } from "./memories/index.js";
export { PLAN_FRAGMENT_PRIORITY, PlanTransitionError, applyTransition, buildPlanFragment, createPlanState, renderPlanText, runReview, type PlanReviewStatus, type PlanState, type PlanTransition, type ReviewVerdict, type RunReviewOptions, } from "./plan/index.js";
export { createLocalJobRegistry, createProcessJobHooks, JobError, makeJobTools, registerJobTools, type JobDoneListener, type JobHooks, type JobOutcome, type JobRead, type JobRegistry, type JobSnapshot, type JobStart, type JobStatus, type LocalJobRegistryOptions, type ProcessJobOptions, } from "./jobs/index.js";
export { createFakeFetchProvider, createFakeSearchProvider, createHttpFetchProvider, createBraveSearchProvider, createExaSearchProvider, createPerplexitySearchProvider, createWebRuntime, makeWebTools, registerWebTools, WebError, type BraveSearchProviderOptions, type ExaSearchProviderOptions, type PerplexitySearchProviderOptions, type HttpFetchProviderOptions, type WebErrorCode, type WebFetchBody, type WebFetchProvider, type WebFetchRequest, type WebFetchResult, type WebRuntime, type WebRuntimeConfig, type WebSearchProvider, type WebSearchRequest, type WebSearchResult, type WebSearchSource, } from "./web/index.js";
export { createFakeTerminalBackend, createPtyTerminalBackend, isPtyAvailable, createTerminalSessionService, makeTerminalTools, registerTerminalTools, TerminalError, type FakeTerminalBackendOptions, type FakeTerminalSessionState, type TerminalBackend, type TerminalBackendSession, type TerminalBackendSpawnSpec, type TerminalErrorCode, type TerminalReadRequest, type TerminalReadResult, type TerminalSendOperation, type TerminalSendRequest, type TerminalSendResult, type TerminalSessionService, type TerminalSessionSnapshot, type TerminalSessionStatus, type TerminalSignal, type TerminalSpawnRequest, type TerminalWaitReason, } from "./terminal/index.js";
export { createSystemPromptRegistry, agentsMdSection, bashGuidanceSection, harnessIdentitySection, jobsGuidanceSection, personaSection, permissionsPolicySection, planModeSection, readFileGuidanceSection, terminalGuidanceSection, webSearchGuidanceSection, workspaceSection, DEFAULT_PROJECT_DOC_FALLBACKS, buildAgentSystemPrompt, type BuildAgentSystemPromptOptions, type PromptAssemblyContext, type PromptSection, type SystemPromptRegistry, } from "./system-prompt/index.js";
export { assembleTurnContext, type AssembleTurnContextOptions, type AssembledTurnContext, } from "./context/turn-context.js";
export { isEphemeralUserContextText, isEphemeralUserMessage, injectEphemeralUserContext, } from "./context/ephemeral-user-context.js";
export { createDefaultCredentials, wireEnvironmentTools, type EnvironmentCapabilities, type WireEnvironmentOptions, } from "./environment/index.js";
export { createAskCredentialsProvider, createCredentialsProvider, createEnvCredentialsProvider, createFileCredentialsProvider, createRedactingTracer, CredentialError, type AskCredentialsOptions, type CredentialErrorCode, type CredentialReference, type CredentialSource, type CredentialsProvider, type EnvCredentialsOptions, type FileCredentialsOptions, type RedactingTracerOptions, type ResolveCredentialOptions, } from "./credentials/index.js";
export { createFeedbackSidecar, createFeedbackStore, makeFeedbackTools, registerFeedbackTools, toSelfEvolveSignals, type FeedbackEvent, type FeedbackPolarity, type FeedbackSidecar, type FeedbackSidecarOptions, type FeedbackStore, type FeedbackStoreOptions, type MessageFeedback, type RecordFeedbackInput, type SelfEvolveFeedbackSignal, } from "./feedback/index.js";
export { type FilesystemSkillProviderOptions, type SkillDefinition, type SkillFrontmatter, type SkillProvider, type SkillRegistry, type SkillRoot, type SkillSummary, SkillError, createFilesystemSkillProvider, createSkillRegistry, defaultSkillRoots, makeSkillListTool, makeSkillTool, parseFrontmatter, registerSkillTools, renderSkillContent, renderSkillCatalog, skillCatalogDigest, nextCatalogMessage, createSkillCatalogFragment, type SkillCatalogOptions, } from "./skills/index.js";
export { ACP_PROTOCOL_VERSION, attachAcpServer, attachSdkServer, createFakeSessionBackend, createAgentSessionBackend, createInProcessJsonRpcPair, encodeFrame, FrameDecoder, installToolPermissionAskHook, JsonRpcConnection, JsonRpcError, JsonRpcErrorCode, isJsonRpcNotification, isJsonRpcRequest, isJsonRpcResponse, type AcpServerOptions, type AgentSessionBackendOptions, type InProcessPair, type JsonRpcConnectionOptions, type JsonRpcErrorObject, type JsonRpcFailure, type JsonRpcId, type JsonRpcMessage, type JsonRpcNotification, type JsonRpcRequest, type JsonRpcResponse, type JsonRpcSuccess, type NotificationHandler, type ProtocolClusterStatus, type ProtocolCommittedMessage, type ProtocolDiscoveryEvent, type ProtocolPeerHealth, type ProtocolPeerInfo, type ProtocolPermissionDecision, type ProtocolPermissionRequest, type ProtocolPromptResult, type ProtocolScoreboardEntry, type ProtocolSessionBackend, type ProtocolTeamAgentStatus, type ProtocolTeamJob, type ProtocolToolInfo, type RequestHandler, type SdkServerOptions, type ToolPermissionAskHookOptions, } from "./protocol/index.js";
export { parsePeerEndpoint, parsePeerEndpointsFromEnv, parsePeerEndpointsList, type PeerEndpointSpec, } from "./peers/endpoints.js";
export { peersFromConfigLayer, resolvePeerEndpoints, type ResolvedPeerEndpoint, type ResolvePeerEndpointsOptions, } from "./peers/resolve.js";
export { mergeClusterSeams, wirePeerCluster, type ClusterSeams, type WirePeerClusterOptions, type WirePeerClusterResult, } from "./peers/wire-cluster.js";
//# sourceMappingURL=index.d.ts.map