import 'dart:convert';
import 'package:archive/archive.dart';
import 'node_service_client.dart';

/// QR code pairing service.
///
/// Parses `envoy://pair?...` URIs from the home node and calls
/// `pairThinClient` RPC. Two URI formats are supported:
///
/// 1. **Compressed token format** (preferred, used by Social app >= Phase 12):
///    `envoy://pair?pairing=<base64url-gzip-json>`
///    The token contains all fields in a gzip-compressed JSON payload.
///    Decoded using the `archive` package.
///
/// 2. **Legacy query-param format** (for backward compatibility):
///    `envoy://pair?wsUrl=...&token=...&ownerId=...&...`
class PairingService {
  final NodeServiceClient _client;

  PairingService(this._client);

  /// Parse a pairing URI from the home node.
  ///
  /// Tries the compressed `pairing` token first; falls back to legacy
  /// query-param parsing for URIs generated by older versions.
  static PairingData? parsePairingUri(String uri) {
    if (!uri.startsWith('envoy://pair')) return null;

    final parsed = Uri.tryParse(uri);
    if (parsed == null) return null;

    // Try compressed token format first.
    final compressedToken = parsed.queryParameters['pairing']?.trim();
    if (compressedToken != null && compressedToken.isNotEmpty) {
      try {
        final decoded = _decodePairingToken(compressedToken);
        if (decoded != null) return decoded;
      } catch (_) {
        // Fall through to legacy parsing.
      }
    }

    // Legacy query-param format (for backward compat).
    return _parseLegacyPairingUri(parsed);
  }

  // ─── Compressed token decoding ─────────────────────────────────────────────

  /// Decode a base64url-encoded gzip-compressed JSON pairing token.
  /// Returns null if the token is empty or malformed.
  static PairingData? _decodePairingToken(String token) {
    if (token.isEmpty) return null;

    final trimmed = token.trim();
    final decompressed = _gzipDecompress(trimmed);
    if (decompressed == null) return null;

    String json;
    try {
      json = utf8.decode(decompressed);
    } catch (_) {
      return null;
    }

    Map<String, dynamic> obj;
    try {
      obj = jsonDecode(json) as Map<String, dynamic>;
    } catch (_) {
      return null;
    }

    final v = obj['v'];
    if (v != 1) return null; // Unknown version

    final ws = obj['ws'] as String?;
    final tok = obj['tok'] as String?;
    final oid = obj['oid'] as String?;

    if (ws == null || ws.isEmpty) return null;
    if (tok == null || tok.isEmpty) return null;
    if (oid == null || oid.isEmpty) return null;

    final relayWsUrl = obj['rel'] as String?;
    final lanWsUrl = obj['lan'] as String?;
    final homeNodePeerId = obj['tid'] as String?;
    final agentPeerId = obj['apid'] as String?;
    final agentName = obj['aname'] as String?;
    final bpnRaw = obj['bpn'];

    List<String>? bootstrapPresetNames;
    if (bpnRaw is List) {
      final filtered = bpnRaw
          .whereType<String>()
          .where((s) => s.isNotEmpty)
          .toList();
      bootstrapPresetNames = filtered.isEmpty ? null : filtered;
    }

    return PairingData(
      token: tok,
      wsUrl: ws,
      relayWsUrl: relayWsUrl?.isNotEmpty == true ? relayWsUrl! : ws,
      lanWsUrl: lanWsUrl?.isNotEmpty == true ? lanWsUrl : null,
      ownerId: oid,
      homeNodePeerId: homeNodePeerId?.isNotEmpty == true ? homeNodePeerId : null,
      agentPeerId: agentPeerId?.isNotEmpty == true ? agentPeerId : null,
      agentName: agentName?.isNotEmpty == true ? agentName : null,
      // ownerPublicKey and bootstrapPeers are not in the compressed token —
      // the mobile app fetches the device certificate after pairing via RPC.
      // Bootstrap presets are reconstructed from bootstrapPresetNames locally.
      bootstrapPresetNames: bootstrapPresetNames,
    );
  }

  /// Decompress a base64url-encoded gzip blob. Returns null on failure.
  static List<int>? _gzipDecompress(String base64url) {
    try {
      // Normalize base64url → standard base64.
      String base64 = base64url.replaceAll('-', '+').replaceAll('_', '/');
      // Add padding if needed.
      while (base64.length % 4 != 0) {
        base64 += '=';
      }
      final bytes = base64Decode(base64);
      final archive = GZipDecoder().decodeBytes(bytes);
      return archive;
    } catch (_) {
      return null;
    }
  }

  // ─── Legacy query-param decoding ──────────────────────────────────────────

  static PairingData? _parseLegacyPairingUri(Uri parsed) {
    final token = parsed.queryParameters['token']?.trim();
    final wsUrl = parsed.queryParameters['wsUrl']?.trim();

    if (token == null || token.isEmpty) return null;
    if (wsUrl == null || wsUrl.isEmpty) return null;

    // Prefer relayWsUrl (clean URL from QR) over wsUrl (has ?target=.&token=.).
    final relayWsUrl = _nullableTrim(parsed.queryParameters['relayWsUrl']) ?? wsUrl;

    return PairingData(
      token: token,
      wsUrl: wsUrl,
      relayWsUrl: relayWsUrl,
      lanWsUrl: _nullableTrim(parsed.queryParameters['lanWsUrl']),
      ownerId: _nullableTrim(parsed.queryParameters['ownerId']),
      homeNodePeerId: _nullableTrim(parsed.queryParameters['homeNodePeerId']),
      agentPeerId: _nullableTrim(parsed.queryParameters['agentPeerId']),
      agentName: _nullableTrim(parsed.queryParameters['agentName']),
      relayPeerId: _nullableTrim(parsed.queryParameters['relayPeerId']),
      ownerPublicKey: _nullableTrim(parsed.queryParameters['ownerPublicKey']),
      bootstrapPeers: _parseBootstrapPeers(parsed.queryParameters['bootstrapPeers']),
      bootstrapPresetNames: _parseBootstrapPresetNames(parsed.queryParameters['bootstrapPresetNames']),
    );
  }

  /// Complete the pairing handshake with the home node.
  Future<PairResult> pair(PairingData data, String deviceName) async {
    final result = await _client.pairWithHomeNode(
      data.token,
      deviceName,
      'flutter',
    );
    return PairResult(
      sessionToken: result['sessionToken'] as String,
      ownerId: result['ownerId'] as String,
    );
  }

  /// Trim a query value, returning `null` for missing or empty-after-trim
  /// entries. Lets callers treat `?foo=` the same as `?foo` or no `foo` at all.
  static String? _nullableTrim(String? raw) {
    if (raw == null) return null;
    final trimmed = raw.trim();
    return trimmed.isEmpty ? null : trimmed;
  }

  /// Parse the bootstrapPeers query param: comma-separated list of
  /// WebSocket URLs or host:port strings.
  static List<String>? _parseBootstrapPeers(String? raw) {
    if (raw == null || raw.isEmpty) return null;
    final trimmed = raw.trim();
    if (trimmed.isEmpty) return null;
    return trimmed.split(',').map((s) => s.trim()).where((s) => s.isNotEmpty).toList();
  }

  /// Parse the bootstrapPresetNames query param: comma-separated preset names
  /// like "public-libp2p,public-libp2p-am6,cn-relay".
  /// EnvoyGo resolves these to full multiaddr strings using the same
  /// preset registry as the home node.
  static List<String>? _parseBootstrapPresetNames(String? raw) {
    if (raw == null || raw.isEmpty) return null;
    final trimmed = raw.trim();
    if (trimmed.isEmpty) return null;
    return trimmed.split(',').map((s) => s.trim()).where((s) => s.isNotEmpty).toList();
  }
}

/// Parsed pairing URI data from the home node.
class PairingData {
  /// Short-lived pairing token.
  final String token;

  /// Relay WebSocket URL (required, has ?target=...&token=...).
  final String wsUrl;

  /// Clean relay WebSocket URL without routing params (preferred).
  final String relayWsUrl;

  /// LAN WebSocket URL (optional, direct LAN access).
  final String? lanWsUrl;

  /// Owner ID from the home node (envoy:owner:...).
  final String? ownerId;

  /// Home node's libp2p peer ID.
  final String? homeNodePeerId;

  /// Bridge agent peer ID.
  final String? agentPeerId;

  /// Bridge agent display name.
  final String? agentName;

  /// Relay libp2p peer ID.
  final String? relayPeerId;

  /// Owner's Ed25519 public key (PEM) — only present in legacy URIs.
  final String? ownerPublicKey;

  /// Bootstrap peer addresses (libp2p public servers, additional relays)
  /// from the home node's configuration. Used as fallback when the
  /// primary relay is unavailable.
  final List<String>? bootstrapPeers;

  /// Bootstrap preset names (short codes like "public-libp2p-am6").
  /// EnvoyGo resolves these to full multiaddr strings using the same
  /// preset registry as the home node.
  final List<String>? bootstrapPresetNames;

  const PairingData({
    required this.token,
    required this.wsUrl,
    required this.relayWsUrl,
    this.lanWsUrl,
    this.ownerId,
    this.homeNodePeerId,
    this.agentPeerId,
    this.agentName,
    this.relayPeerId,
    this.ownerPublicKey,
    this.bootstrapPeers,
    this.bootstrapPresetNames,
  });
}

/// Result of a successful pairing.
class PairResult {
  final String sessionToken;
  final String ownerId;

  const PairResult({
    required this.sessionToken,
    required this.ownerId,
  });
}
