# Install / uninstall a user-level supervisor for a headless EnvoyMesh home node.
#
# Default product distribution stays the Tauri desktop app. This is for advanced
# operators who want the home node always on without a UI (EnvoyGo, mini-PC).
#
# Windows: Scheduled Task at logon + restart-on-failure (not a full SCM service).
#
# Do not run this and the desktop app against the same profile at the same time.
#
# Usage:
#   .\scripts\home-node-service.ps1 install [-Bundle DIR] [-Profile DIR]
#   .\scripts\home-node-service.ps1 uninstall
#   .\scripts\home-node-service.ps1 status
#   .\scripts\home-node-service.ps1 install -DryRun -Bundle C:\path\to\bundle
#
# -Bundle DIR   portable bundle (start.bat). Production headless path.
# (no -Bundle)  this git checkout via supervise-home-node.ps1. Dev path.
#
# Twin: scripts/home-node-service.sh (macOS LaunchAgent / Linux systemd --user).

[CmdletBinding()]
param(
  [Parameter(Position = 0)]
  [ValidateSet("install", "uninstall", "status")]
  [string]$Command,

  [string]$Bundle,
  [string]$Profile,
  [switch]$DryRun
)

$ErrorActionPreference = "Stop"

if (-not $Command) {
  Get-Content -Path $PSCommandPath -TotalCount 24 | Select-Object -Skip 1
  exit 1
}

$TaskName = "EnvoyMeshHomeNode"
$Root = Split-Path -Parent $PSScriptRoot
$SharedHome = Join-Path $env:LOCALAPPDATA "EnvoyMesh"
if (-not $Profile) {
  $Profile = Join-Path $SharedHome "profile"
}
$RuntimeDir = Join-Path $SharedHome "runtime"
$Wrapper = Join-Path $RuntimeDir "home-node-service-run.ps1"
$LogDir = Join-Path $env:LOCALAPPDATA "EnvoyMesh\logs"
$LogFile = Join-Path $LogDir "home-node-service.log"

Write-Host "Quit the EnvoyMesh desktop app first. One home node owns a profile."
Write-Host "Profile: $Profile"

function Write-Wrapper {
  New-Item -ItemType Directory -Force -Path $RuntimeDir, $LogDir | Out-Null
  $bundleDir = $null
  $execBlock = $null
  if ($Bundle) {
    $bundleDir = (Resolve-Path $Bundle).Path
    $startBat = Join-Path $bundleDir "start.bat"
    if (-not (Test-Path $startBat)) {
      throw "Bundle has no start.bat: $bundleDir"
    }
    $execBlock = @"
Set-Location '$bundleDir'
& '$startBat'
exit `$LASTEXITCODE
"@
  } else {
    $pkg = Join-Path $Root "package.json"
    $supervise = Join-Path $Root "scripts\supervise-home-node.ps1"
    if (-not (Test-Path $pkg) -or -not (Test-Path $supervise)) {
      throw "Not an EnvoyMesh checkout. Pass -Bundle DIR for a portable install."
    }
    $execBlock = @"
Set-Location '$Root'
& '$supervise' --profile '$Profile'
exit `$LASTEXITCODE
"@
  }

  $pathEsc = $env:Path.Replace("'", "''")
  $content = @"
# Generated by scripts/home-node-service.ps1 — do not edit while the task is registered.
`$ErrorActionPreference = 'Stop'
`$env:Path = '$pathEsc'
`$env:ENVOYMESH_GUARDIAN_EXIT_ON_LAG = '1'
`$env:ENVOYMESH_HOME = '$SharedHome'
`$env:ENVOYMESH_PROFILE = '$Profile'
New-Item -ItemType Directory -Force -Path '$LogDir' | Out-Null
Start-Transcript -Path '$LogFile' -Append | Out-Null
try {
$execBlock
} finally {
  Stop-Transcript | Out-Null
}
"@
  Set-Content -Path $Wrapper -Value $content -Encoding UTF8
}

function Install-HomeNodeTask {
  if ($Bundle) {
    $bundleDir = (Resolve-Path $Bundle).Path
    if (-not (Test-Path (Join-Path $bundleDir "start.bat"))) {
      throw "Bundle has no start.bat: $bundleDir"
    }
  } elseif (-not (Test-Path (Join-Path $Root "package.json")) -or -not (Test-Path (Join-Path $Root "scripts\supervise-home-node.ps1"))) {
    throw "Not an EnvoyMesh checkout. Pass -Bundle DIR for a portable install."
  }
  if ($DryRun) {
    Write-Host "[dry-run] wrapper: $Wrapper"
    Write-Host "[dry-run] task:    $TaskName"
    Write-Host "[dry-run] profile: $Profile"
    return
  }
  Write-Wrapper
  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
  $arg = "-NoProfile -ExecutionPolicy Bypass -File `"$Wrapper`""
  $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $arg
  $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
  $settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero)
  $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
  Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal | Out-Null
  Start-ScheduledTask -TaskName $TaskName
  Write-Host "Installed Scheduled Task $TaskName"
  Write-Host "Logs: $LogFile"
}

function Uninstall-HomeNodeTask {
  if ($DryRun) {
    Write-Host "[dry-run] would unregister $TaskName and remove $Wrapper"
    return
  }
  Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
  if (Test-Path $Wrapper) { Remove-Item $Wrapper -Force }
  Write-Host "Removed Scheduled Task $TaskName"
}

function Show-HomeNodeTaskStatus {
  $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  if (-not $task) {
    Write-Host "$TaskName is not registered"
    if (Test-Path $Wrapper) { Write-Host "wrapper present: $Wrapper" }
    return
  }
  $info = Get-ScheduledTaskInfo -TaskName $TaskName
  Write-Host "Task: $($task.TaskName)"
  Write-Host "State: $($task.State)"
  Write-Host "LastResult: $($info.LastTaskResult)"
  Write-Host "LastRun: $($info.LastRunTime)"
  Write-Host "NextRun: $($info.NextRunTime)"
}

switch ($Command) {
  "install" { Install-HomeNodeTask }
  "uninstall" { Uninstall-HomeNodeTask }
  "status" { Show-HomeNodeTaskStatus }
}
