#!/usr/bin/env bash
# Install / uninstall a user-level supervisor for a headless EnvoyMesh home node.
#
# Default product distribution stays the Tauri desktop app. This is for advanced
# operators who want the home node always on without a UI (EnvoyGo, mini-PC).
#
# macOS: LaunchAgent (KeepAlive)
# Linux: systemd --user (Restart=on-failure)
#
# Do not run this and the desktop app against the same profile at the same time.
#
# Usage:
#   ./scripts/home-node-service.sh install [--bundle DIR] [--profile DIR]
#   ./scripts/home-node-service.sh uninstall
#   ./scripts/home-node-service.sh status
#   ./scripts/home-node-service.sh install --dry-run --bundle /path/to/bundle
#   (dry-run prints paths; it does not write LaunchAgents or systemd units)
#
# --bundle DIR   portable bundle (start.sh). Production headless path.
# (no --bundle)  this git checkout via supervise-home-node.sh. Dev path.
#
# Twin: scripts/home-node-service.ps1 (Windows Scheduled Task).

set -euo pipefail

LABEL="com.envoymesh.home-node"
SYSTEMD_UNIT="envoymesh-home-node.service"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

usage() {
  sed -n '2,22p' "$0"
  exit "${1:-0}"
}

plist_escape() {
  printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

default_shared_home() {
  case "$(uname -s)" in
    Darwin) printf '%s\n' "$HOME/Library/Application Support/EnvoyMesh" ;;
    *)
      if [ -n "${XDG_DATA_HOME:-}" ]; then
        printf '%s\n' "$XDG_DATA_HOME/EnvoyMesh"
      else
        printf '%s\n' "$HOME/.local/share/EnvoyMesh"
      fi
      ;;
  esac
}

cmd=""
BUNDLE_DIR=""
PROFILE_DIR=""
DRY_RUN=0

while [ $# -gt 0 ]; do
  case "$1" in
    install|uninstall|status) cmd="$1"; shift ;;
    --bundle)
      [ $# -ge 2 ] || { echo "Missing value for --bundle" >&2; exit 1; }
      BUNDLE_DIR="$2"; shift 2
      ;;
    --profile)
      [ $# -ge 2 ] || { echo "Missing value for --profile" >&2; exit 1; }
      PROFILE_DIR="$2"; shift 2
      ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage 1
      ;;
  esac
done

[ -n "$cmd" ] || usage 1

SHARED_HOME="$(default_shared_home)"
if [ -z "$PROFILE_DIR" ]; then
  PROFILE_DIR="$SHARED_HOME/profile"
fi
RUNTIME_DIR="$SHARED_HOME/runtime"
WRAPPER="$RUNTIME_DIR/home-node-service-run.sh"
LOG_DIR="$HOME/Library/Logs/EnvoyMesh"
if [ "$(uname -s)" != "Darwin" ]; then
  LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/envoymesh"
fi

UNAME="$(uname -s)"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
SYSTEMD_DIR="$HOME/.config/systemd/user"
SYSTEMD_PATH="$SYSTEMD_DIR/$SYSTEMD_UNIT"

print_exclusivity() {
  echo "Quit the EnvoyMesh desktop app first. One home node owns a profile."
  echo "Profile: $PROFILE_DIR"
}

# bash 3.2 (macOS /bin/bash) has no printf %q.
posix_sq() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

resolve_exec_line() {
  if [ -n "$BUNDLE_DIR" ]; then
    BUNDLE_DIR="$(cd "$BUNDLE_DIR" && pwd)"
    if [ ! -x "$BUNDLE_DIR/start.sh" ]; then
      echo "Bundle has no start.sh: $BUNDLE_DIR" >&2
      exit 1
    fi
    printf 'exec "%s/start.sh"\n' "$BUNDLE_DIR"
    return
  fi
  if [ ! -f "$ROOT/package.json" ] || [ ! -f "$ROOT/scripts/supervise-home-node.sh" ]; then
    echo "Not an EnvoyMesh checkout. Pass --bundle DIR for a portable install." >&2
    exit 1
  fi
  printf 'cd "%s" && exec bash "%s/scripts/supervise-home-node.sh" -- --profile "%s"\n' \
    "$ROOT" "$ROOT" "$PROFILE_DIR"
}

write_wrapper() {
  mkdir -p "$RUNTIME_DIR" "$LOG_DIR"
  local exec_line
  exec_line="$(resolve_exec_line)"
  cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by scripts/home-node-service.sh — do not edit while the service is loaded.
set -euo pipefail
export PATH=$(posix_sq "$PATH")
export ENVOYMESH_GUARDIAN_EXIT_ON_LAG=1
export ENVOYMESH_HOME=$(posix_sq "$SHARED_HOME")
export ENVOYMESH_PROFILE=$(posix_sq "$PROFILE_DIR")
$exec_line
EOF
  chmod +x "$WRAPPER"
}

write_launch_agent() {
  mkdir -p "$(dirname "$PLIST")"
  local wrap_esc home_esc log_esc
  wrap_esc="$(plist_escape "$WRAPPER")"
  home_esc="$(plist_escape "$SHARED_HOME")"
  log_esc="$(plist_escape "$LOG_DIR/home-node-service.log")"
  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${wrap_esc}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${home_esc}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>${log_esc}</string>
  <key>StandardErrorPath</key>
  <string>${log_esc}</string>
</dict>
</plist>
EOF
}

write_systemd_unit() {
  mkdir -p "$SYSTEMD_DIR"
  cat > "$SYSTEMD_PATH" <<EOF
[Unit]
Description=EnvoyMesh headless home node
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=ENVOYMESH_GUARDIAN_EXIT_ON_LAG=1
Environment=ENVOYMESH_HOME=$SHARED_HOME
Environment=ENVOYMESH_PROFILE=$PROFILE_DIR
ExecStart=$WRAPPER
Restart=on-failure
RestartSec=5
TimeoutStopSec=20

[Install]
WantedBy=default.target
EOF
}

install_macos() {
  resolve_exec_line >/dev/null
  if [ "$DRY_RUN" = "1" ]; then
    echo "[dry-run] wrapper: $WRAPPER"
    echo "[dry-run] plist:   $PLIST"
    echo "[dry-run] exec:    $(resolve_exec_line)"
    return
  fi
  write_wrapper
  write_launch_agent
  launchctl bootout "gui/$(id -u)" "$PLIST" >/dev/null 2>&1 || true
  launchctl bootstrap "gui/$(id -u)" "$PLIST"
  launchctl enable "gui/$(id -u)/${LABEL}" >/dev/null 2>&1 || true
  launchctl kickstart -k "gui/$(id -u)/${LABEL}"
  echo "Installed LaunchAgent $LABEL"
  echo "Logs: $LOG_DIR/home-node-service.log"
}

uninstall_macos() {
  if [ "$DRY_RUN" = "1" ]; then
    echo "[dry-run] would bootout $LABEL and remove $PLIST $WRAPPER"
    return
  fi
  launchctl bootout "gui/$(id -u)" "$PLIST" >/dev/null 2>&1 || true
  rm -f "$PLIST" "$WRAPPER"
  echo "Removed LaunchAgent $LABEL"
}

status_macos() {
  if launchctl print "gui/$(id -u)/${LABEL}" >/dev/null 2>&1; then
    launchctl print "gui/$(id -u)/${LABEL}" | sed -n '1,40p'
  else
    echo "$LABEL is not loaded"
    [ -f "$PLIST" ] && echo "plist present: $PLIST"
  fi
}

install_linux() {
  resolve_exec_line >/dev/null
  if [ "$DRY_RUN" = "1" ]; then
    echo "[dry-run] wrapper: $WRAPPER"
    echo "[dry-run] unit:    $SYSTEMD_PATH"
    echo "[dry-run] exec:    $(resolve_exec_line)"
    return
  fi
  write_wrapper
  write_systemd_unit
  systemctl --user daemon-reload
  systemctl --user enable --now "$SYSTEMD_UNIT"
  echo "Installed systemd user unit $SYSTEMD_UNIT"
  echo "Logs: journalctl --user -u $SYSTEMD_UNIT -f"
  echo "If this machine has no GUI login, you may need: loginctl enable-linger $USER"
}

uninstall_linux() {
  if [ "$DRY_RUN" = "1" ]; then
    echo "[dry-run] would disable $SYSTEMD_UNIT"
    return
  fi
  systemctl --user disable --now "$SYSTEMD_UNIT" >/dev/null 2>&1 || true
  rm -f "$SYSTEMD_PATH" "$WRAPPER"
  systemctl --user daemon-reload >/dev/null 2>&1 || true
  echo "Removed systemd user unit $SYSTEMD_UNIT"
}

status_linux() {
  if systemctl --user status "$SYSTEMD_UNIT" >/dev/null 2>&1; then
    systemctl --user status "$SYSTEMD_UNIT" --no-pager
  else
    echo "$SYSTEMD_UNIT is not active"
    [ -f "$SYSTEMD_PATH" ] && echo "unit file present: $SYSTEMD_PATH"
  fi
}

print_exclusivity

case "$cmd" in
  install)
    case "$UNAME" in
      Darwin) install_macos ;;
      Linux) install_linux ;;
      *)
        echo "Unsupported OS: $UNAME (Windows: scripts/home-node-service.ps1)" >&2
        exit 1
        ;;
    esac
    ;;
  uninstall)
    case "$UNAME" in
      Darwin) uninstall_macos ;;
      Linux) uninstall_linux ;;
      *)
        echo "Unsupported OS: $UNAME" >&2
        exit 1
        ;;
    esac
    ;;
  status)
    case "$UNAME" in
      Darwin) status_macos ;;
      Linux) status_linux ;;
      *)
        echo "Unsupported OS: $UNAME" >&2
        exit 1
        ;;
    esac
    ;;
esac
