#!/usr/bin/env node
// sync-version.mjs — Read VERSION from root, write it everywhere.
// Usage: node scripts/sync-version.mjs
// Also runs automatically as npm "version" lifecycle hook.

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs"
import { resolve, join, dirname, basename } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, "..")

// ---- Read source of truth ----
const version = readFileSync(join(ROOT, "VERSION"), "utf8").trim()
if (!/^\d+\.\d+\.\d+/.test(version)) {
  console.error(`❌ Invalid VERSION: "${version}" — must be semver (e.g. 0.1.0)`)
  process.exit(1)
}
console.log(`🔄 Syncing version → ${version}`)

let changed = 0

// ---- Helpers ----
function updateJsonVersion(filePath, versionField = "version") {
  const raw = readFileSync(filePath, "utf8")
  const pkg = JSON.parse(raw)
  if (pkg[versionField] === version) return
  pkg[versionField] = version
  writeFileSync(filePath, JSON.stringify(pkg, null, 2) + "\n")
  console.log(`  ✏️  ${versionField} in ${filePath.replace(ROOT + "/", "")}`)
  changed++
}

function updateCargoVersion(filePath) {
  const raw = readFileSync(filePath, "utf8")
  const updated = raw.replace(
    /^(version\s*=\s*)"[^"]*"/m,
    `$1"${version}"`,
  )
  if (updated === raw) return
  writeFileSync(filePath, updated)
  console.log(`  ✏️  version in ${filePath.replace(ROOT + "/", "")}`)
  changed++
}

function updateGradleVersion(filePath) {
  const raw = readFileSync(filePath, "utf8")
  const updated = raw.replace(
    /versionName\s+"[^"]*"/,
    `versionName "${version}"`,
  )
  if (updated === raw) return
  writeFileSync(filePath, updated)
  console.log(`  ✏️  versionName in ${filePath.replace(ROOT + "/", "")}`)
  changed++
}

function generateVersionTs(filePath) {
  const content =
    `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit manually.\n` +
    `// Source of truth: VERSION file at repo root.\n` +
    `export const ENVOYMESH_VERSION = ${JSON.stringify(version)} as const;\n`
  try {
    const existing = readFileSync(filePath, "utf8")
    if (existing === content) return
  } catch {
    // File doesn't exist yet — will create
  }
  writeFileSync(filePath, content)
  console.log(`  ✏️  ${filePath.replace(ROOT + "/", "")}`)
  changed++
}

// ---- 1. Root package.json ----
updateJsonVersion(join(ROOT, "package.json"))

// ---- 2. All workspace package.json files (except OpenClawExtension & openclaw dist-runtime) ----
function collectWorkspacePackageJsons(dir, results = []) {
  const entries = readdirSync(dir, { withFileTypes: true })
  for (const entry of entries) {
    if (entry.name === "node_modules" || entry.name === ".git" ||
        entry.name === "OpenClawExtension" || entry.name === "resources") {
      continue
    }
    // Skip vendored openclaw package (sibling of openclaw-runtime which is ours)
    if (basename(dir) === "packages" && entry.name === "openclaw") continue
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      collectWorkspacePackageJsons(full, results)
    } else if (entry.name === "package.json") {
      results.push(full)
    }
  }
  return results
}

const allPkgJsons = collectWorkspacePackageJsons(ROOT)
for (const p of allPkgJsons) {
  // Skip the root (already done) and tauri node bundle (nested, versioned differently)
  if (p === join(ROOT, "package.json")) continue
  // Skip openclaw dist-runtime extensions (third-party, own versions)
  if (p.includes("dist-runtime")) continue
  // Skip tauri resources/node/package.json — that's the bundled node, versioned separately
  if (p.includes(join("resources", "node"))) continue
  updateJsonVersion(p)
}

// ---- 3. Tauri conf files ----
const tauriDir = join(ROOT, "apps", "tauri", "src-tauri")
for (const name of ["tauri.conf.json", "tauri.conf.slim.json", "tauri.conf.full.json"]) {
  updateJsonVersion(join(tauriDir, name))
}

// ---- 4. Cargo.toml ----
updateCargoVersion(join(tauriDir, "Cargo.toml"))

// ---- 5. Android build.gradle ----
const gradlePath = join(ROOT, "apps", "mobile", "android", "app", "build.gradle")
if (statSync(gradlePath, { throwIfNoEntry: false })) {
  updateGradleVersion(gradlePath)
}

// ---- 6. Generate version.ts for runtime imports ----
const versionTsPath = join(ROOT, "packages", "api", "src", "version.ts")
generateVersionTs(versionTsPath)

// ---- 7. Update hardcoded version strings in source code ----
function updateSourceVersion(filePath, pattern) {
  const raw = readFileSync(filePath, "utf8")
  const updated = raw.replace(pattern, `$1${JSON.stringify(version)}`)
  if (updated === raw) return
  writeFileSync(filePath, updated)
  console.log(`  ✏️  version string in ${filePath.replace(ROOT + "/", "")}`)
  changed++
}

// openclaw-runtime: envoyVersion in hello handshake
updateSourceVersion(
  join(ROOT, "packages", "openclaw-runtime", "src", "index.ts"),
  /(envoyVersion:\s*)"[^"]*"/,
)

// local-store: versionTag in capability manifest
updateSourceVersion(
  join(ROOT, "packages", "local-store", "src", "capability-manifest-store.ts"),
  /(versionTag:\s*)"[^"]*"/,
)

// openclaw-runtime test: envoyVersion in test fixture
updateSourceVersion(
  join(ROOT, "packages", "openclaw-runtime", "test", "index.test.ts"),
  /(envoyVersion:\s*)"[^"]*"/,
)

// ---- Done ----
if (changed === 0) {
  console.log(`  ✅ Everything already at ${version} — no changes needed.`)
} else {
  console.log(`  ✅ Updated ${changed} file${changed > 1 ? "s" : ""} to ${version}`)
}
