#!/usr/bin/env node
// sync-version.mjs — Read VERSION from root, write it everywhere.
// Usage: node scripts/sync-version.mjs
// Also runs automatically as npm "version" lifecycle hook.

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs"
import { resolve, join, dirname, basename } from "node:path"
import { execSync } from "node:child_process"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, "..")

// ---- Resolve source of truth ----
// Two ways this script gets invoked:
//   1. Manually / via CI:  `echo 0.3.0 > VERSION && node sync-version.mjs`
//      → VERSION file is the source of truth.
//   2. As the npm "version" lifecycle hook:  `npm version 0.3.0`
//      → npm bumps package.json BEFORE running this hook, so package.json's
//        version is newer than VERSION. Trust package.json here and write it
//        back to VERSION, otherwise we'd overwrite npm's bump back to the old
//        value and leave the repo in an inconsistent state.
// `npm_command` distinguishes the two: "version" for `npm version`,
// "run-script" for `npm run version`, undefined for plain `node sync-version.mjs`.
const VERSION_FILE = join(ROOT, "VERSION")
const ROOT_PKG = join(ROOT, "package.json")
const fileVersion = readFileSync(VERSION_FILE, "utf8").trim()
const pkgVersion = JSON.parse(readFileSync(ROOT_PKG, "utf8")).version
const isNpmVersionLifecycle = process.env.npm_command === "version"

let version
if (isNpmVersionLifecycle && pkgVersion !== fileVersion) {
  // npm version just bumped package.json — adopt it as the new source of truth.
  version = pkgVersion
  writeFileSync(VERSION_FILE, version + "\n")
  console.log(`📥 Adopted version from package.json (npm version lifecycle): ${version} → VERSION`)
} else {
  version = fileVersion
}

if (!/^\d+\.\d+\.\d+/.test(version)) {
  console.error(`❌ Invalid VERSION: "${version}" — must be semver (e.g. 0.1.0)`)
  process.exit(1)
}
console.log(`🔄 Syncing version → ${version}`)

let changed = 0

// ---- Helpers ----
function updateJsonVersion(filePath, versionField = "version") {
  const raw = readFileSync(filePath, "utf8")
  const pkg = JSON.parse(raw)
  if (pkg[versionField] === version) return
  pkg[versionField] = version
  writeFileSync(filePath, JSON.stringify(pkg, null, 2) + "\n")
  console.log(`  ✏️  ${versionField} in ${filePath.replace(ROOT + "/", "")}`)
  changed++
}

/** Keep workspace @envoymesh/* dependency pins in lockstep with VERSION.
 *  Stale pins (e.g. "0.1.0" while packages are 0.2.1) make npm fetch the
 *  registry and 404 on private workspace packages. */
function updateWorkspaceDepPins(filePath) {
  const raw = readFileSync(filePath, "utf8")
  const pkg = JSON.parse(raw)
  let touched = false
  for (const field of ["dependencies", "devDependencies", "peerDependencies", "optionalDependencies"]) {
    const deps = pkg[field]
    if (!deps || typeof deps !== "object") continue
    for (const [name, range] of Object.entries(deps)) {
      if (!name.startsWith("@envoymesh/")) continue
      // Only rewrite exact versions / simple ranges we own — leave path/git specs alone.
      if (typeof range !== "string") continue
      if (/^(file:|link:|git[+:]|https?:|workspace:)/.test(range)) continue
      if (range === version) continue
      deps[name] = version
      touched = true
    }
  }
  if (!touched) return
  writeFileSync(filePath, JSON.stringify(pkg, null, 2) + "\n")
  console.log(`  ✏️  @envoymesh/* deps in ${filePath.replace(ROOT + "/", "")}`)
  changed++
}

function updateCargoVersion(filePath) {
  const raw = readFileSync(filePath, "utf8")
  const updated = raw.replace(
    /^(version\s*=\s*)"[^"]*"/m,
    `$1"${version}"`,
  )
  if (updated === raw) return
  writeFileSync(filePath, updated)
  console.log(`  ✏️  version in ${filePath.replace(ROOT + "/", "")}`)
  changed++
}

function updateGradleVersion(filePath) {
  const raw = readFileSync(filePath, "utf8")
  const updated = raw.replace(
    /versionName\s+"[^"]*"/,
    `versionName "${version}"`,
  )
  if (updated === raw) return
  writeFileSync(filePath, updated)
  console.log(`  ✏️  versionName in ${filePath.replace(ROOT + "/", "")}`)
  changed++
}

function generateVersionTs(filePath) {
  const content =
    `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit manually.\n` +
    `// Source of truth: VERSION file at repo root.\n` +
    `export const ENVOYMESH_VERSION = ${JSON.stringify(version)} as const;\n`
  try {
    const existing = readFileSync(filePath, "utf8")
    if (existing === content) return
  } catch {
    // File doesn't exist yet — will create
  }
  writeFileSync(filePath, content)
  console.log(`  ✏️  ${filePath.replace(ROOT + "/", "")}`)
  changed++
}

// ---- 1. Root package.json ----
updateJsonVersion(join(ROOT, "package.json"))

// ---- 2. All workspace package.json files (except OpenClawExtension & openclaw dist-runtime) ----
function collectWorkspacePackageJsons(dir, results = []) {
  const entries = readdirSync(dir, { withFileTypes: true })
  for (const entry of entries) {
    if (entry.name === "node_modules" || entry.name === ".git" ||
        entry.name === "OpenClawExtension" || entry.name === "resources") {
      continue
    }
    // Skip vendored openclaw package (sibling of openclaw-runtime which is ours)
    if (basename(dir) === "packages" && entry.name === "openclaw") continue
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      collectWorkspacePackageJsons(full, results)
    } else if (entry.name === "package.json") {
      results.push(full)
    }
  }
  return results
}

const allPkgJsons = collectWorkspacePackageJsons(ROOT)
for (const p of allPkgJsons) {
  // Skip the root (already done) and tauri node bundle (nested, versioned differently)
  if (p === join(ROOT, "package.json")) continue
  // Skip openclaw dist-runtime extensions (third-party, own versions)
  if (p.includes("dist-runtime")) continue
  // Skip tauri resources/node/package.json — that's the bundled node, versioned separately
  if (p.includes(join("resources", "node"))) continue
  updateJsonVersion(p)
  updateWorkspaceDepPins(p)
}
// Root may also list workspace deps in future — keep pins consistent.
updateWorkspaceDepPins(join(ROOT, "package.json"))

// ---- 3. Tauri conf files ----
const tauriDir = join(ROOT, "apps", "tauri", "src-tauri")
for (const name of ["tauri.conf.json", "tauri.conf.slim.json", "tauri.conf.full.json"]) {
  updateJsonVersion(join(tauriDir, name))
}

// ---- 4. Cargo.toml ----
updateCargoVersion(join(tauriDir, "Cargo.toml"))

// ---- 5. Android build.gradle ----
const gradlePath = join(ROOT, "apps", "mobile", "android", "app", "build.gradle")
if (statSync(gradlePath, { throwIfNoEntry: false })) {
  updateGradleVersion(gradlePath)
}

// ---- 6. Generate version.ts for runtime imports ----
const versionTsPath = join(ROOT, "packages", "api", "src", "version.ts")
generateVersionTs(versionTsPath)

// ---- 7. Update hardcoded version strings in source code ----
function updateSourceVersion(filePath, pattern) {
  const raw = readFileSync(filePath, "utf8")
  const updated = raw.replace(pattern, `$1${JSON.stringify(version)}`)
  if (updated === raw) return
  writeFileSync(filePath, updated)
  console.log(`  ✏️  version string in ${filePath.replace(ROOT + "/", "")}`)
  changed++
}

// openclaw-runtime: envoyVersion in hello handshake
updateSourceVersion(
  join(ROOT, "packages", "openclaw-runtime", "src", "index.ts"),
  /(envoyVersion:\s*)"[^"]*"/,
)

// local-store: versionTag in capability manifest
updateSourceVersion(
  join(ROOT, "packages", "local-store", "src", "capability-manifest-store.ts"),
  /(versionTag:\s*)"[^"]*"/,
)

// openclaw-runtime test: envoyVersion in test fixture
updateSourceVersion(
  join(ROOT, "packages", "openclaw-runtime", "test", "index.test.ts"),
  /(envoyVersion:\s*)"[^"]*"/,
)

// ---- Done ----
if (changed === 0) {
  console.log(`  ✅ Everything already at ${version} — no changes needed.`)
} else {
  console.log(`  ✅ Updated ${changed} file${changed > 1 ? "s" : ""} to ${version}`)
}

// When invoked as the npm "version" lifecycle hook, npm will create its own
// git commit + tag immediately after this script returns — but only with
// whatever is staged at that point. Stage all our sync writes so they land in
// npm's version commit alongside package.json, instead of being left in the
// working tree and forgotten.
if (isNpmVersionLifecycle) {
  try {
    execSync("git add -A", { stdio: "ignore", cwd: ROOT })
    console.log(`  📦 Staged all changes for npm version commit`)
  } catch {
    // Not a git repo, or git unavailable — non-fatal; user can `git add` manually.
  }
}
