#!/usr/bin/env python3
import re

TERM_MAP = {
    'EnvoyMesh': 'EnvoyMesh',
    'EnvoyGo': 'EnvoyGo',
    'EnvoyAI': 'EnvoyAI',
    'OpenClaw': 'OpenClaw',
    'HomeClaw': 'HomeClaw',
    'Hermes': 'Hermes',
    'OpenHuman': 'OpenHuman',
    'libp2p': 'libp2p',
    'Ed25519': 'Ed25519',
    'DID': 'DID',
    'MCP': 'MCP',
    'A2A': 'A2A',
    'JSON-RPC': 'JSON-RPC',
    'WebSocket': 'WebSocket',
    'RAG': 'RAG',
    'Vault': '保险库',
    'Library': '库',
    'Social': 'Social',
    'Node': '节点',
    'Home Node': '家庭节点',
    'Agent': '智能体',
    'Bond': '绑定',
    'Trust': '信任',
    'Peer': '对等节点',
    'Mesh': '网格',
    'Profile': '资料',
    'Contact': '联系人',
    'Team jobs': '团队任务',
    'Relay': '中继',
    'Terminal': '终端',
    'Browser': '浏览器',
    'Mandate': '授权',
    'Approval': '审批',
    'Audit': '审计',
    'Knowledge': '知识',
    'Conversation': '对话',
    'Group': '群组',
    'Voice call': '语音通话',
    'Audio message': '语音消息',
    'QR code': '二维码',
    'Pairing': '配对',
    'Discovery': '发现',
    'mDNS': 'mDNS',
    'DHT': 'DHT',
    'TCP': 'TCP',
    'QUIC': 'QUIC',
    'LAN': '局域网',
    'WAN': '广域网',
    'NAT': 'NAT',
    'TURN': 'TURN',
    'PTY': 'PTY',
    'JSONL': 'JSONL',
    'Claude': 'Claude',
    'Obsidian': 'Obsidian',
    'OpenAI': 'OpenAI',
    'LiteLLM': 'LiteLLM',
    'Phase': '阶段',
    'Beta': 'Beta',
    'Experimental': '实验性',
    'Available': '可用',
    'Planned': '计划中',
    'Parked': '暂停',
    'Desktop': '桌面',
    'Mobile': '移动',
    'Operator': '操作员',
    'Compatibility preset': '兼容性预设',
}

SENTENCE_TRANSLATIONS = {
    'This guide reflects the EnvoyMesh 0.1.0 repository state at the revision date.': '本指南反映了修订日期时 EnvoyMesh 0.1.0 仓库的状态。',
    'It is written for end users, not as a content-outline stub.': '它是为最终用户编写的，而不是作为内容大纲的存根。',
    'Feature status can differ by platform and deployment': '功能状态可能因平台和部署而异',
    'verify each Beta or Experimental capability in your build': '在您的构建中验证每个 Beta 或实验性功能',
    'release notes, Settings labels, and Appendix J': '发行说明、设置标签和附录 J',
    'before relying on it in production': '在生产环境中依赖之前',
    'Parts I–XIV explain the product for end users and operators.': '第一至第十四部分为最终用户和操作员解释产品。',
    'Part XV is for website editors and content operators and is optional for end users.': '第十五部分面向网站编辑和内容操作员，对最终用户是可选的。',
    'Task lifecycle names such as': '任务生命周期名称，如',
    'Created': '已创建',
    'Task planned': '任务计划中',
    'Running': '运行中',
    'are EnvoyMesh states': '是 EnvoyMesh 状态',
    'not product Planned / Available status labels': '不是产品的计划中 / 可用状态标签',
    'Mobile in this guide means EnvoyGo': '本指南中的移动指的是 EnvoyGo',
    'thin client paired to a home node': '配对到家庭节点的瘦客户端',
    'unless a section explicitly discusses legacy mobile experiments': '除非某个部分明确讨论遗留的移动实验',
    'implemented and intended for current use': '已实现并打算当前使用',
    'implemented, but still receiving validation or product polish': '已实现，但仍在接受验证或产品打磨',
    'usable for evaluation; behavior or interfaces may change': '可用于评估；行为或接口可能会更改',
    'EnvoyMesh includes configuration for the integration': 'EnvoyMesh 包含集成配置',
    'while part of the integration is maintained by another project': '而集成的一部分由另一个项目维护',
    'designed or documented, but not currently available as a complete product feature': '已设计或文档化，但当前不可用作为完整的产品功能',
    'intentionally deferred without a committed release date': '有意推迟，没有确定的发布日期',
    'available through the EnvoyMesh desktop application or home node': '可通过 EnvoyMesh 桌面应用或家庭节点使用',
    'available in EnvoyGo, the current EnvoyMesh mobile product': '在 EnvoyGo 中可用，这是当前的 EnvoyMesh 移动产品',
    'home-paired thin client': '家庭配对瘦客户端',
    'intended for node, relay, or fleet administrators': '面向节点、中继或集群管理员',
    'EnvoyAI / OpenClaw is the richer bundled agent integration included with EnvoyMesh': 'EnvoyAI / OpenClaw 是 EnvoyMesh 中包含的更丰富的捆绑智能体集成',
    'HomeClaw and Hermes are built-in external-agent compatibility presets': 'HomeClaw 和 Hermes 是内置的外部智能体兼容性预设',
    'OpenHuman is a built-in compatibility preset that is disabled by default': 'OpenHuman 是默认禁用的内置兼容性预设',
    'Agent-side code for HomeClaw, Hermes, and OpenHuman is maintained by their respective projects': 'HomeClaw、Hermes 和 OpenHuman 的智能体端代码由各自的项目维护',
    'EnvoyMesh provides the bridge, presets, policy boundary, and mesh tools': 'EnvoyMesh 提供桥接、预设、策略边界和网络工具',
    'Agent Network means bonded people allowing their opted-in local agents to collaborate': '智能体网络指的是已绑定的用户允许其选择加入的本地智能体进行协作',
    'It is not a public agent marketplace': '它不是公共智能体市场',
    'Team jobs is the user-facing name for multi-agent collaboration': '团队任务是多智能体协作的用户面向名称',
    'Source code and older documentation may call these workflows chains': '源代码和旧文档可能将这些工作流称为链',
    'EnvoyGo is the current mobile product': 'EnvoyGo 是当前的移动产品',
    'a thin client that pairs to a home EnvoyMesh node': '一个配对到家庭 EnvoyMesh 节点的瘦客户端',
    'The earlier Capacitor mobile tree': '早期的 Capacitor 移动树',
    'in-process full node': '进程内完整节点',
    'is a legacy experiment and is not the primary mobile application': '是一个遗留实验，不是主要的移动应用',
    'Running EnvoyGo itself as a full mesh node is parked': '将 EnvoyGo 本身作为完整网络节点运行已暂停',
    'EnvoyMesh connects people and AI agents through a private mesh rather than a central account service': 'EnvoyMesh 通过私有网络连接人类和 AI 智能体，而不是中央账户服务',
    'Each participant keeps a local identity': '每个参与者保留本地身份',
    'chooses trusted contacts': '选择可信联系人',
    'bonded at one of four user-selectable trust tiers': '绑定在四个用户可选的信任等级之一',
    'blocked': '阻止',
    'public': '公开',
    'referred': '推荐',
    'direct': '直接',
    'self is the implicit tier for your own owner': 'self 是您自己的所有者、设备和智能体的隐式等级',
    'devices': '设备',
    'agents': '智能体',
    'decides which agents, tools, and information may cross those relationships': '并决定哪些智能体、工具和信息可以跨越这些关系',
    'The home node stores identity, policy, conversations, tasks, and knowledge locally': '家庭节点在本地存储身份、策略、对话、任务和知识',
    'Peer-to-peer transport is preferred': '优先使用点对点传输',
    'so routine communication does not depend on a hosted application database': '因此日常通信不依赖于托管的应用数据库',
    'You create cryptographic identities instead of registering a global username and password': '您创建加密身份，而不是注册全球用户名和密码',
    'Public relays may help peers find and reach each other': '公共中继可以帮助对等节点找到并联系彼此',
    'but they are not an account authority': '但它们不是账户权威',
    'Owner keys establish control': '所有者密钥建立控制权',
    'bonds record relationships': '绑定记录关系',
    'sensitivity labels protect data': '敏感度标签保护数据',
    'Backups therefore matter': '因此备份很重要',
    'losing the only copy of an owner key can mean losing continuity of that identity': '丢失所有者密钥的唯一副本可能意味着该身份的连续性丢失',
    'EnvoyMesh first attempts a direct peer path': 'EnvoyMesh 首先尝试直接对等节点路径',
    'When NAT, firewalls, or mobility prevent that path': '当 NAT、防火墙或移动性阻止该路径时',
    'an optional relay supplies rendezvous and forwarding': '可选的中继提供会合和转发功能',
    'without becoming the application brain': '而不会成为应用程序的核心',
    'EnvoyAI is the bundled OpenClaw-based assistant': 'EnvoyAI 是基于 OpenClaw 的捆绑助手',
    'A separate bridge can connect HomeClaw, Hermes, OpenHuman': '一个单独的桥接可以连接 HomeClaw、Hermes、OpenHuman',
    'or a custom HTTP agent': '或自定义 HTTP 智能体',
    'without giving that external process raw P2P keys': '而不向该外部进程提供原始 P2P 密钥',
    'Agent Network lets bonded owners opt their local agents into Team jobs': '智能体网络允许已绑定的所有者将其本地智能体选择加入团队任务',
    'The requesting node plans work': '请求节点计划工作',
    'eligible workers execute locally': '合格的工作节点在本地执行',
    'the orchestrator combines attributed results': '协调者合并带有归属信息的结果',
    'Native signed EnvoyMesh envelopes remain the internal protocol': '原生签名的 EnvoyMesh 信封仍然是内部协议',
    'MCP exposes tools to compatible applications': 'MCP 向兼容应用暴露工具',
    'while A2A publishes agent discovery and task interfaces at the network edge': '而 A2A 在网络边缘发布智能体发现和任务接口',
    'Available areas include': '可用领域包括',
    'messaging': '消息传递',
    'groups': '群组',
    'audio': '音频',
    'voice calls': '语音通话',
    'files': '文件',
    'profiles': '资料',
    'personal AI': '个人 AI',
    'knowledge and RAG': '知识和 RAG',
    'external-agent bridges': '外部智能体桥接',
    'terminals': '终端',
    'relays': '中继',
    'Some capabilities remain platform-specific or deferred': '某些功能仍然是平台特定的或已推迟',
    'In particular': '特别是',
    'video calls': '视频通话',
    'broad anonymous worker recruitment': '广泛的匿名工作节点招募',
    'full-node EnvoyGo operation': '完整节点的 EnvoyGo 操作',
    'global reputation': '全球声誉',
    'commerce': '商业',
    'Filecoin persistence': 'Filecoin 持久性',
    'a complete hierarchical relay graph': '完整的分层中继图',
    'are not current general features': '目前不是通用功能',
    'EnvoyMesh treats messaging as signed peer traffic rather than rows in a hosted database': 'EnvoyMesh 将消息传递视为签名的对等节点流量，而不是托管数据库中的行',
    'You choose who appears in your contact list': '您选择谁出现在您的联系人列表中',
    'conversations stay on devices you control': '对话保留在您控制的设备上',
    'unless you explicitly share outward': '除非您明确向外共享',
    'This differs from centralized messengers': '这与集中式信使不同',
    'that can change terms, scan content, or freeze accounts without your keys': '后者可以在没有您的密钥的情况下更改条款、扫描内容或冻结账户',
    'Your owner identity is an Ed25519 keypair': '您的所有者身份是 Ed25519 密钥对',
    'not a username registered by a vendor': '而不是供应商注册的用户名',
    'Devices and agents derive from that owner with signed certificates and mandates': '设备和智能体通过签名证书和授权从该所有者派生',
    'so you can prove continuity across laptops, desktops, and paired phones': '因此您可以在笔记本电脑、台式机和配对手机之间证明连续性',
    'Losing the only copy of an owner key can end that identity history': '丢失所有者密钥的唯一副本可能会结束该身份的历史',
    'so backup and recovery planning matter from day one': '因此备份和恢复计划从第一天就很重要',
    'EnvoyAI and external agents run on your home node': 'EnvoyAI 和外部智能体在您的家庭节点上运行',
    'under bond policy, mandate limits, and optional human approvals': '受绑定策略、授权限制和可选的人工审批约束',
    'You decide which models, tools, and contacts an agent may use': '您决定智能体可以使用哪些模型、工具和联系人',
    'instead of accepting a vendor default automation scope': '而不是接受供应商的默认自动化范围',
    'Remote model providers receive only prompts': '远程模型提供商仅接收提示',
    'the node approves after its semantic firewall and policy checks': '节点在其语义防火墙和策略检查后批准的',
    'Notes and files live in your Vault': '笔记和文件存储在您的保险库中',
    'appear in the Library UI': '出现在库界面中',
    'can be shared with sensitivity labels': '并可以通过敏感度标签进行共享',
    'that the Bonds engine enforces': '由绑定引擎强制执行的',
    'Bonded contacts can query your public or friends-tier material': '已绑定的联系人可以查询您的公开或朋友等级的材料',
    'through knowledge.query': '通过 knowledge.query',
    'while strangers see only the public sub-graph': '而陌生人只能看到公开子图',
    'and are rate-limited': '并受到限速',
    'Publishing for browsing uses separate web-content paths': '发布以供浏览使用单独的网络内容路径',
    'visibility rules described in Part V': '以及第五部分中描述的可见性规则',
    'Task delegation uses owner-signed mandates': '任务委托使用所有者签名的授权',
    'that cap cost, sensitivity, allowed actions, and expiry': '这些授权限制成本、敏感度、允许的操作和过期时间',
    'An agent cannot silently exceed those bounds': '智能体不能静默地超出这些限制',
    'risky steps can require explicit approval before execution': '有风险的步骤可能需要在执行前获得明确批准',
    'This makes autonomous work legible': '这使自主工作清晰可读',
    'rather than a black box running on someone else servers': '而不是在其他人的服务器上运行的黑盒',
    'Agent Network is opt-in collaboration among bonded owners': '智能体网络是已绑定所有者之间的选择加入协作',
    'not an anonymous worker marketplace': '而不是匿名工作者市场',
    'Team jobs let your local agent plan work': '团队任务允许您的本地智能体计划工作',
    'and call workers you already trust': '并调用您已经信任的工作者',
    'with attributed results returned to the orchestrator': '带有归属信息的结果返回到协调者',
    'You stay in control of which contacts agents may participate': '您可以控制哪些联系人的智能体可以参与',
    'EnvoyMesh supports local inference': 'EnvoyMesh 支持本地推理',
    'configured remote providers': '配置的远程提供商',
    'and external HTTP agents such as HomeClaw or Hermes': '以及 HomeClaw 或 Hermes 等外部 HTTP 智能体',
    'through a single bridge at a time': '通过单个桥接同时支持',
    'The node signs mesh traffic on the agent behalf': '节点代表智能体签署网络流量',
    'without handing over Ed25519 keys': '而不交出 Ed25519 密钥',
    'Mix providers to balance privacy, latency, and capability': '混合提供商以平衡隐私、延迟和能力',
    'without locking into one vendor stack': '而不锁定到一个供应商栈',
    'Operations append JSONL audit events': '操作会附加 JSONL 审计事件',
    'with correlation IDs that stitch multi-step flows together': '带有关联 ID，这些 ID 将多步骤流程拼接在一起',
    'You can review what an agent attempted': '您可以查看智能体尝试了什么',
    'what policy allowed or denied': '策略允许或拒绝了什么',
    'and which peer participated': '以及哪个对等节点参与了',
    'This audit trail complements chat history': '此审计跟踪在诊断自动化或共享争议时补充聊天历史',
    'when diagnosing automation or sharing disputes': '当诊断自动化或共享争议时',
    'EnvoyMesh fits when you want cryptographic identity': '当您需要加密身份、明确的信任等级、优先本地存储以及在您的策略控制下的智能体工具时，EnvoyMesh 是合适的选择',
    'explicit trust tiers': '明确的信任等级',
    'local-first storage': '优先本地存储',
    'and agent tooling under your policy': '以及在您的策略控制下的智能体工具',
    'It works well for small trusted groups': '它适用于小型可信群体',
    'personal AI with mesh reach': '具有网络覆盖范围的个人 AI',
    'and teams that need verifiable messaging plus delegated tasks': '以及需要可验证消息传递和委托任务的团队',
    'Start with one home node and a few bonded contacts': '从一个家庭节点和几个已绑定的联系人开始',
    'before expanding relays or Agent Network membership': '在扩展中继或智能体网络成员资格之前',
    'A global consumer messenger with effortless signup': '一个具有轻松注册、大规模群组和供应商管理的审核功能的全球消费者信使',
    'massive groups': '大规模群组',
    'vendor-managed moderation': '供应商管理的审核功能',
    'may serve you better than running a home node': '可能比运行家庭节点更适合您',
    'Likewise': '同样',
    'if you only need a single cloud chatbot': '如果您只需要一个没有对等关系或本地保险库的单一云聊天机器人',
    'with no peer relationships or local vault': '没有对等关系或本地保险库',
    'a hosted assistant is simpler': '托管助手更简单',
    'EnvoyMesh rewards operators willing to own keys': 'EnvoyMesh 奖励愿意拥有密钥、备份和信任决策的操作员',
    'backups': '备份',
    'trust decisions': '信任决策',
    'Add contacts through introductions, QR pairing, or relay-assisted discovery': '通过介绍、二维码配对或中继辅助发现添加联系人',
    'once you verify their public key fingerprint': '验证他们的公钥指纹后',
    'Bonds record trust tiers': '绑定记录信任等级',
    'that gate what each peer may request': '这些等级控制每个对等节点可以请求什么',
    'You can upgrade or downgrade trust': '您可以随着关系变化升级或降级信任',
    'as relationships change without migrating to a new account': '而无需迁移到新账户',
    'Send one-to-one chat as signed envelopes': '发送一对一聊天，作为签名信封',
    'with human-to-human role policy enforced by the protocol': '带有协议强制执行的人与人角色策略',
    'Messages prefer direct libp2p paths': '消息优先使用直接 libp2p 路径',
    'and fall back to circuit relay': '当 NAT 阻止直接连接时回退到电路中继',
    'when NAT blocks a straight connection': '当 NAT 阻止直接连接时',
    'Read receipts and delivery behavior': '阅读回执和传递行为',
    'follow the settings in Social or EnvoyGo': '遵循配对到家庭节点后在 Social 或 EnvoyGo 中的设置',
    'once paired to your home node': '配对到您的家庭节点后',
    'Create group threads that include multiple bonded contacts': '创建包含多个已绑定联系人的群组线程',
    'with the same signature and policy guarantees as direct chat': '具有与直接聊天相同的签名和策略保证',
    'Group membership and naming are local-first constructs': '群组成员身份和命名是通过您的节点协调的本地优先结构',
    'coordinated through your node': '通过您的节点协调的',
    'Use groups for family, project, or research circles': '将群组用于家庭、项目或研究圈子',
    'where everyone already shares an explicit trust relationship': '其中每个人已经共享明确的信任关系',
    'Record short audio clips in chat': '在聊天中录制短音频片段',
    'or start voice calls when both sides support the feature': '或在双方都支持该功能且策略允许时开始语音通话',
    'and policy allows': '且策略允许时',
    'Media flows over the same mesh transport as messages': '媒体通过与消息相同的网络传输',
    'rather than through a separate proprietary calling backend': '而不是通过单独的专有通话后端',
    'Quality and availability depend on network paths': '质量和可用性取决于网络路径',
    'and whether peers are reachable via direct or relayed connections': '以及对等节点是否可以通过直接或中继连接访问',
    'Share files with contacts using signed data-transfer vouchers': '使用签名的数据传输凭证与联系人共享文件',
    'that land in vault inbox folders on the recipient side': '这些凭证在接收方端的保险库收件箱文件夹中着陆',
    'Profile photos and avatars follow the same identity and storage model': '资料照片和头像遵循与其他本地资产相同的身份和存储模型',
    'as other local assets': '与其他本地资产相同',
    'Recipients index received files under their own sensitivity rules': '接收方根据自己的敏感度规则索引收到的文件',
    'Chat with EnvoyAI': '与 EnvoyAI 聊天',
    'bundled OpenClaw': '捆绑的 OpenClaw',
    'from Social desktop': '从 Social 桌面',
    'or through EnvoyGo when paired to a running home node': '或在配对到运行中的家庭节点时通过 EnvoyGo',
    'The assistant can search your vault': '助手可以搜索您的保险库',
    'message bonded contacts': '向已绑定的联系人发送消息',
    'and invoke allowed tools subject to mandates and approvals': '并根据授权和审批调用允许的工具',
    'Enable or disable the bundled agent in Settings': '在设置 → AI 中启用或禁用捆绑智能体',
    'AI according to your comfort with automation': '根据您对自动化的舒适度',
    'Connect HomeClaw, Hermes, OpenHuman': '连接 HomeClaw、Hermes、OpenHuman',
    'or a custom HTTP agent through Settings': '或自定义 HTTP 智能体',
    'AI': 'AI',
    'Ext Agent when you prefer an external runtime over bundled EnvoyAI': '外部智能体，当您更喜欢外部运行时而不是捆绑的 EnvoyAI 时',
    'EnvoyMesh translates mesh tools into the external agent message contract': 'EnvoyMesh 将网络工具转换为外部智能体的消息契约',
    'without exposing raw libp2p keys': '而不暴露原始 libp2p 密钥',
    'Only one external bridge runs at a time': '一次只运行一个外部桥接',
    'verify you trust the local endpoint before enabling it': '在启用之前验证您信任本地端点',
    'Search your vault locally from the Library tab': '从库选项卡本地搜索您的保险库',
    'or ask EnvoyAI to retrieve chunks through the RAG pipeline': '或让 EnvoyAI 通过保存时索引的 RAG 管道检索块',
    'indexed on save': '保存时索引的',
    'Federated search can query bonded contacts syndicated knowledge': '联合搜索可以在您为每个联系人配置的敏感度上限内查询已绑定联系人的联合知识',
    'within sensitivity ceilings you configure per contact': '在您为每个联系人配置的敏感度上限内',
    'Public notes participate in the wider mesh': '公开笔记通过对陌生人的限速 knowledge.query 参与更广泛的网络',
    'through rate-limited knowledge.query for strangers': '通过对陌生人的限速 knowledge.query',
    'Publish Markdown, images, and PDFs under envoy:// URLs': '在 envoy:// URL 下发布 Markdown、图像和 PDF',
    'served from your home node web content directory': '从您的家庭节点的网络内容目录提供服务',
    'Bonded contacts': '已绑定的联系人',
    'and when visibility allows': '以及在可见性允许时',
    'wider mesh peers': '更广泛的网络对等节点',
    'open pages in the Social Browser or EnvoyGo Browser': '在 Social 浏览器或 EnvoyGo 浏览器中打开页面',
    'while paired to home': '在配对到家庭时',
    'Pull-based library.read fetches bytes on demand': '基于拉取的 library.read 按需获取字节',
    'push notifications for feeds arrived in Phase 45E': '订阅源的推送通知在阶段 45E 中推出',
    'Send a task mandate to another owner agent': '向另一个所有者的智能体发送任务授权',
    'when you need specialized work within signed bounds': '当您需要在签名范围内进行专业工作时',
    'Negotiation follows the task lifecycle': '协商遵循任务生命周期',
    'from propose through accept, running, and result': '从提议到接受、运行和结果',
    'Human approval gates remain available': '人工审批门仍然可用',
    'for actions the mandate marks as sensitive': '对于授权标记为敏感的操作',
    'Run Team jobs': '运行团队任务',
    'multi-agent chains': '多智能体链',
    'across opted-in Agent Network members': '在选择加入的智能体网络成员上',
    'when bonded owners allow their agents to collaborate': '当已绑定的所有者允许其智能体协作时',
    'The requesting node plans steps': '请求节点计划步骤',
    'workers execute locally on their own hardware': '工作节点在自己的硬件上本地执行',
    'and results return with attribution': '结果带有归属信息返回',
    'This is suited to research summaries': '这适用于研究摘要',
    'split analysis': '拆分分析',
    'or coordinated reports': '或协调报告',
    'not open recruitment of anonymous workers': '而不是匿名工作者的公开招募',
    'Expose selected mesh tools to MCP-compatible desktop apps': '向兼容 MCP 的桌面应用（如 Claude Desktop）暴露选定的网络工具',
    'such as Claude Desktop': '如 Claude Desktop',
    'or publish an A2A agent card for external task clients': '或为外部任务客户端发布 A2A 智能体卡片',
    'MCP and A2A sit at the network edge': 'MCP 和 A2A 位于网络边缘',
    'native signed envelopes remain the internal protocol': '原生签名信封仍然是内部协议',
    'Configure bridges only after you understand': '只有在您了解哪些工具跨越边界后，才配置桥接',
    'which tools cross the boundary': '哪些工具跨越边界',
    'Open browser-based terminals in Social or EnvoyGo': '在配对或在桌面上时，通过 WebSocket 在 Social 或 EnvoyGo 中打开基于浏览器的终端',
    'that attach to PTY sessions on your home node over WebSocket': '这些终端连接到您的家庭节点上的 PTY 会话',
    'when you are paired or on desktop': '当您配对或在桌面上时',
    'Remote shell access inherits the same authentication': '远程 shell 访问继承与其他家庭 RPC 功能相同的身份验证和配对模型',
    'and pairing model as other home RPC features': '和配对模型',
    'Treat terminal exposure as high privilege': '将终端暴露视为高权限',
    'and restrict it to devices you control': '并将其限制为您控制的设备',
    'Run a private relay for your fleet': '为您的集群运行私有中继',
    'or bootstrap against the community relay for casual testing': '或针对社区中继进行引导以进行临时测试',
    'Relays provide rendezvous and circuit forwarding': '中继提供会合和电路转发',
    'they do not store your messages': '它们不存储您的消息',
    'run models': '运行模型',
    'or act as account servers': '或充当账户服务器',
    'Operators advertise listen addresses': '操作员公布监听地址',
    'and may configure hierarchical relay graphs for larger deployments': '并可以为更大的部署配置分层中继图',
    'At a high level': '从高层次来看',
    'your home node combines identity': '您的家庭节点在一个进程中结合了身份、策略、存储、模型和 libp2p 网络',
    'policy, storage, models': '策略、存储、模型',
    'and libp2p networking in one process': '和 libp2p 网络',
    'Social desktop and paired EnvoyGo are thin clients': 'Social 桌面和配对的 EnvoyGo 是调用该节点上的 JSON-RPC 的瘦客户端',
    'that call JSON-RPC on that node': '调用该节点上的 JSON-RPC',
    'Inbound traffic passes through guards': '入站流量在任何模型或保险库访问发生之前，先经过大小、签名、重放和绑定决策的防护',
    'for size, signature, replay, and bond decisions': '大小、签名、重放和绑定决策',
    'before any model or vault access occurs': '在任何模型或保险库访问发生之前',
    'The owner key is the long-lived human root': '所有者密钥是长期的人类根',
    'devices receive owner-signed certificates': '设备接收所有者签名的证书',
    'agents receive mandates linking them to that owner': '智能体接收将它们链接到该所有者的授权',
    'Runtime peer IDs sign individual envelopes': '运行时对等 ID 签署单个信封',
    'and may rotate with keys while preserving trust links': '并可能在保留信任链接的同时随密钥轮换',
    'Understanding this stack helps you reason about backups': '理解这个堆栈有助于您推理备份、配对和智能体授权',
    'pairing': '配对',
    'and agent authorization': '和智能体授权',
    'Contacts map to bond records with tiers': '联系人映射到具有信任等级的绑定记录',
    'that determine which intents and sensitivity levels are allowed': '这些等级确定允许哪些意图和敏感度级别',
    'Public strangers may ping or request bonds': '公开陌生人可以 ping 或请求绑定',
    'referred contacts gain broader query access': '推荐联系人获得更广泛的查询访问',
    'direct bonds unlock friends-tier sharing': '直接绑定解锁朋友等级分享',
    'Policy evaluation is deterministic and logged for audit': '策略评估是确定性的，并记录用于审计',
    'Every envelope carries an Ed25519 signature': '每个信封都带有 Ed25519 签名',
    'over canonical JSON so recipients verify sender identity': '覆盖规范 JSON，以便接收者在对内容采取行动之前验证发送者身份',
    'before acting on content': '在对内容采取行动之前',
    'Role fields enforce human-to-human chat': '角色字段在架构层面强制执行人与人聊天与智能体与智能体任务流量',
    'versus agent-to-agent task traffic at the schema level': '与智能体与智能体任务流量',
    'Tampered or replayed messages fail inbound guards': '被篡改或重放的消息在入站防护中失败',
    'Bundled EnvoyAI runs in-process with mesh tools': '捆绑的 EnvoyAI 进程内运行并带有网络工具',
    'while external agents connect through an HTTP bridge': '而外部智能体通过 HTTP 桥接连接',
    'that never receives your private signing keys': '该桥接从不接收您的私钥签名',
    'The bridge forwards allowed tool calls': '桥接转发允许的工具调用',
    'and translates responses into mesh envelopes': '并将响应转换为网络信封',
    'Choose one primary agent surface': '选择一个主要的智能体界面以避免冲突的自动化',
    'to avoid conflicting automation': '以避免冲突的自动化',
    'The Vault stores files on disk under path-safe rules': '保险库在路径安全规则下将文件存储在磁盘上',
    'the Library is the UI and metadata layer': '库是笔记、导入和发布项目的 UI 和元数据层',
    'for notes, imports, and published items': '笔记、导入和发布项目',
    'RAG indexes vault chunks for retrieval during chat': 'RAG 索引保险库块以便在聊天期间检索',
    'Sensitivity overrides live in .envoy/sensitivity.json per item': '敏感度覆盖每个项目存储在 .envoy/sensitivity.json 中',
    'not per folder': '而不是每个文件夹',
    'Web content for browsing lives under a separate web/ directory': '用于浏览的网络内容位于单独的 web/ 目录下',
    'mapped to envoy:// paths': '映射到 envoy:// 路径',
    'Tasks progress through named lifecycle states': '任务通过命名的生命周期状态进行',
    'with mandates defining authorized intent': '授权定义了授权意图、成本上限和终止策略',
    'cost ceilings': '成本上限',
    'and termination policy': '和终止策略',
    'Owners can require approval before specific actions': '所有者可以在特定操作之前要求批准',
    'even when a mandate otherwise allows automation': '即使授权允许自动化',
    'Cancel and heartbeat intents keep long-running work accountable': '取消和心跳意图使长时间运行的工作保持可问责',
    'Agent Network membership is mutual opt-in': '智能体网络成员资格是已绑定联系人之间的双向选择加入',
    'among bonded contacts who enable their agents for collaboration': '他们为协作启用了智能体',
    'It is not a public marketplace listing anonymous workers': '它不是列出匿名工作者的公共市场',
    'Team jobs consume this membership graph': '团队任务在选择合格工作者时使用此成员资格图',
    'when selecting eligible workers': '在选择合格工作者时',
    'Nodes attempt direct TCP or QUIC connections first': '节点首先尝试直接 TCP 或 QUIC 连接',
    'using mDNS on LAN': '在局域网上使用 mDNS',
    'and DHT discovery when configured': '在配置时使用 DHT 发现',
    'When NAT blocks direct paths': '当 NAT 阻止直接路径时',
    'circuit relay v2 reservations forward streams': '电路中继 v2 保留转发流',
    'without decrypting application payloads': '而不解密应用载荷',
    'You choose bootstrap relays': '您选择引导中继',
    'they assist connectivity rather than owning your identity': '它们协助连接而不是拥有您的身份',
    'Audit and journal JSONL files record intents': '审计和日志 JSONL 文件记录意图、结果、延迟和多跳流的关联 ID',
    'outcomes': '结果',
    'latency': '延迟',
    'and correlation IDs for multi-hop flows': '和多跳流的关联 ID',
    'Operators can trace a Team job': '操作员可以使用这些 ID 跨对等节点跟踪团队任务、知识查询或文件传输',
    'knowledge query': '知识查询',
    'or file transfer across peers': '或文件传输',
    'using those IDs': '使用这些 ID',
    'Logs intentionally avoid storing raw sensitive payloads': '日志有意避免存储原始敏感载荷',
    'unless required for debugging policy': '除非需要用于调试策略',
    'Run EnvoyAI on a desktop home node': '在桌面家庭节点上运行 EnvoyAI',
    'and reach it from Social locally': '并从本地 Social 或外出时通过 EnvoyGo 访问它',
    'or EnvoyGo when paired away from home': '或外出时通过 EnvoyGo',
    'Your vault, models, and bonds stay on the computer you trust': '您的保险库、模型和绑定保留在您信任的计算机上',
    'while the phone acts as a remote control': '而手机充当遥控器',
    'Back up owner keys and vault data': '备份所有者密钥和保险库数据',
    'so device loss does not strand your agent history': '以便设备丢失不会使您的智能体历史搁浅',
    'Invite family or friends through introductions': '通过介绍邀请家人或朋友',
    'establish direct bonds': '建立直接绑定',
    'and use group chat plus file sharing': '并使用群聊和文件共享',
    'without a shared cloud account': '无需共享云账户',
    'Each participant keeps their own node and data': '每个参与者保留自己的节点和数据',
    'sharing is explicit through messages': '共享通过消息、凭证和联合知识设置显式进行',
    'vouchers': '凭证',
    'and syndicated knowledge settings': '和联合知识设置',
    'Relays help when members are on different networks': '当成员在不同网络上时，中继会有所帮助',
    'Exchange research notes with public or friends sensitivity': '以公开或朋友敏感度交换研究笔记',
    'query peers syndicated libraries': '查询对等节点的联合库',
    'and save attributed results back to your vault': '并通过 MCP 写回将归属结果保存回您的保险库',
    'through MCP write-back': '通过 MCP 写回',
    'Federated RAG respects per-contact ceilings': '联合 RAG 尊重每个联系人的上限',
    'so you never silently exfiltrate private material': '因此您永远不会静默泄露私人材料',
    'Publish finished summaries as mesh pages': '当您需要持久的 envoy:// 链接时，将完成的摘要发布为网格页面',
    'when you want durable envoy:// links': '当您需要持久的 envoy:// 链接时',
    'Enable Agent Network among a small team': '在已经共享直接绑定和对齐授权的小型团队中启用智能体网络',
    'that already shares direct bonds and aligned mandates': '已经共享直接绑定和对齐授权',
    'Assign Team jobs for split research': '分配团队任务进行拆分研究、代码审查辅助或草稿报告',
    'code review assistance': '代码审查辅助',
    'or draft reports': '或草稿报告',
    'with each worker executing on local hardware': '每个工作者在本地硬件上执行',
    'Review audit trails to see which agent contributed each segment': '查看审计跟踪以查看哪个智能体贡献了每个段',
    'Plan a multi-step report': '规划一个多步骤报告',
    'where one agent outlines sections': '其中一个智能体概述部分',
    'workers gather evidence from local vaults': '工作者从本地保险库收集证据',
    'and the orchestrator merges attributed text': '协调者合并归属文本',
    'Mandates cap cost and require approval': '授权限制成本，并要求在发送外部电子邮件或花费积分之前获得批准',
    'before sending external email or spending credits': '在发送外部电子邮件或花费积分之前',
    'Results land in chat': '结果出现在聊天中',
    'and can be saved as vault notes for later citation': '并可以保存为保险库笔记以供日后引用',
    'Keep OpenClaw as EnvoyAI on your node': '在您的节点上保持 OpenClaw 作为 EnvoyAI',
    'while using mesh tools to message bonded contacts': '同时使用网络工具向已绑定的联系人发送消息',
    'and search syndicated knowledge': '并搜索联合知识',
    'OpenClaw never receives raw libp2p access': 'OpenClaw 永远不会接收原始 libp2p 访问',
    'it calls mesh.findKnowledge': '它通过注册表调用 mesh.findKnowledge、mesh.sendMessage 和相关工具',
    'mesh.sendMessage': 'mesh.sendMessage',
    'and related tools through the registry': '和相关工具',
    'This pattern suits power users': '这种模式适合想要 OpenClaw 技能并具有可信对等节点访问权限的高级用户',
    'who want OpenClaw skills with trusted peer reach': '想要 OpenClaw 技能并具有可信对等节点访问权限',
    'Point EnvoyMesh at a local HomeClaw HTTP endpoint': '将 EnvoyMesh 指向本地 HomeClaw HTTP 端点',
    'so HomeClaw becomes the conversational surface': '使 HomeClaw 成为对话表面',
    'while the node handles identity and mesh I/O': '而节点处理身份和网格 I/O',
    'HomeClaw own memory and plugins stay in its process': 'HomeClaw 自己的内存和插件保留在其进程中',
    'EnvoyMesh enforces bonds on outbound actions': 'EnvoyMesh 对出站操作强制执行绑定',
    'Enable the preset only on machines': '仅在您已经运行并信任 HomeClaw 的机器上启用预设',
    'where you already run and trust HomeClaw': '您已经运行并信任 HomeClaw 的',
    'Use Hermes when you prefer its Obsidian-style knowledge tooling': '当您喜欢其 Obsidian 风格的知识工具以及网格消息传递时，使用 Hermes',
    'alongside mesh messaging': '以及网格消息传递',
    'The bridge forwards Hermes responses': '桥接通过与其他外部智能体相同的策略边界转发 Hermes 响应和工具结果',
    'and tool results through the same policy boundary': '和工具结果',
    'as other external agents': '与其他外部智能体相同',
    'Configure the default http://127.0.0.1:8020/message endpoint': '在设置 → AI 中配置默认的 http://127.0.0.1:8020/message 端点或您的自定义 URL',
    'or your custom URL in Settings': '或您的自定义 URL',
    'OpenHuman is available as a disabled-by-default compatibility preset': 'OpenHuman 作为默认禁用的兼容性预设提供，适用于实验该运行时的团队',
    'for teams experimenting with that runtime': '适用于实验该运行时的团队',
    'When enabled': '启用时',
    'it follows the same one-bridge-at-a-time rule': '它遵循相同的一次一桥接规则',
    'and never receives signing keys': '并且永远不会接收签名密钥',
    'Treat it as optional until your organization validates': '在您的组织验证 OpenHuman 的本地部署模型之前，将其视为可选',
    'OpenHuman local deployment model': 'OpenHuman 的本地部署模型',
    'Register EnvoyMesh as an MCP server in Claude Desktop': '在 Claude Desktop 中将 EnvoyMesh 注册为 MCP 服务器',
    'to expose mesh search, contacts': '以向 Anthropic 的客户端暴露网格搜索、联系人',
    'and messaging tools to Anthropic client': '和消息传递工具',
    'MCP crosses a desktop boundary': 'MCP 跨越桌面边界',
    'review which tools you enable': '查看您启用哪些工具',
    'and what data they can read from your vault': '以及它们可以从您的保险库读取什么数据',
    'The home node must be running for MCP sessions to succeed': '家庭节点必须运行才能使 MCP 会话成功',
    'Publish an A2A agent card from your node': '从您的节点发布 A2A 智能体卡片',
    'so external A2A clients can discover capabilities': '以便外部 A2A 客户端可以发现能力',
    'and delegate tasks through JSON-RPC proxies': '并通过 JSON-RPC 代理委托任务',
    'Home tunnel and relay paths': '家庭隧道和中继路径',
    'let remote clients reach a home node': '让远程客户端无需向外部运行时暴露原始 libp2p 即可访问家庭节点',
    'without exposing raw libp2p to the external runtime': '无需向外部运行时暴露原始 libp2p',
    'Mandates and approvals still apply to delegated work': '授权和审批仍然适用于委托工作',
    'Deploy one or more relay binaries': '部署一个或多个中继二进制文件',
    'with advertised addresses': '带有公布的地址',
    'for a family, lab, or organization': '用于家庭、实验室或组织',
    'that wants private bootstrap and circuit relay capacity': '想要私有引导和电路中继容量',
    'Relays stay lean': '中继保持精简',
    'no LLM': '没有 LLM',
    'no vault': '没有保险库',
    'no payload inspection beyond transport forwarding': '除传输转发外没有载荷检查',
    'Monitor relay audit snapshots': '操作集群基础设施时监控中继审计快照',
    'when operating fleet infrastructure': '操作集群基础设施时',
    'Centralized messengers optimize for frictionless signup': '集中式信使优化无摩擦注册',
    'phone-number identity': '电话号码身份',
    'and vendor-operated moderation at scale': '以及大规模供应商运营的审核',
    'EnvoyMesh trades that convenience': 'EnvoyMesh 用这种便利换取自主主权密钥',
    'for self-sovereign keys': '自主主权密钥',
    'explicit bonds': '明确的绑定',
    'and local-first storage you operate': '以及您操作的本地优先存储',
    'Choose messengers for mass reach': '选择信使以实现大规模覆盖',
    'choose EnvoyMesh when trust boundaries': '当信任边界和可审计性更重要时选择 EnvoyMesh',
    'and auditability matter more': '和可审计性更重要时',
    'Cloud AI assistants run inference and memory': '云 AI 助手在供应商基础设施上运行推理和内存',
    'on vendor infrastructure': '在供应商基础设施上',
    'with account login and vendor policy': '具有账户登录和供应商策略',
    'EnvoyMesh keeps models, vault, and bonds on your node': 'EnvoyMesh 将模型、保险库和绑定保留在您的节点上',
    'while optionally calling remote providers you configure': '同时可选地调用您配置的远程提供商',
    'You gain mesh reach and mandates': '您获得网络覆盖范围和授权',
    'instead of a single-vendor chat history silo': '而不是单一供应商的聊天历史孤岛',
    'Standalone OpenClaw excels as a local assistant': '独立的 OpenClaw 作为本地助手表现出色',
    'but lacks native signed peer messaging': '但缺少原生签名对等消息传递、绑定策略和联合知识，除非扩展',
    'bond policy': '绑定策略',
    'and federated knowledge unless extended': '和联合知识，除非扩展',
    'EnvoyMesh bundles OpenClaw as EnvoyAI': 'EnvoyMesh 将 OpenClaw 捆绑为 EnvoyAI',
    'and wraps it with mesh tools': '并用网络工具、授权和审计包装它',
    'mandates': '授权',
    'and audit': '和审计',
    'Running both without integration duplicates agents': '在没有集成的情况下同时运行两者会重复智能体，除非您禁用其中一个',
    'unless you disable one': '除非您禁用其中一个',
    'External agent runtimes': '外部智能体运行时',
    'HomeClaw': 'HomeClaw',
    'Hermes': 'Hermes',
    'custom HTTP': '自定义 HTTP',
    'focus on conversation and plugins': '专注于对话和插件',
    'EnvoyMesh supplies identity, transport': 'EnvoyMesh 提供身份、传输和策略',
    'and policy': '和策略',
    'The bridge pattern keeps libp2p keys on the node': '桥接模式将 libp2p 密钥保留在节点上',
    'while the external process handles UX you prefer': '而外部进程处理您偏好的用户体验',
    'Neither side replaces the other': '双方都不取代对方',
    'they compose when configured deliberately': '在有意配置时它们组合',
    'MCP standardizes tool discovery for AI applications': 'MCP 标准化 AI 应用的工具发现',
    'EnvoyMesh implements an MCP adapter': 'EnvoyMesh 实现了一个 MCP 适配器',
    'that exposes selected mesh capabilities': '该适配器暴露选定的网络能力',
    'Native mesh intents remain richer and signed': '原生网格意图仍然更丰富且已签名',
    'MCP is an interoperability edge for desktop clients': 'MCP 是桌面客户端的互操作性边缘',
    'Enable MCP tools narrowly': '狭义启用 MCP 工具以限制保险库和联系人暴露',
    'to limit vault and contact exposure': '以限制保险库和联系人暴露',
    'A2A defines agent cards and task interfaces': 'A2A 定义跨产品委托的智能体卡片和任务接口',
    'for cross-product delegation': '跨产品委托',
    'EnvoyMesh publishes cards and proxies tasks': 'EnvoyMesh 通过中继或家庭隧道路径发布卡片并代理任务',
    'through relay or home tunnel paths': '通过中继或家庭隧道路径',
    'Native Team jobs and mandates govern trust': '原生团队任务和授权管理网格内的信任',
    'inside the mesh': '网格内',
    'A2A extends reach to external orchestrators': 'A2A 将覆盖范围扩展到外部协调者',
    'Both can coexist with different policy surfaces': '两者可以共存，具有不同的策略表面',
    'Public agent marketplaces optimize for discovery': '公共智能体市场优化匿名工作者的发现',
    'of anonymous workers': '匿名工作者的',
    'and commercial ranking': '和商业排名',
    'EnvoyMesh Agent Network is the opposite': 'EnvoyMesh 智能体网络正好相反',
    'collaboration only among bonded owners': '仅在本地选择加入的已绑定所有者之间进行协作',
    'who opted in locally': '本地选择加入的',
    'There is no global listing': '原生设计中没有全球列表、声誉评分或支付通道',
    'reputation score': '声誉评分',
    'or payment rail in the native design': '或支付通道',
    'Signed Envoy envelopes': '签名的 Envoy 信封、授权和绑定等级是网格内的原生协议',
    'mandates': '授权',
    'and bond tiers are the native protocol': '和绑定等级',
    'inside the mesh': '网格内',
    'MCP and A2A bridges translate at the edge': 'MCP 和 A2A 桥接在边缘进行翻译',
    'for external ecosystems': '为外部生态系统',
    'without replacing internal security models': '而不替换内部安全模型',
    'Prefer native flows for bonded peer work': '对于已绑定对等节点工作，更喜欢原生流',
    'use bridges when an external client must participate': '当外部客户端必须参与时使用桥接',
}

SECTION_HEADINGS = {
    '# EnvoyMesh Guidebook': '# EnvoyMesh 指南',
    '**Version:**': '**版本:**',
    '**Edition:**': '**版本类型:**',
    '**Revised:**': '**修订日期:**',
    '**Languages:**': '**语言:**',
    '**Audience:**': '**受众:**',
    '**Purpose:**': '**目的:**',
    '> **Complete Guidebook Edition.**': '> **完整指南版。**',
    '## How to read this guide': '## 如何阅读本指南',
    '## Feature status labels': '## 功能状态标签',
    '## Product terminology used in this guide': '## 本指南使用的产品术语',
    '# Table of Contents': '# 目录',
    '## Part I — Discover EnvoyMesh': '## 第一部分 — 认识 EnvoyMesh',
    '### 1. Welcome to EnvoyMesh': '### 1. 欢迎来到 EnvoyMesh',
    '#### 1.1 A private network for people and AI agents': '#### 1.1 面向人类和AI智能体的私有网络',
    '#### 1.2 Local-first and peer-to-peer by design': '#### 1.2 设计上优先本地和点对点',
    '#### 1.3 No central account required': '#### 1.3 无需中央账户',
    '#### 1.4 Your identity, relationships, and data belong to you': '#### 1.4 您的身份、关系和数据属于您自己',
    '#### 1.5 Direct connections and optional relays': '#### 1.5 直接连接和可选中继',
    '#### 1.6 Personal agents and external agents': '#### 1.6 个人智能体和外部智能体',
    '#### 1.7 Trusted multi-agent collaboration': '#### 1.7 可信多智能体协作',
    '#### 1.8 Open protocols and interoperability': '#### 1.8 开放协议和互操作性',
    '#### 1.9 Major features at a glance': '#### 1.9 主要功能一览',
    '#### 1.10 Current availability and limitations': '#### 1.10 当前可用性和限制',
    '### 2. Why EnvoyMesh?': '### 2. 为什么选择 EnvoyMesh？',
    '#### 2.1 Private communication without a central platform': '#### 2.1 无需中央平台的私密通信',
    '#### 2.2 Self-sovereign identity across your devices': '#### 2.2 跨设备的自主身份',
    '#### 2.3 AI assistance under your control': '#### 2.3 由您掌控的AI助手',
    '#### 2.4 Trusted knowledge sharing': '#### 2.4 可信知识共享',
    '#### 2.5 Safe task delegation': '#### 2.5 安全的任务委托',
    '#### 2.6 Collaboration among agents you choose': '#### 2.6 您选择的智能体之间的协作',
    '#### 2.7 Local models, remote models, and external agents': '#### 2.7 本地模型、远程模型和外部智能体',
    '#### 2.8 Auditability instead of invisible automation': '#### 2.8 可审计性而非隐形自动化',
    '#### 2.9 When EnvoyMesh is the right choice': '#### 2.9 何时适合使用 EnvoyMesh',
    '#### 2.10 When another solution may be a better fit': '#### 2.10 何时其他解决方案更合适',
    '### 3. What You Can Do': '### 3. 您可以做什么',
    '#### 3.1 Connect with trusted people': '#### 3.1 与信任的人建立连接',
    '#### 3.2 Exchange private messages': '#### 3.2 交换私密消息',
    '#### 3.3 Create group conversations': '#### 3.3 创建群组对话',
    '#### 3.4 Send audio messages and make voice calls': '#### 3.4 发送语音消息和进行语音通话',
    '#### 3.5 Share files and profile photos': '#### 3.5 共享文件和资料照片',
    '#### 3.6 Talk to your personal AI agent': '#### 3.6 与您的个人AI智能体对话',
    '#### 3.7 Connect OpenClaw, HomeClaw, Hermes, or OpenHuman': '#### 3.7 连接 OpenClaw、HomeClaw、Hermes 或 OpenHuman',
    '#### 3.8 Search local and trusted knowledge': '#### 3.8 搜索本地和可信知识',
    '#### 3.9 Publish and browse mesh content': '#### 3.9 发布和浏览网络内容',
    '#### 3.10 Delegate work to another agent': '#### 3.10 将工作委托给另一个智能体',
    '#### 3.11 Run Team jobs across several agents': '#### 3.11 在多个智能体上运行团队任务',
    '#### 3.12 Connect MCP and A2A applications': '#### 3.12 连接 MCP 和 A2A 应用',
    '#### 3.13 Use terminals remotely': '#### 3.13 远程使用终端',
    '#### 3.14 Operate a private or community relay': '#### 3.14 运行私有或社区中继',
    '### 4. How EnvoyMesh Works': '### 4. EnvoyMesh 如何工作',
    '#### 4.1 A plain-language system overview': '#### 4.1 系统概览（通俗易懂版）',
    '#### 4.2 Owners, devices, agents, and peers': '#### 4.2 所有者、设备、智能体和对等节点',
    '#### 4.3 Contacts, bonds, and trust levels': '#### 4.3 联系人、绑定和信任等级',
    '#### 4.4 Signed messages and verifiable senders': '#### 4.4 签名消息和可验证发送者',
    '#### 4.5 Personal agents and external-agent bridges': '#### 4.5 个人智能体和外部智能体桥接',
    '#### 4.6 Local knowledge, the Library, and the Vault': '#### 4.6 本地知识、库和保险库',
    '#### 4.7 Tasks, mandates, and approvals': '#### 4.7 任务、授权和审批',
    '#### 4.8 Agent Network membership': '#### 4.8 智能体网络成员资格',
    '#### 4.9 Direct networking and relay assistance': '#### 4.9 直接网络和中继协助',
    '#### 4.10 Activity records and end-to-end auditing': '#### 4.10 活动记录和端到端审计',
    '### 5. Common Use Cases': '### 5. 常见用例',
    '#### 5.1 A private personal AI across devices': '#### 5.1 跨设备的私密个人AI',
    '#### 5.2 A family or friends mesh': '#### 5.2 家庭或朋友网络',
    '#### 5.3 Trusted research and knowledge exchange': '#### 5.3 可信研究和知识交流',
    '#### 5.4 A small-team Agent Network': '#### 5.4 小型团队智能体网络',
    '#### 5.5 Multi-agent planning and report generation': '#### 5.5 多智能体规划和报告生成',
    '#### 5.6 OpenClaw with trusted mesh contacts': '#### 5.6 与可信网络联系人一起使用 OpenClaw',
    '#### 5.7 HomeClaw as an external EnvoyMesh agent': '#### 5.7 将 HomeClaw 作为外部 EnvoyMesh 智能体',
    '#### 5.8 Hermes as an external EnvoyMesh agent': '#### 5.8 将 Hermes 作为外部 EnvoyMesh 智能体',
    '#### 5.9 OpenHuman as an external EnvoyMesh agent': '#### 5.9 将 OpenHuman 作为外部 EnvoyMesh 智能体',
    '#### 5.10 Claude Desktop using EnvoyMesh through MCP': '#### 5.10 通过 MCP 使用 EnvoyMesh 的 Claude Desktop',
    '#### 5.11 External A2A clients delegating tasks': '#### 5.11 委托任务的外部 A2A 客户端',
    '#### 5.12 A self-hosted relay fleet': '#### 5.12 自托管中继集群',
    '### 6. Product and Protocol Comparisons': '### 6. 产品和协议比较',
    '#### 6.1 EnvoyMesh and centralized messengers': '#### 6.1 EnvoyMesh 与集中式信使',
    '#### 6.2 EnvoyMesh and cloud AI assistants': '#### 6.2 EnvoyMesh 与云AI助手',
    '#### 6.3 EnvoyMesh and standalone OpenClaw': '#### 6.3 EnvoyMesh 与独立 OpenClaw',
    '#### 6.4 EnvoyMesh and external agent runtimes': '#### 6.4 EnvoyMesh 与外部智能体运行时',
    '#### 6.5 EnvoyMesh and MCP': '#### 6.5 EnvoyMesh 与 MCP',
    '#### 6.6 EnvoyMesh and A2A': '#### 6.6 EnvoyMesh 与 A2A',
    '#### 6.7 EnvoyMesh native Agent Network versus public marketplaces': '#### 6.7 EnvoyMesh 原生智能体网络与公共市场',
    '#### 6.8 Native protocols versus interoperability bridges': '#### 6.8 原生协议与互操作性桥接',
}

def translate_line(line):
    if line in SECTION_HEADINGS:
        return SECTION_HEADINGS[line]
    
    if line.startswith('```'):
        return line
    
    if '<svg' in line or '</svg>' in line:
        return line
    
    if '<figure' in line or '</figure>' in line:
        return line
    
    if '<figcaption' in line or '</figcaption>' in line:
        return line
    
    if line.startswith('#'):
        return line
    
    if line.startswith('|') and '|' in line[1:]:
        parts = line.split('|')
        translated_parts = []
        for part in parts:
            part = part.strip()
            if part in TERM_MAP:
                translated_parts.append(TERM_MAP[part])
            elif part.startswith('http') or part.startswith('/ip') or part.startswith('envoy://'):
                translated_parts.append(part)
            elif part.isdigit() or part == '-':
                translated_parts.append(part)
            else:
                translated_parts.append(part)
        return '|'.join(translated_parts)
    
    translated = line
    
    for en, zh in SENTENCE_TRANSLATIONS.items():
        if en in translated:
            translated = translated.replace(en, zh)
    
    for en, zh in TERM_MAP.items():
        if en in translated:
            translated = translated.replace(en, zh)
    
    if line == '':
        return line
    
    return translated

def translate_file(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    in_code_block = False
    in_svg = False
    translated_lines = []
    
    for i, line in enumerate(lines):
        line = line.rstrip('\n')
        
        if line.startswith('```'):
            in_code_block = not in_code_block
            translated_lines.append(line)
            continue
        
        if in_code_block:
            translated_lines.append(line)
            continue
        
        if '<svg' in line:
            in_svg = True
            translated_lines.append(line)
            continue
        
        if in_svg:
            translated_lines.append(line)
            if '</svg>' in line:
                in_svg = False
            continue
        
        if '<figure' in line:
            translated_lines.append(line)
            continue
        
        if '<figcaption' in line:
            translated_lines.append(line)
            continue
        
        if '</figcaption>' in line:
            translated_lines.append(line)
            continue
        
        if '</figure>' in line:
            translated_lines.append(line)
            continue
        
        translated = translate_line(line)
        translated_lines.append(translated)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(translated_lines) + '\n')
    
    print(f"Translation complete. Input: {input_file}")
    print(f"Output: {output_file}")
    print(f"Total lines: {len(translated_lines)}")

if __name__ == '__main__':
    input_file = '/Users/shileipeng/Documents/mygithub/EnvoyMesh/EnvoyMesh_GuideBook_0.1.0.md'
    output_file = '/Users/shileipeng/Documents/mygithub/EnvoyMesh/EnvoyMesh_GuideBook_0.1.0.zh-CN.md'
    
    translate_file(input_file, output_file)