import re

TERMS_TO_KEEP = {
    'EnvoyMesh', 'EnvoyGo', 'EnvoyAI', 'OpenClaw', 'HomeClaw', 'Hermes', 'OpenHuman',
    'Ed25519', 'libp2p', 'DID', 'MCP', 'A2A', 'RAG', 'IPFS', 'WebRTC', 'TURN', 'STUN',
    'JSON-RPC', 'WebSocket', 'HTTP', 'TCP', 'QUIC', 'mDNS', 'DHT', 'LAN', 'WAN', 'NAT',
    'API', 'CLI', 'QR', 'FCM', 'APNs', 'CallKit', 'VoIP', 'PTY', 'SDK', 'LLM', 'LiteLLM',
    'Ollama', 'Claude', 'Anthropic', 'OpenAI', 'Signal', 'AirDrop', 'Tauri', 'Flutter',
    'React', 'Node.js', 'TypeScript', 'Zod', 'SQLite', 'Helia', 'Kubo', 'Memex',
    'Phase 42I', 'Phase 45', 'Phase 45C', 'Phase 45E', 'Appendix J', 'Appendix K',
    'CHANGELOG.md', 'QuickStart.md', 'README.md', 'node-config.json', 'bridge-config.json',
    'bridge-identity.json', 'bundled-sponsor-friend.json', '.envoy/sensitivity.json',
    'envoy://', 'http://', 'https://', '/ip4/', '/tcp/', '/p2p/', '/p2p-circuit/',
    '@envoy', '@envoymesh/', 'mesh.', 'chat.', 'task.', 'knowledge.', 'library.',
    'vault/', 'notes/', 'documents/', 'inbox/', 'shared_vault/', 'web/', 'digests/',
    'npm', 'node', 'git', 'npm run', 'node-config', 'bridge-config', 'vault-search',
    'connectivity-status', 'relay-status', 'morning-report', 'listPendingApprovals',
    'openclawEnabled', 'bridgeEnabled', 'autonomousKillSwitch', 'openclaw-only',
    'both', 'ext-only', 'off', 'ollama', 'openai-compatible', 'anthropic-compatible',
    'litellm', 'mock', 'trustModeEnabled', 'socialProxyEnabled', 'offlineAgentEnabled',
    'friendAutopilotEnabled', 'onlineAssistantEnabled', 'autoReplyLimits', 'statusMode',
    'aiAccessLevel', 'knowledgeAccess', 'syndicationMaxSensitivity', 'disclosure',
    'debugPrefixInMessageText', 'aiSettings', 'defaultModeForNewContacts', 'manual',
    'assistant', 'auto', 'none', 'assistant_only', 'full', 'public', 'friends',
    'trusted', 'private', 'blocked', 'direct', 'referred', 'stranger', 'owner', 'device',
    'agent', 'peer', 'bond', 'mandate', 'vault', 'library', 'browser', 'terminal',
    'session', 'approval', 'audit', 'digest', 'trigger', 'profile', 'contact',
    'conversation', 'chat', 'group', 'message', 'voice', 'call', 'audio', 'video',
    'file', 'photo', 'gallery', 'share', 'transfer', 'search', 'discovery', 'network',
    'mesh', 'relay', 'bootstrap', 'circuit', 'rendezvous', 'forwarding', 'connectivity',
    'reachability', 'transport', 'encryption', 'signature', 'verification', 'proof',
    'fingerprint', 'hash', 'payload', 'envelope', 'intent', 'correlation', 'latency',
    'timeout', 'policy', 'sensitivity', 'trust', 'tier', 'visibility', 'membership',
    'identity', 'DID', 'key', 'public', 'private', 'secret', 'certificate', 'revocation',
    'backup', 'recovery', 'restore', 'migrate', 'upgrade', 'install', 'uninstall',
    'build', 'release', 'version', 'setup', 'configure', 'deploy', 'fleet', 'operator',
    'admin', 'moderation', 'telemetry', 'gateway', 'orchestration', 'runtime',
    'process', 'thread', 'service', 'daemon', 'watchdog', 'kill switch', 'killSwitch',
    'model', 'router', 'provider', 'endpoint', 'apiKey', 'modelName', 'prompt',
    'context', 'memory', 'session', 'workspace', 'plugin', 'extension', 'integration',
    'bridge', 'proxy', 'adapter', 'mirror', 'thin client', 'client', 'server',
    'node', 'home node', 'relay node', 'full node', 'capacitor', 'desktop', 'mobile',
    'iOS', 'Android', 'macOS', 'Windows', 'Linux', 'AppImage', 'DMG', '.exe',
    'distribution', 'channel', 'notarization', 'Gatekeeper', 'firewall', 'permission',
    'notification', 'push', 'background', 'battery', 'optimization', 'signing',
    'verification', 'attribution', 'approval', 'escalation', 'mandate', 'budget',
    'cost', 'maxCost', 'bid', 'award', 'chain', 'Team job', 'Team jobs',
    'digest', 'schedule', 'cron', 'interval', 'one-shot', 'daily', 'weekly',
    'follow-up', 'check-in', 'proactive', 'autonomous', 'auto-reply', 'draft',
    'assistant', 'gatekeeper', 'escalate', 'acknowledge', 'pending', 'expired',
    'chain_award', 'trust', 'block', 'mute', 'remove', 'restore', 'revoke',
    'introduce', 'refer', 'upgrade', 'downgrade', 'sync', 'refresh', 'fetch',
    'publish', 'unpublish', 'import', 'export', 'archive', 'delete', 'index',
    'chunk', 're-index', 'discover', 'query', 'browse', 'read', 'write', 'list',
    'propose', 'accept', 'reject', 'negotiate', 'run', 'result', 'partial',
    'completed', 'failed', 'cancelled', 'created', 'planned', 'discovering',
    'negotiating', 'waiting_for_peer', 'waiting_for_owner', 'running',
    'collectCompletedResults', 'closeOnFirstCompletedResult',
    'requireApprovalFor', 'allowedActions', 'disallowedActions', 'maxSensitivity',
    'expiresAt', 'Knowledge Base', 'ToolRegistry', 'Bond Engine', 'Inbound Guard',
    'Task Runtime', 'Brain', 'Semantic Firewall', 'Vault', 'Library', 'Browser',
    'Terminal', 'Approvals', 'Activity', 'Profile', 'Settings', 'People',
    'Conversations', 'Chat', 'Groups', 'Rooms', 'Discover', 'Me', 'Identity',
    'Agent Network', 'Ext Agent', 'AI Engine', 'Knowledge Base', 'Plugins',
    'Automation', 'Notifications', 'Privacy', 'Node', 'Pairing', 'Home',
    'Social', 'HomeRemote', 'HomeClaw HTTP endpoint', 'Hermes', 'OpenHuman',
    'Claude Desktop', 'Obsidian', 'Memex', 'envoy:owner:', 'envoy:device:', 'envoy:agent:',
    'envoy_', 'owner ID', 'device ID', 'agent ID', 'peer ID', 'display name',
    'bio', 'avatar', 'thumbnail', 'photo', 'gallery', 'proof text',
    'pairing queue', 'invitation link', 'multiaddr', 'listening address',
    'advertise address', 'bootstrap address', 'relay address', 'listen',
    'bootstrap', 'relay-server', 'relay', 'connectivity-status', 'relay-status',
    'mesh.search', 'mesh.findKnowledge', 'mesh.sendMessage', 'mesh.intro',
    'mesh.add-trigger', 'mesh.update-trigger', 'mesh.remove-trigger',
    'mesh.list-triggers', 'mesh.list-pending', 'mesh.approve', 'mesh.reject',
    'mesh.reject-all', 'mesh.escalate', 'mesh.acknowledge-escalation',
    'mesh.share_propose', 'mesh.library_request_share', 'mesh.transfer_status',
    'mesh.share_list_pending', 'mesh.task.propose', 'mesh.task.await_result',
    'mesh.capability_provider.start', 'mesh.agent_card.request',
    'mesh.list_agent_network_workers', 'mesh.mcp.list_tools', 'mesh.mcp.call_tool',
    'mesh.library_list', 'mesh.library_read', 'mesh.library_discover',
    'mesh.chat_rag_search', 'mesh.knowledge.query', 'mesh.session-summary',
    'mesh.list-sessions', 'mesh.set-digest-schedule', 'mesh.get-digest-config',
    'mesh.set-contact-mode', 'mesh.chat_rag_search', 'getMorningReport',
    'createNote', 'deleteNote', 'npm install', 'npm run typecheck', 'npm test',
    'npm run node:dev', 'npm run cli', 'npm run setup', './scripts/setup.sh',
    '.\\scripts\\setup.ps1', '--profile', '--relay-server', '--listen', '--bootstrap',
    '--relay', '--include-p2p-trace', '--vault', '--query', '--approvals',
    '/ip4/0.0.0.0/tcp/4001', '/ip4/127.0.0.1/tcp/18789', '/ip4/127.0.0.1/tcp/3031',
    '/ip4/127.0.0.1/tcp/11434/v1', '/ip4/127.0.0.1/tcp/4000/v1',
    '/ip4/127.0.0.1/tcp/8010/message', '/ip4/127.0.0.1/tcp/8020/message',
    '18789', '3031', '11434', '4000', '4001', '8010', '8020',
    '12D3KooWLNR4WYWHBswe8ux5zWsy6cuGywnYPJbdbaAbbpmJMjbo',
}

TERM_MAP = {
    'install': '安装',
    'installed': '已安装',
    'installation': '安装',
    'setup': '设置',
    'set up': '设置',
    'configured': '配置',
    'configuration': '配置',
    'configure': '配置',
    'config': '配置',
    'configured': '已配置',
    'configuring': '配置',
    'settings': '设置',
    'setting': '设置',
    'preferences': '偏好设置',
    'preference': '偏好设置',
    'option': '选项',
    'options': '选项',
    'feature': '功能',
    'features': '功能',
    'capability': '能力',
    'capabilities': '能力',
    'enabled': '已启用',
    'enable': '启用',
    'disabling': '禁用',
    'disabled': '已禁用',
    'disable': '禁用',
    'available': '可用',
    'available': '可用',
    'availability': '可用性',
    'limitation': '限制',
    'limitations': '限制',
    'require': '需要',
    'requires': '需要',
    'required': '必需的',
    'recommend': '推荐',
    'recommended': '推荐的',
    'suggest': '建议',
    'suggested': '建议的',
    'choose': '选择',
    'choosing': '选择',
    'choice': '选择',
    'select': '选择',
    'selected': '已选择',
    'selection': '选择',
    'use': '使用',
    'using': '使用',
    'used': '使用',
    'usage': '使用',
    'run': '运行',
    'running': '运行',
    'runs': '运行',
    'started': '已启动',
    'start': '启动',
    'starting': '启动',
    'stop': '停止',
    'stopped': '已停止',
    'stopping': '停止',
    'restart': '重新启动',
    'restarted': '已重新启动',
    'restarting': '重新启动',
    'open': '打开',
    'opens': '打开',
    'opened': '已打开',
    'open': '打开',
    'close': '关闭',
    'closed': '已关闭',
    'closing': '关闭',
    'view': '查看',
    'views': '查看',
    'viewing': '查看',
    'review': '审阅',
    'reviewing': '审阅',
    'reviewed': '已审阅',
    'check': '检查',
    'checking': '检查',
    'checked': '已检查',
    'verify': '验证',
    'verifying': '验证',
    'verified': '已验证',
    'confirm': '确认',
    'confirming': '确认',
    'confirmed': '已确认',
    'test': '测试',
    'testing': '测试',
    'tested': '已测试',
    'test': '测试',
    'debug': '调试',
    'debugging': '调试',
    'debugged': '已调试',
    'troubleshoot': '故障排除',
    'troubleshooting': '故障排除',
    'troubleshooting': '故障排除',
    'diagnose': '诊断',
    'diagnosing': '诊断',
    'diagnosed': '已诊断',
    'diagnosis': '诊断',
    'report': '报告',
    'reports': '报告',
    'reporting': '报告',
    'reported': '已报告',
    'reporting': '报告',
    'log': '日志',
    'logs': '日志',
    'logging': '日志',
    'logged': '已记录',
    'log': '日志',
    'audit': '审计',
    'audits': '审计',
    'auditing': '审计',
    'audited': '已审计',
    'audit': '审计',
    'history': '历史',
    'histories': '历史',
    'historical': '历史的',
    'backup': '备份',
    'backups': '备份',
    'backing up': '备份',
    'backed up': '已备份',
    'restore': '恢复',
    'restores': '恢复',
    'restoring': '恢复',
    'restored': '已恢复',
    'recovery': '恢复',
    'recover': '恢复',
    'recovering': '恢复',
    'recovered': '已恢复',
    'migrate': '迁移',
    'migrating': '迁移',
    'migrated': '已迁移',
    'migration': '迁移',
    'upgrade': '升级',
    'upgrading': '升级',
    'upgraded': '已升级',
    'upgrades': '升级',
    'update': '更新',
    'updating': '更新',
    'updated': '已更新',
    'updates': '更新',
    'version': '版本',
    'versions': '版本',
    'release': '发布',
    'releases': '发布',
    'released': '已发布',
    'releasing': '发布',
    'build': '构建',
    'builds': '构建',
    'building': '构建',
    'built': '已构建',
    'deploy': '部署',
    'deploying': '部署',
    'deployed': '已部署',
    'deployment': '部署',
    'deploys': '部署',
    'download': '下载',
    'downloading': '下载',
    'downloaded': '已下载',
    'downloads': '下载',
    'import': '导入',
    'importing': '导入',
    'imported': '已导入',
    'imports': '导入',
    'export': '导出',
    'exporting': '导出',
    'exported': '已导出',
    'exports': '导出',
    'delete': '删除',
    'deleting': '删除',
    'deleted': '已删除',
    'deletion': '删除',
    'deletes': '删除',
    'remove': '移除',
    'removing': '移除',
    'removed': '已移除',
    'removal': '移除',
    'removes': '移除',
    'create': '创建',
    'creating': '创建',
    'created': '已创建',
    'creates': '创建',
    'creation': '创建',
    'add': '添加',
    'adding': '添加',
    'added': '已添加',
    'adds': '添加',
    'addition': '添加',
    'edit': '编辑',
    'editing': '编辑',
    'edited': '已编辑',
    'edits': '编辑',
    'modification': '修改',
    'modify': '修改',
    'modifying': '修改',
    'modified': '已修改',
    'save': '保存',
    'saving': '保存',
    'saved': '已保存',
    'saves': '保存',
    'saving': '保存',
    'write': '写入',
    'writing': '写入',
    'written': '已写入',
    'writes': '写入',
    'read': '读取',
    'reading': '读取',
    'read': '读取',
    'reads': '读取',
    'reading': '读取',
    'search': '搜索',
    'searching': '搜索',
    'searched': '已搜索',
    'searches': '搜索',
    'searching': '搜索',
    'find': '查找',
    'finding': '查找',
    'found': '已找到',
    'finds': '查找',
    'discover': '发现',
    'discovering': '发现',
    'discovered': '已发现',
    'discovers': '发现',
    'discovery': '发现',
    'discoveries': '发现',
    'discoverable': '可发现的',
    'discoverability': '可发现性',
    'browse': '浏览',
    'browsing': '浏览',
    'browsed': '已浏览',
    'browses': '浏览',
    'browsing': '浏览',
    'publish': '发布',
    'publishing': '发布',
    'published': '已发布',
    'publishes': '发布',
    'publishing': '发布',
    'unpublish': '取消发布',
    'unpublishing': '取消发布',
    'unpublished': '已取消发布',
    'share': '分享',
    'sharing': '分享',
    'shared': '已分享',
    'shares': '分享',
    'sharing': '分享',
    'send': '发送',
    'sending': '发送',
    'sent': '已发送',
    'sends': '发送',
    'sending': '发送',
    'receive': '接收',
    'receiving': '接收',
    'received': '已接收',
    'receives': '接收',
    'receiving': '接收',
    'accept': '接受',
    'accepting': '接受',
    'accepted': '已接受',
    'accepts': '接受',
    'accepting': '接受',
    'reject': '拒绝',
    'rejecting': '拒绝',
    'rejected': '已拒绝',
    'rejects': '拒绝',
    'rejecting': '拒绝',
    'approve': '批准',
    'approving': '批准',
    'approved': '已批准',
    'approves': '批准',
    'approving': '批准',
    'approval': '批准',
    'approvals': '批准',
    'approved': '已批准',
    'approving': '批准',
    'deny': '拒绝',
    'denying': '拒绝',
    'denied': '已拒绝',
    'denies': '拒绝',
    'denying': '拒绝',
    'deny': '拒绝',
    'allow': '允许',
    'allowing': '允许',
    'allowed': '已允许',
    'allows': '允许',
    'allowing': '允许',
    'request': '请求',
    'requests': '请求',
    'requesting': '请求',
    'requested': '已请求',
    'requesting': '请求',
    'request': '请求',
    'invite': '邀请',
    'inviting': '邀请',
    'invited': '已邀请',
    'invites': '邀请',
    'inviting': '邀请',
    'invitation': '邀请',
    'invitations': '邀请',
    'invite': '邀请',
    'invited': '已邀请',
    'introduce': '介绍',
    'introducing': '介绍',
    'introduced': '已介绍',
    'introduces': '介绍',
    'introduction': '介绍',
    'introductions': '介绍',
    'introduce': '介绍',
    'introduced': '已介绍',
    'refer': '推荐',
    'referring': '推荐',
    'referred': '已推荐',
    'refers': '推荐',
    'referring': '推荐',
    'reference': '引用',
    'references': '引用',
    'referenced': '已引用',
    'referencing': '引用',
    'reference': '引用',
    'connect': '连接',
    'connecting': '连接',
    'connected': '已连接',
    'connects': '连接',
    'connection': '连接',
    'connections': '连接',
    'connectivity': '连接性',
    'reachable': '可到达的',
    'reachability': '可达性',
    'access': '访问',
    'accessing': '访问',
    'accessed': '已访问',
    'accesses': '访问',
    'access': '访问',
    'accessibility': '可访问性',
    'permission': '权限',
    'permissions': '权限',
    'authorized': '已授权',
    'authorization': '授权',
    'authorize': '授权',
    'authorizing': '授权',
    'authorized': '已授权',
    'authorizes': '授权',
    'authorizing': '授权',
    'authentication': '认证',
    'authenticate': '认证',
    'authenticating': '认证',
    'authenticated': '已认证',
    'authenticates': '认证',
    'authenticating': '认证',
    'sign': '签名',
    'signing': '签名',
    'signed': '已签名',
    'signs': '签名',
    'signing': '签名',
    'signature': '签名',
    'signatures': '签名',
    'verification': '验证',
    'verify': '验证',
    'verifying': '验证',
    'verified': '已验证',
    'verifies': '验证',
    'verifying': '验证',
    'encrypt': '加密',
    'encrypting': '加密',
    'encrypted': '已加密',
    'encrypts': '加密',
    'encryption': '加密',
    'decrypt': '解密',
    'decrypting': '解密',
    'decrypted': '已解密',
    'decrypts': '解密',
    'decryption': '解密',
    'encrypt': '加密',
    'encrypted': '已加密',
    'security': '安全',
    'secure': '安全',
    'securing': '安全',
    'secured': '已安全',
    'secures': '安全',
    'security': '安全',
    'privacy': '隐私',
    'private': '私有',
    'privately': '私有地',
    'privacy': '隐私',
    'confidential': '机密',
    'confidentially': '机密地',
    'confidentiality': '机密性',
    'protection': '保护',
    'protects': '保护',
    'protected': '已保护',
    'protecting': '保护',
    'protection': '保护',
    'threat': '威胁',
    'threats': '威胁',
    'threatened': '受威胁',
    'threatening': '威胁',
    'threat': '威胁',
    'attack': '攻击',
    'attacks': '攻击',
    'attacked': '已攻击',
    'attacking': '攻击',
    'attack': '攻击',
    'vulnerability': '漏洞',
    'vulnerabilities': '漏洞',
    'vulnerable': '脆弱的',
    'exposed': '暴露的',
    'exposure': '暴露',
    'expose': '暴露',
    'exposing': '暴露',
    'exposed': '已暴露',
    'exposes': '暴露',
    'exposing': '暴露',
    'risk': '风险',
    'risks': '风险',
    'risky': '有风险的',
    'risk': '风险',
    'danger': '危险',
    'dangerous': '危险的',
    'unsafe': '不安全的',
    'safe': '安全的',
    'safety': '安全',
    'safe': '安全',
    'trust': '信任',
    'trusted': '可信的',
    'trusting': '信任',
    'trusts': '信任',
    'trust': '信任',
    'trustworthiness': '可信度',
    'trustworthy': '可信的',
    'distrust': '不信任',
    'distrusting': '不信任',
    'distrusted': '不可信的',
    'distrusts': '不信任',
    'distrust': '不信任',
    'block': '阻止',
    'blocking': '阻止',
    'blocked': '已阻止',
    'blocks': '阻止',
    'blocking': '阻止',
    'block': '阻止',
    'blocked': '已阻止',
    'mute': '静音',
    'muting': '静音',
    'muted': '已静音',
    'mutes': '静音',
    'muting': '静音',
    'mute': '静音',
    'muted': '已静音',
    'restore': '恢复',
    'restoring': '恢复',
    'restored': '已恢复',
    'restores': '恢复',
    'restoring': '恢复',
    'recovery': '恢复',
    'recover': '恢复',
    'recovering': '恢复',
    'recovered': '已恢复',
    'recovery': '恢复',
    'revoke': '撤销',
    'revoking': '撤销',
    'revoked': '已撤销',
    'revokes': '撤销',
    'revoking': '撤销',
    'revocation': '撤销',
    'revoke': '撤销',
    'revoked': '已撤销',
    'grant': '授予',
    'granting': '授予',
    'granted': '已授予',
    'grants': '授予',
    'granting': '授予',
    'grant': '授予',
    'granted': '已授予',
    'revoke': '撤销',
    'revoking': '撤销',
    'revoked': '已撤销',
    'revokes': '撤销',
    'revoking': '撤销',
    'revocation': '撤销',
    'revoke': '撤销',
    'revoked': '已撤销',
    'upgrade': '升级',
    'upgrading': '升级',
    'upgraded': '已升级',
    'upgrades': '升级',
    'upgrading': '升级',
    'upgrade': '升级',
    'upgraded': '已升级',
    'downgrade': '降级',
    'downgrading': '降级',
    'downgraded': '已降级',
    'downgrades': '降级',
    'downgrading': '降级',
    'downgrade': '降级',
    'downgraded': '已降级',
    'pair': '配对',
    'pairing': '配对',
    'paired': '已配对',
    'pairs': '配对',
    'pairing': '配对',
    'pair': '配对',
    'paired': '已配对',
    'pairing code': '配对码',
    'QR code': '二维码',
    'pairing queue': '配对队列',
    'pairing token': '配对令牌',
    'bond': '绑定',
    'bonding': '绑定',
    'bonded': '已绑定',
    'bonds': '绑定',
    'bonding': '绑定',
    'bond': '绑定',
    'bonded': '已绑定',
    'bond request': '绑定请求',
    'bond tier': '绑定等级',
    'bond policy': '绑定策略',
    'bond engine': '绑定引擎',
    'trust tier': '信任等级',
    'trust boundary': '信任边界',
    'trust level': '信任级别',
    'trust relationship': '信任关系',
    'trust store': '信任存储',
    'public': '公开',
    'public': '公开',
    'publicly': '公开地',
    'public': '公开',
    'friends': '朋友',
    'friend': '朋友',
    'friendly': '友好的',
    'friendship': '友谊',
    'trusted': '受信任',
    'trusted': '受信任',
    'trustworthy': '可信的',
    'trusted': '受信任',
    'private': '私有',
    'private': '私有',
    'privately': '私有地',
    'private': '私有',
    'blocked': '已阻止',
    'blocked': '已阻止',
    'blocking': '阻止',
    'blocked': '已阻止',
    'direct': '直接',
    'directly': '直接地',
    'direct': '直接',
    'referred': '推荐',
    'referred': '推荐',
    'referring': '推荐',
    'referred': '推荐',
    'stranger': '陌生人',
    'strangers': '陌生人',
    'strange': '陌生的',
    'stranger': '陌生人',
    'identity': '身份',
    'identities': '身份',
    'identify': '识别',
    'identifying': '识别',
    'identified': '已识别',
    'identifies': '识别',
    'identifying': '识别',
    'identity': '身份',
    'identified': '已识别',
    'owner': '所有者',
    'owners': '所有者',
    'owned': '拥有的',
    'owning': '拥有',
    'owner': '所有者',
    'ownership': '所有权',
    'device': '设备',
    'devices': '设备',
    'device': '设备',
    'agent': '智能体',
    'agents': '智能体',
    'agency': '智能体',
    'agent': '智能体',
    'peer': '对等节点',
    'peers': '对等节点',
    'peering': '对等',
    'peer': '对等节点',
    'peer-to-peer': '点对点',
    'peer-to-peer': '点对点',
    'peer-to-peer': '点对点',
    'network': '网络',
    'networks': '网络',
    'networking': '网络',
    'networked': '已联网',
    'network': '网络',
    'mesh': '网格',
    'mesh': '网格',
    'meshed': '网格化',
    'meshing': '网格化',
    'mesh': '网格',
    'mesh network': '网格网络',
    'mesh network': '网格网络',
    'mesh network': '网格网络',
    'mesh network': '网格网络',
    'relay': '中继',
    'relays': '中继',
    'relaying': '中继',
    'relayed': '已中继',
    'relay': '中继',
    'relay': '中继',
    'relayed': '已中继',
    'relay server': '中继服务器',
    'relay node': '中继节点',
    'relay address': '中继地址',
    'relay status': '中继状态',
    'relay check-in': '中继签到',
    'relay lookup': '中继查找',
    'circuit relay': '电路中继',
    'circuit relay v2': '电路中继 v2',
    'circuit relay reservation': '电路中继预留',
    'bootstrap': '引导',
    'bootstrapping': '引导',
    'bootstrapped': '已引导',
    'bootstraps': '引导',
    'bootstrapping': '引导',
    'bootstrap': '引导',
    'bootstrapped': '已引导',
    'bootstrap relay': '引导中继',
    'community relay': '社区中继',
    'private relay': '私有中继',
    'rendezvous': '会合',
    'rendezvous': '会合',
    'rendezvous': '会合',
    'rendezvous': '会合',
    'forwarding': '转发',
    'forward': '转发',
    'forwarded': '已转发',
    'forwards': '转发',
    'forwarding': '转发',
    'forwarding': '转发',
    'transport': '传输',
    'transports': '传输',
    'transporting': '传输',
    'transported': '已传输',
    'transport': '传输',
    'transport': '传输',
    'transported': '已传输',
    'protocol': '协议',
    'protocols': '协议',
    'protocol': '协议',
    'protocol': '协议',
    'envelope': '信封',
    'envelopes': '信封',
    'envelope': '信封',
    'envelope': '信封',
    'payload': '负载',
    'payloads': '负载',
    'payload': '负载',
    'payload': '负载',
    'intent': '意图',
    'intents': '意图',
    'intent': '意图',
    'intent': '意图',
    'chat.message': '聊天消息',
    'knowledge.query': '知识查询',
    'library.read': '库读取',
    'relay.checkin': '中继签到',
    'relay.lookup': '中继查找',
    'task.propose': '任务提议',
    'task.accept': '任务接受',
    'task.reject': '任务拒绝',
    'task.result': '任务结果',
    'task.mandate': '任务授权',
    'task.negotiate': '任务协商',
    'task.cancel': '任务取消',
    'task.heartbeat': '任务心跳',
    'discovery.request': '发现请求',
    'discovery.response': '发现响应',
    'introduction.request': '介绍请求',
    'introduction.response': '介绍响应',
    'bond.request': '绑定请求',
    'bond.accept': '绑定接受',
    'bond.reject': '绑定拒绝',
    'bond.upgrade': '绑定升级',
    'bond.downgrade': '绑定降级',
    'bond.revoke': '绑定撤销',
    'profile.update': '资料更新',
    'profile.fetch': '资料获取',
    'file.share': '文件分享',
    'file.transfer': '文件传输',
    'file.receive': '文件接收',
    'file.accept': '文件接受',
    'file.reject': '文件拒绝',
    'audio.send': '音频发送',
    'audio.receive': '音频接收',
    'voice.call': '语音通话',
    'voice.accept': '语音接受',
    'voice.reject': '语音拒绝',
    'video.call': '视频通话',
    'approval.request': '批准请求',
    'approval.accept': '批准接受',
    'approval.reject': '批准拒绝',
    'audit.event': '审计事件',
    'trigger.fired': '触发器触发',
    'digest.generated': '摘要生成',
    'session.created': '会话创建',
    'session.updated': '会话更新',
    'session.deleted': '会话删除',
    'agent.message': '智能体消息',
    'agent.tool_call': '智能体工具调用',
    'agent.result': '智能体结果',
    'agent.error': '智能体错误',
    'agent.start': '智能体启动',
    'agent.stop': '智能体停止',
    'agent.pause': '智能体暂停',
    'agent.resume': '智能体恢复',
    'mesh.connected': '网格连接',
    'mesh.disconnected': '网格断开',
    'mesh.reconnected': '网格重新连接',
    'mesh.peer_discovered': '网格对等节点发现',
    'mesh.peer_connected': '网格对等节点连接',
    'mesh.peer_disconnected': '网格对等节点断开',
    'mesh.bond_established': '网格绑定建立',
    'mesh.bond_removed': '网格绑定移除',
    'mesh.bond_updated': '网格绑定更新',
    'mesh.message_sent': '网格消息发送',
    'mesh.message_received': '网格消息接收',
    'mesh.file_shared': '网格文件分享',
    'mesh.file_received': '网格文件接收',
    'mesh.audio_sent': '网格音频发送',
    'mesh.audio_received': '网格音频接收',
    'mesh.voice_call_started': '网格语音通话开始',
    'mesh.voice_call_ended': '网格语音通话结束',
    'mesh.video_call_started': '网格视频通话开始',
    'mesh.video_call_ended': '网格视频通话结束',
    'mesh.knowledge_query': '网格知识查询',
    'mesh.knowledge_response': '网格知识响应',
    'mesh.library_read': '网格库读取',
    'mesh.library_response': '网格库响应',
    'mesh.task_proposed': '网格任务提议',
    'mesh.task_accepted': '网格任务接受',
    'mesh.task_rejected': '网格任务拒绝',
    'mesh.task_result': '网格任务结果',
    'mesh.task_cancelled': '网格任务取消',
    'mesh.agent_message': '网格智能体消息',
    'mesh.agent_tool_call': '网格智能体工具调用',
    'mesh.agent_result': '网格智能体结果',
    'mesh.agent_error': '网格智能体错误',
    'mesh.approval_requested': '网格批准请求',
    'mesh.approval_accepted': '网格批准接受',
    'mesh.approval_rejected': '网格批准拒绝',
    'mesh.audit_event': '网格审计事件',
    'mesh.trigger_fired': '网格触发器触发',
    'mesh.digest_generated': '网格摘要生成',
    'mesh.session_created': '网格会话创建',
    'mesh.session_updated': '网格会话更新',
    'mesh.session_deleted': '网格会话删除',
    'mesh.connection_status': '网格连接状态',
    'mesh.relay_status': '网格中继状态',
    'mesh.discovery_status': '网格发现状态',
    'mesh.identity_status': '网格身份状态',
    'mesh.vault_status': '网格保险库状态',
    'mesh.library_status': '网格库状态',
    'mesh.agent_status': '网格智能体状态',
    'mesh.team_job_status': '网格团队任务状态',
    'mesh.mcp_status': '网格 MCP 状态',
    'mesh.a2a_status': '网格 A2A 状态',
    'mesh.browser_status': '网格浏览器状态',
    'mesh.terminal_status': '网格终端状态',
    'mesh.approvals_status': '网格批准状态',
    'mesh.activity_status': '网格活动状态',
    'mesh.profile_status': '网格资料状态',
    'mesh.settings_status': '网格设置状态',
    'mesh.notifications_status': '网格通知状态',
    'mesh.privacy_status': '网格隐私状态',
    'mesh.node_status': '网格节点状态',
    'mesh.pairing_status': '网格配对状态',
    'mesh.home_status': '网格家庭状态',
    'mesh.social_status': '网格社交状态',
    'mesh.home_remote_status': '网格家庭远程状态',
    'mesh.envoygo_status': '网格 EnvoyGo 状态',
    'mesh.envoyai_status': '网格 EnvoyAI 状态',
    'mesh.openclaw_status': '网格 OpenClaw 状态',
    'mesh.homeclaw_status': '网格 HomeClaw 状态',
    'mesh.hermes_status': '网格 Hermes 状态',
    'mesh.openhuman_status': '网格 OpenHuman 状态',
    'mesh.obsidian_status': '网格 Obsidian 状态',
    'mesh.memex_status': '网格 Memex 状态',
    'mesh.ollama_status': '网格 Ollama 状态',
    'mesh.litellm_status': '网格 LiteLLM 状态',
    'mesh.openai_status': '网格 OpenAI 状态',
    'mesh.anthropic_status': '网格 Anthropic 状态',
    'mesh.claude_status': '网格 Claude 状态',
    'mesh.tauri_status': '网格 Tauri 状态',
    'mesh.flutter_status': '网格 Flutter 状态',
    'mesh.react_status': '网格 React 状态',
    'mesh.nodejs_status': '网格 Node.js 状态',
    'mesh.typescript_status': '网格 TypeScript 状态',
    'mesh.zod_status': '网格 Zod 状态',
    'mesh.sqlite_status': '网格 SQLite 状态',
    'mesh.helia_status': '网格 Helia 状态',
    'mesh.kubo_status': '网格 Kubo 状态',
    'mesh.ipfs_status': '网格 IPFS 状态',
    'mesh.webrtc_status': '网格 WebRTC 状态',
    'mesh.turn_status': '网格 TURN 状态',
    'mesh.stun_status': '网格 STUN 状态',
    'mesh.websocket_status': '网格 WebSocket 状态',
    'mesh.http_status': '网格 HTTP 状态',
    'mesh.tcp_status': '网格 TCP 状态',
    'mesh.quic_status': '网格 QUIC 状态',
    'mesh.mdns_status': '网格 mDNS 状态',
    'mesh.dht_status': '网格 DHT 状态',
    'mesh.nat_status': '网格 NAT 状态',
    'mesh.lan_status': '网格 LAN 状态',
    'mesh.wan_status': '网格 WAN 状态',
    'mesh.firewall_status': '网格防火墙状态',
    'mesh.proxy_status': '网格代理状态',
    'mesh.vpn_status': '网格 VPN 状态',
    'mesh.tunnel_status': '网格隧道状态',
    'mesh.gateway_status': '网格网关状态',
    'mesh.orchestration_status': '网格编排状态',
    'mesh.runtime_status': '网格运行时状态',
    'mesh.process_status': '网格进程状态',
    'mesh.thread_status': '网格线程状态',
    'mesh.service_status': '网格服务状态',
    'mesh.daemon_status': '网格守护进程状态',
    'mesh.watchdog_status': '网格看门狗状态',
    'mesh.kill_switch_status': '网格终止开关状态',
    'mesh.model_status': '网格模型状态',
    'mesh.router_status': '网格路由状态',
    'mesh.provider_status': '网格提供商状态',
    'mesh.endpoint_status': '网格端点状态',
    'mesh.api_key_status': '网格 API 密钥状态',
    'mesh.model_name_status': '网格模型名称状态',
    'mesh.prompt_status': '网格提示状态',
    'mesh.context_status': '网格上下文状态',
    'mesh.memory_status': '网格内存状态',
    'mesh.session_status': '网格会话状态',
    'mesh.workspace_status': '网格工作空间状态',
    'mesh.plugin_status': '网格插件状态',
    'mesh.extension_status': '网格扩展状态',
    'mesh.integration_status': '网格集成状态',
    'mesh.bridge_status': '网格桥状态',
    'mesh.proxy_status': '网格代理状态',
    'mesh.adapter_status': '网格适配器状态',
    'mesh.mirror_status': '网格镜像状态',
    'mesh.thin_client_status': '网格瘦客户端状态',
    'mesh.client_status': '网格客户端状态',
    'mesh.server_status': '网格服务器状态',
    'mesh.node_status': '网格节点状态',
    'mesh.home_node_status': '网格家庭节点状态',
    'mesh.relay_node_status': '网格中继节点状态',
    'mesh.full_node_status': '网格全节点状态',
    'mesh.capacitor_status': '网格 Capacitor 状态',
    'mesh.desktop_status': '网格桌面状态',
    'mesh.mobile_status': '网格移动状态',
    'mesh.ios_status': '网格 iOS 状态',
    'mesh.android_status': '网格 Android 状态',
    'mesh.macos_status': '网格 macOS 状态',
    'mesh.windows_status': '网格 Windows 状态',
    'mesh.linux_status': '网格 Linux 状态',
    'mesh.appimage_status': '网格 AppImage 状态',
    'mesh.dmg_status': '网格 DMG 状态',
    'mesh.exe_status': '网格 .exe 状态',
    'mesh.distribution_status': '网格分发状态',
    'mesh.channel_status': '网格渠道状态',
    'mesh.notarization_status': '网格公证状态',
    'mesh.gatekeeper_status': '网格 Gatekeeper 状态',
    'mesh.firewall_status': '网格防火墙状态',
    'mesh.permission_status': '网格权限状态',
    'mesh.notification_status': '网格通知状态',
    'mesh.push_status': '网格推送状态',
    'mesh.background_status': '网格后台状态',
    'mesh.battery_status': '网格电池状态',
    'mesh.optimization_status': '网格优化状态',
    'mesh.signing_status': '网格签名状态',
    'mesh.verification_status': '网格验证状态',
    'mesh.attribution_status': '网格归因状态',
    'mesh.approval_status': '网格批准状态',
    'mesh.escalation_status': '网格升级状态',
    'mesh.mandate_status': '网格授权状态',
    'mesh.budget_status': '网格预算状态',
    'mesh.cost_status': '网格成本状态',
    'mesh.max_cost_status': '网格最大成本状态',
    'mesh.bid_status': '网格出价状态',
    'mesh.award_status': '网格奖励状态',
    'mesh.chain_status': '网格链状态',
    'mesh.team_job_status': '网格团队任务状态',
    'mesh.digest_status': '网格摘要状态',
    'mesh.schedule_status': '网格调度状态',
    'mesh.cron_status': '网格定时状态',
    'mesh.interval_status': '网格间隔状态',
    'mesh.one_shot_status': '网格一次性状态',
    'mesh.daily_status': '网格每日状态',
    'mesh.weekly_status': '网格每周状态',
    'mesh.follow_up_status': '网格跟进状态',
    'mesh.check_in_status': '网格签到状态',
    'mesh.proactive_status': '网格主动状态',
    'mesh.autonomous_status': '网格自主状态',
    'mesh.auto_reply_status': '网格自动回复状态',
    'mesh.draft_status': '网格草稿状态',
    'mesh.assistant_status': '网格助手状态',
    'mesh.gatekeeper_status': '网格守门状态',
    'mesh.escalate_status': '网格升级状态',
    'mesh.acknowledge_status': '网格确认状态',
    'mesh.pending_status': '网格待处理状态',
    'mesh.expired_status': '网格过期状态',
    'mesh.chain_award_status': '网格链奖励状态',
}

SENTENCE_TRANSLATIONS = {
    '**Version:**': '**版本：**',
    '**Edition:**': '**版本类型：**',
    '**Revised:**': '**修订日期：**',
    '**Languages:**': '**语言：**',
    '**Audience:**': '**受众：**',
    '**Purpose:**': '**目的：**',
    '[English](EnvoyMesh_GuideBook_0.1.0.md)': '[English](EnvoyMesh_GuideBook_0.1.0.md)',
    '[简体中文](EnvoyMesh_GuideBook_0.1.0.zh-CN.md)': '[简体中文](EnvoyMesh_GuideBook_0.1.0.zh-CN.md)',
    '([HTML](EnvoyMesh_GuideBook_0.1.0.html) · [中文 HTML](EnvoyMesh_GuideBook_0.1.0.zh-CN.html))': '([HTML](EnvoyMesh_GuideBook_0.1.0.html) · [中文 HTML](EnvoyMesh_GuideBook_0.1.0.zh-CN.html))',
    'End users and prospective users (Parts I–XIV); website editors, support teams, and operators (Part XV and Operator-marked topics)': '最终用户和潜在用户（第一部分至第十四部分）；网站编辑、支持团队和操作员（第十五部分和标有 Operator 的主题）',
    'A complete end-user guide to EnvoyMesh—what it is, how to install and use it on desktop and EnvoyGo, how identity and trust work, and how to operate networking, agents, relays, and advanced features safely.': 'EnvoyMesh 的完整最终用户指南 — 它是什么、如何安装并在桌面和 EnvoyGo 上使用它、身份和信任如何工作，以及如何安全地操作网络、智能体、中继和高级功能。',
    '> **Complete Guidebook Edition.**': '> **完整指南版本。**',
    'This guide reflects the EnvoyMesh 0.1.0 repository state at the revision date.': '本指南反映了修订日期时 EnvoyMesh 0.1.0 仓库的状态。',
    'It is written for end users, not as a content-outline stub.': '它是为最终用户编写的，而不是作为内容大纲存根。',
    'Feature status can differ by platform and deployment—verify each Beta or Experimental capability in your build (release notes, Settings labels, and Appendix J) before relying on it in production.': '功能状态可能因平台和部署而异 - 在生产环境中依赖它之前，请验证您的构建中的每个 Beta 或 Experimental 功能（发布说明、设置标签和附录 J）。',
    '## How to read this guide': '## 如何阅读本指南',
    '- **Parts I–XIV** explain the product for end users and operators.': '- **第一部分至第十四部分** 向最终用户和操作员解释产品。',
    '- **Part XV** is for website editors and content operators and is optional for end users.': '- **第十五部分** 适用于网站编辑和内容操作员，对于最终用户来说是可选的。',
    'Task lifecycle names such as *Created* / *Task planned* / *Running* are EnvoyMesh states, not product **Planned** / **Available** status labels.': '任务生命周期名称（例如*已创建* / *任务计划* / *运行中*）是 EnvoyMesh 状态，而不是产品 **Planned** / **Available** 状态标签。',
    '**Mobile** in this guide means **EnvoyGo** (thin client paired to a home node), unless a section explicitly discusses legacy mobile experiments.': '本指南中的 **Mobile** 表示 **EnvoyGo**（与主节点配对的瘦客户端），除非某节明确讨论旧版移动实验。',
    '## Feature status labels': '## 功能状态标签',
    '- **Available** — implemented and intended for current use.': '- **Available** — 已实施并供当前使用。',
    '- **Beta** — implemented, but still receiving validation or product polish.': '- **Beta** — 已实施，但仍在接受验证或产品完善。',
    '- **Experimental** — usable for evaluation; behavior or interfaces may change.': '- **Experimental** — 可用于评估；行为或界面可能会改变。',
    '- **Compatibility preset** — EnvoyMesh includes configuration for the integration, while part of the integration is maintained by another project.': '- **Compatibility preset** — EnvoyMesh 包含集成配置，而部分集成由另一个项目维护。',
    '- **Planned** — designed or documented, but not currently available as a complete product feature.': '- **Planned** — 已设计或记录，但目前不作为完整的产品功能提供。',
    '- **Parked** — intentionally deferred without a committed release date.': '- **Parked** — 有意推迟，没有承诺的发布日期。',
    '- **Desktop** — available through the EnvoyMesh desktop application or home node.': '- **Desktop** — 通过 EnvoyMesh 桌面应用程序或主节点可用。',
    '- **Mobile** — available in EnvoyGo, the current EnvoyMesh mobile product (home-paired thin client).': '- **Mobile** — 适用于 EnvoyGo，当前的 EnvoyMesh 移动产品（与主节点配对的瘦客户端）。',
    '- **Operator** — intended for node, relay, or fleet administrators.': '- **Operator** — 用于节点、中继或集群管理员。',
    '## Product terminology used in this guide': '## 本指南使用的产品术语',
    '- **EnvoyAI / OpenClaw** is the richer bundled agent integration included with EnvoyMesh.': '- **EnvoyAI / OpenClaw** 是 EnvoyMesh 中包含的更丰富的捆绑智能体集成。',
    '- **HomeClaw** and **Hermes** are built-in external-agent compatibility presets.': '- **HomeClaw** 和 **Hermes** 是内置的外部智能体兼容性预设。',
    '- **OpenHuman** is a built-in compatibility preset that is disabled by default.': '- **OpenHuman** 是一个内置兼容性预设，默认情况下处于禁用状态。',
    'Agent-side code for HomeClaw, Hermes, and OpenHuman is maintained by their respective projects; EnvoyMesh provides the bridge, presets, policy boundary, and mesh tools.': 'HomeClaw、Hermes 和 OpenHuman 的智能体端代码由各自的项目维护；EnvoyMesh 提供桥、预设、策略边界和网格工具。',
    '- **Agent Network** means bonded people allowing their opted-in local agents to collaborate. It is not a public agent marketplace.': '- **Agent Network** 表示绑定的人员允许其选择加入的本地智能体进行协作。它不是公共智能体市场。',
    '- **Team jobs** is the user-facing name for multi-agent collaboration. Source code and older documentation may call these workflows **chains**.': '- **Team jobs** 是多智能体协作的面向用户的名称。源代码和较旧的文档可能将这些工作流称为**链**。',
    '- **EnvoyGo** is the current mobile product: a thin client that pairs to a home EnvoyMesh node.': '- **EnvoyGo** 是当前的移动产品：与主 EnvoyMesh 节点配对的瘦客户端。',
    'The earlier Capacitor mobile tree (in-process full node) is a legacy experiment and is not the primary mobile application.': '早期的 Capacitor 移动树（进程内完整节点）是一个遗留实验，不是主要的移动应用程序。',
    'Running EnvoyGo itself as a full mesh node is parked (Appendix J.6).': '将 EnvoyGo 本身作为完整网格节点运行已暂停（附录 J.6）。',
    '# Table of Contents': '# 目录',
    '## Part I — Discover EnvoyMesh': '## 第一部分 — 认识 EnvoyMesh',
    '### 1. Welcome to EnvoyMesh': '### 1. 欢迎来到 EnvoyMesh',
    '#### 1.1 A private network for people and AI agents': '#### 1.1 面向人类和 AI 智能体的私有网络',
    'EnvoyMesh connects people and AI agents through a private mesh rather than a central account service.': 'EnvoyMesh 通过私有网格而不是中央帐户服务连接人员和人工智能智能体。',
    'Each participant keeps a local identity, chooses trusted contacts (bonded at one of four user-selectable trust tiers — blocked, public, referred, or direct; `self` is the implicit tier for your own owner, devices, and agents), and decides which agents, tools, and information may cross those relationships.': '每个参与者保留本地身份，选择可信联系人（绑定在四个用户可选信任等级之一 — blocked、public、referred 或 direct；`self` 是您自己的所有者、设备和智能体的隐式等级），并决定哪些智能体、工具和信息可以跨越这些关系。',
    '#### 1.2 Local-first and peer-to-peer by design': '#### 1.2 设计上优先本地和点对点',
    'The home node stores identity, policy, conversations, tasks, and knowledge locally.': '主节点本地存储身份、策略、对话、任务和知识。',
    'Peer-to-peer transport is preferred, so routine communication does not depend on a hosted application database.': '优先使用点对点传输，因此日常通信不依赖于托管应用程序数据库。',
    '#### 1.3 No central account required': '#### 1.3 无需中央帐户',
    'You create cryptographic identities instead of registering a global username and password.': '您创建加密身份，而不是注册全局用户名和密码。',
    'Public relays may help peers find and reach each other, but they are not an account authority.': '公共中继可以帮助对等节点找到并联系彼此，但它们不是帐户权威。',
    '#### 1.4 Your identity, relationships, and data belong to you': '#### 1.4 您的身份、关系和数据属于您自己',
    'Owner keys establish control, bonds record relationships, and sensitivity labels protect data.': '所有者密钥建立控制权，绑定记录关系，敏感度标签保护数据。',
    'Backups therefore matter: losing the only copy of an owner key can mean losing continuity of that identity.': '因此备份很重要：丢失所有者密钥的唯一副本可能意味着失去该身份的连续性。',
    '#### 1.5 Direct connections and optional relays': '#### 1.5 直接连接和可选中继',
    'EnvoyMesh first attempts a direct peer path.': 'EnvoyMesh 首先尝试直接对等路径。',
    'When NAT, firewalls, or mobility prevent that path, an optional relay supplies rendezvous and forwarding without becoming the application brain.': '当 NAT、防火墙或移动性阻止该路径时，可选中继提供会合和转发，而不会成为应用程序大脑。',
    '#### 1.6 Personal agents and external agents': '#### 1.6 个人智能体和外部智能体',
    'EnvoyAI is the bundled OpenClaw-based assistant.': 'EnvoyAI 是基于 OpenClaw 的捆绑助手。',
    'A separate bridge can connect HomeClaw, Hermes, OpenHuman, or a custom HTTP agent without giving that external process raw P2P keys.': '单独的桥可以连接 HomeClaw、Hermes、OpenHuman 或自定义 HTTP 智能体，而不向外部进程提供原始 P2P 密钥。',
    '#### 1.7 Trusted multi-agent collaboration': '#### 1.7 可信多智能体协作',
    'Agent Network lets bonded owners opt their local agents into Team jobs.': 'Agent Network 允许绑定的所有者将其本地智能体选择加入 Team jobs。',
    'The requesting node plans work, eligible workers execute locally, and the orchestrator combines attributed results.': '请求节点规划工作，合格的工作者在本地执行，编排器合并带有归属的结果。',
    '#### 1.8 Open protocols and interoperability': '#### 1.8 开放协议和互操作性',
    'Native signed EnvoyMesh envelopes remain the internal protocol.': '原生签名的 EnvoyMesh 信封仍然是内部协议。',
    'MCP exposes tools to compatible applications, while A2A publishes agent discovery and task interfaces at the network edge.': 'MCP 向兼容应用程序公开工具，而 A2A 在网络边缘发布智能体发现和任务接口。',
    '#### 1.9 Major features at a glance': '#### 1.9 主要功能一览',
    'Available areas include messaging, groups, audio, voice calls, files, profiles, personal AI, knowledge and RAG, external-agent bridges, Team jobs, terminals, Browser, relays, MCP, and A2A.': '可用领域包括消息、群组、音频、语音通话、文件、资料、个人 AI、知识和 RAG、外部智能体桥、Team jobs、终端、浏览器、中继、MCP 和 A2A。',
    '#### 1.10 Current availability and limitations': '#### 1.10 当前可用性和限制',
    'Some capabilities remain platform-specific or deferred.': '某些功能仍然特定于平台或被推迟。',
    'In particular, video calls, broad anonymous worker recruitment, full-node EnvoyGo operation, global reputation, commerce, Filecoin persistence, and a complete hierarchical relay graph are not current general features.': '特别是，视频通话、广泛的匿名工作者招募、完整节点的 EnvoyGo 操作、全球声誉、商业、Filecoin 持久性和完整的分层中继图不是当前的通用功能。',
    '### 2. Why EnvoyMesh?': '### 2. 为什么选择 EnvoyMesh？',
    '#### 2.1 Private communication without a central platform': '#### 2.1 无需中央平台的私密通信',
    'EnvoyMesh treats messaging as signed peer traffic rather than rows in a hosted database.': 'EnvoyMesh 将消息传递视为已签名的对等流量，而不是托管数据库中的行。',
    'You choose who appears in your contact list, and conversations stay on devices you control unless you explicitly share outward.': '您选择谁出现在您的联系人列表中，对话保留在您控制的设备上，除非您明确向外分享。',
    'This differs from centralized messengers that can change terms, scan content, or freeze accounts without your keys.': '这与集中式信使不同，集中式信使可以在没有您的密钥的情况下更改条款、扫描内容或冻结帐户。',
    '#### 2.2 Self-sovereign identity across your devices': '#### 2.2 跨设备的自主身份',
    'Your owner identity is an Ed25519 keypair, not a username registered by a vendor.': '您的所有者身份是 Ed25519 密钥对，而不是供应商注册的用户名。',
    'Devices and agents derive from that owner with signed certificates and mandates, so you can prove continuity across laptops, desktops, and paired phones.': '设备和智能体从该所有者派生，带有签名证书和授权，因此您可以证明笔记本电脑、台式机和配对手机之间的连续性。',
    'Losing the only copy of an owner key can end that identity\'s history, so backup and recovery planning matter from day one.': '丢失所有者密钥的唯一副本可能会结束该身份的历史，因此备份和恢复计划从第一天起就很重要。',
    '#### 2.3 AI assistance under your control': '#### 2.3 由您掌控的 AI 助手',
    'EnvoyAI and external agents run on your home node under bond policy, mandate limits, and optional human approvals.': 'EnvoyAI 和外部智能体在您的主节点上运行，遵循绑定策略、授权限制和可选的人工批准。',
    'You decide which models, tools, and contacts an agent may use instead of accepting a vendor\'s default automation scope.': '您决定智能体可以使用哪些模型、工具和联系人，而不是接受供应商的默认自动化范围。',
    'Remote model providers receive only prompts the node approves after its semantic firewall and policy checks.': '远程模型提供商仅接收节点在其语义防火墙和策略检查后批准的提示。',
    '#### 2.4 Trusted knowledge sharing': '#### 2.4 可信知识共享',
    'Notes and files live in your Vault, appear in the Library UI, and can be shared with sensitivity labels that the Bonds engine enforces.': '笔记和文件存储在您的保险库中，出现在库 UI 中，并可以与绑定引擎强制执行的敏感度标签一起共享。',
    'Bonded contacts can query your public or friends-tier material through `knowledge.query`, while strangers see only the public sub-graph and are rate-limited.': '绑定的联系人可以通过 `knowledge.query` 查询您的公开或朋友级材料，而陌生人只能看到公开子图并受到速率限制。',
    'Publishing for browsing uses separate web-content paths and visibility rules described in Part V.': '发布用于浏览的内容使用第五部分中描述的单独的网络内容路径和可见性规则。',
    '#### 2.5 Safe task delegation': '#### 2.5 安全的任务委托',
    'Task delegation uses owner-signed mandates that cap cost, sensitivity, allowed actions, and expiry.': '任务委托使用所有者签名的授权，限制成本、敏感度、允许的操作和过期时间。',
    'An agent cannot silently exceed those bounds; risky steps can require explicit approval before execution.': '智能体不能默默地超出这些界限；有风险的步骤可能需要在执行前获得明确批准。',
    'This makes autonomous work legible rather than a black box running on someone else\'s servers.': '这使得自主工作变得清晰可理解，而不是在别人的服务器上运行的黑匣子。',
    '#### 2.6 Collaboration among agents you choose': '#### 2.6 您选择的智能体之间的协作',
    'Agent Network is opt-in collaboration among bonded owners, not an anonymous worker marketplace.': 'Agent Network 是绑定所有者之间的选择加入协作，而不是匿名工作者市场。',
    'Team jobs let your local agent plan work and call workers you already trust, with attributed results returned to the orchestrator.': 'Team jobs 让您的本地智能体规划工作并调用您已经信任的工作者，带有归属的结果返回给编排器。',
    'You stay in control of which contacts\' agents may participate.': '您始终控制哪些联系人的智能体可以参与。',
    '#### 2.7 Local models, remote models, and external agents': '#### 2.7 本地模型、远程模型和外部智能体',
    'EnvoyMesh supports local inference, configured remote providers, and external HTTP agents such as HomeClaw or Hermes through a single bridge at a time.': 'EnvoyMesh 支持本地推理、配置的远程提供商以及通过单个桥接器连接的外部 HTTP 智能体（如 HomeClaw 或 Hermes）。',
    'The node signs mesh