#!/usr/bin/env python3
import re
import os

TERM_MAP = {
    'EnvoyMesh': 'EnvoyMesh',
    'EnvoyGo': 'EnvoyGo',
    'EnvoyAI': 'EnvoyAI',
    'OpenClaw': 'OpenClaw',
    'HomeClaw': 'HomeClaw',
    'Hermes': 'Hermes',
    'OpenHuman': 'OpenHuman',
    'Claude': 'Claude',
    'Agent Network': '智能体网络',
    'Team jobs': '团队任务',
    'mesh': '网络',
    'libp2p': 'libp2p',
    'Ed25519': 'Ed25519',
    'DID': 'DID',
    'bond': '绑定',
    'bonds': '绑定',
    'peer': '对等节点',
    'owner': '所有者',
    'device': '设备',
    'agent': '智能体',
    'mandate': '授权',
    'vault': '保险库',
    'Vault': '保险库',
    'Library': '库',
    'RAG': 'RAG',
    'knowledge base': '知识库',
    'knowledge': '知识',
    'knowledge.query': 'knowledge.query',
    'mesh.findKnowledge': 'mesh.findKnowledge',
    'mesh.sendMessage': 'mesh.sendMessage',
    'mesh.findContact': 'mesh.findContact',
    'JSON-RPC': 'JSON-RPC',
    'WebSocket': 'WebSocket',
    'JSONL': 'JSONL',
    'correlation ID': '关联ID',
    'correlation IDs': '关联ID',
    'audit': '审计',
    'audit trail': '审计轨迹',
    'policy': '策略',
    'policy engine': '策略引擎',
    'Bond Engine': '绑定引擎',
    'trust': '信任',
    'trust tier': '信任等级',
    'trust levels': '信任等级',
    'direct': '直接',
    'referred': '推荐',
    'public': '公开',
    'blocked': '阻止',
    'stranger': '陌生人',
    'friends': '朋友',
    'sensitivity': '敏感度',
    'sensitivity label': '敏感度标签',
    'sensitivity labels': '敏感度标签',
    'sensitivity tier': '敏感度等级',
    'social': '社交',
    'Social': 'Social',
    'chat': '聊天',
    'message': '消息',
    'messages': '消息',
    'chat.message': 'chat.message',
    'profile': '资料',
    'Profile': '资料',
    'display name': '显示名称',
    'display profile': '显示资料',
    'avatar': '头像',
    'contacts': '联系人',
    'contact': '联系人',
    'groups': '群组',
    'group': '群组',
    'voice call': '语音通话',
    'audio message': '语音消息',
    'voice calls': '语音通话',
    'audio messages': '语音消息',
    'file sharing': '文件共享',
    'files': '文件',
    'share files': '共享文件',
    'terminal': '终端',
    'terminals': '终端',
    'Browser': '浏览器',
    'browser': '浏览器',
    'relay': '中继',
    'relays': '中继',
    'circuit relay': '电路中继',
    'circuit-relay-v2': 'circuit-relay-v2',
    'relay.checkin': 'relay.checkin',
    'relay.lookup': 'relay.lookup',
    'relay.join.request': 'relay.join.request',
    'MCP': 'MCP',
    'A2A': 'A2A',
    'agent card': '智能体卡片',
    'Agent Card': '智能体卡片',
    'task': '任务',
    'tasks': '任务',
    'task intent': '任务意图',
    'task lifecycle': '任务生命周期',
    'task.propose': 'task.propose',
    'task.negotiate': 'task.negotiate',
    'task.accept': 'task.accept',
    'task.reject': 'task.reject',
    'task.result': 'task.result',
    'task.mandate': 'task.mandate',
    'approval': '审批',
    'approvals': '审批',
    'human approval': '人工审批',
    'requires approval': '需要审批',
    'approval queue': '审批队列',
    'inbound guard': '入站守卫',
    'Inbound Guard': '入站守卫',
    'task runtime guard': '任务运行时守卫',
    'Task Runtime Guard': '任务运行时守卫',
    'semantic firewall': '语义防火墙',
    'Semantic Firewall': '语义防火墙',
    'Diplomat': '外交官',
    'Brain': '大脑',
    'HomeRemoteClient': 'HomeRemoteClient',
    'HomeRemote': 'HomeRemote',
    'bootstrap': '引导',
    'bootstrap relay': '引导中继',
    'community relay': '社区中继',
    'private relay': '私有中继',
    'rendezvous': '会合',
    'forwarding': '转发',
    'NAT': 'NAT',
    'firewall': '防火墙',
    'TCP': 'TCP',
    'QUIC': 'QUIC',
    'mDNS': 'mDNS',
    'DHT': 'DHT',
    'LAN': '局域网',
    'WAN': '广域网',
    'circuit': '电路',
    'reservation': '预留',
    'stream': '流',
    'streams': '流',
    'payload': '负载',
    'payloads': '负载',
    'envelope': '信封',
    'envelopes': '信封',
    'EnvoyEnvelope': 'EnvoyEnvelope',
    'signature': '签名',
    'signatures': '签名',
    'signed': '已签名',
    'canonical JSON': '规范JSON',
    'canonical payload': '规范负载',
    'signing': '签名',
    'verification': '验证',
    'verify': '验证',
    'verifiable': '可验证',
    'sensitivity.json': 'sensitivity.json',
    'node-config.json': 'node-config.json',
    'bridge-config.json': 'bridge-config.json',
    'bridge-identity.json': 'bridge-identity.json',
    'bundled-sponsor-friend.json': 'bundled-sponsor-friend.json',
    'shared_vault': 'shared_vault',
    'web/': 'web/',
    'envoy://': 'envoy://',
    '/ip4/': '/ip4/',
    '/tcp/': '/tcp/',
    '/p2p/': '/p2p/',
    '/p2p-circuit': '/p2p-circuit',
    'multiaddr': '多地址',
    'multiaddrs': '多地址',
    'listen address': '监听地址',
    'listen addresses': '监听地址',
    'advertise address': '广播地址',
    'advertise-addr': 'advertise-addr',
    'discovery': '发现',
    'discovery mode': '发现模式',
    'discovery UI': '发现界面',
    'search': '搜索',
    'federated search': '联合搜索',
    'vault-search': 'vault-search',
    'index': '索引',
    'indexing': '索引',
    'chunk': '块',
    'chunks': '块',
    'RAG pipeline': 'RAG管道',
    'syndicated knowledge': '联合知识',
    'syndicated library': '联合库',
    'publish': '发布',
    'published': '已发布',
    'browse': '浏览',
    'content': '内容',
    'web content': '网页内容',
    'visibility': '可见性',
    'visibility rules': '可见性规则',
    'mesh content': '网络内容',
    'publish Markdown': '发布Markdown',
    'Markdown': 'Markdown',
    'PDF': 'PDF',
    'images': '图像',
    'image': '图像',
    'library.read': 'library.read',
    'push notifications': '推送通知',
    'notifications': '通知',
    'settings': '设置',
    'Settings': '设置',
    'AI': 'AI',
    'AI engine': 'AI引擎',
    'model': '模型',
    'models': '模型',
    'model provider': '模型提供商',
    'model providers': '模型提供商',
    'local model': '本地模型',
    'local models': '本地模型',
    'remote model': '远程模型',
    'remote models': '远程模型',
    'remote provider': '远程提供商',
    'remote providers': '远程提供商',
    'inference': '推理',
    'prompt': '提示',
    'prompts': '提示',
    'LiteLLM': 'LiteLLM',
    'OpenAI': 'OpenAI',
    'HTTP': 'HTTP',
    'HTTP agent': 'HTTP智能体',
    'HTTP bridge': 'HTTP桥接',
    'external agent': '外部智能体',
    'external agents': '外部智能体',
    'external runtime': '外部运行时',
    'external process': '外部进程',
    'bridge': '桥接',
    'bridges': '桥接',
    'Ext Agent': '外部智能体',
    'bridge configuration': '桥接配置',
    'bridge secrets': '桥接密钥',
    'bridge credentials': '桥接凭证',
    'bridge identity': '桥接身份',
    'endpoint': '端点',
    'endpoints': '端点',
    'localhost': 'localhost',
    '127.0.0.1': '127.0.0.1',
    'port': '端口',
    'ports': '端口',
    'port 18789': '端口18789',
    'WebSocket API': 'WebSocket API',
    'API': 'API',
    'JSON': 'JSON',
    'JavaScript': 'JavaScript',
    'TypeScript': 'TypeScript',
    'npm': 'npm',
    'node': '节点',
    'nodes': '节点',
    'home node': '主节点',
    'Home Node': '主节点',
    'node service': '节点服务',
    'NodeService': 'NodeService',
    'node runtime': '节点运行时',
    'node-config': '节点配置',
    'relay server': '中继服务器',
    'relay-server': 'relay-server',
    'listen': '监听',
    '--listen': '--listen',
    '--bootstrap': '--bootstrap',
    '--relay': '--relay',
    '--profile': '--profile',
    '--include-p2p-trace': '--include-p2p-trace',
    'connectivity-status': 'connectivity-status',
    'relay-status': 'relay-status',
    'cli': 'cli',
    'CLI': 'CLI',
    'terminal attach': '终端连接',
    'PTY': 'PTY',
    'shell': 'shell',
    'shell session': 'shell会话',
    'remote shell': '远程shell',
    'SSH': 'SSH',
    'TURN': 'TURN',
    'WebRTC': 'WebRTC',
    'CallKit': 'CallKit',
    'VoIP': 'VoIP',
    'VoIP push': 'VoIP推送',
    'FCM': 'FCM',
    'APNs': 'APNs',
    'iOS': 'iOS',
    'Android': 'Android',
    'macOS': 'macOS',
    'Windows': 'Windows',
    'desktop': '桌面',
    'Desktop': '桌面',
    'mobile': '移动',
    'Mobile': '移动',
    'thin client': '瘦客户端',
    'full node': '全节点',
    'in-process': '进程内',
    'Capacitor': 'Capacitor',
    'Tauri': 'Tauri',
    'Flutter': 'Flutter',
    'React': 'React',
    'Vite': 'Vite',
    'Electron': 'Electron',
    'AppImage': 'AppImage',
    'DMG': 'DMG',
    '.exe': '.exe',
    'installer': '安装程序',
    'installation': '安装',
    'install': '安装',
    'setup': '设置',
    'setup.sh': 'setup.sh',
    'setup.ps1': 'setup.ps1',
    'build': '构建',
    'builds': '构建',
    'source': '源码',
    'source build': '源码构建',
    'release': '版本',
    'releases': '版本',
    'release notes': '版本说明',
    'CHANGELOG.md': 'CHANGELOG.md',
    'QuickStart.md': 'QuickStart.md',
    'version': '版本',
    'Version': '版本',
    'Edition': '版本类型',
    'Revised': '修订日期',
    'Languages': '语言',
    'Audience': '受众',
    'Purpose': '目的',
    'Complete Guidebook Edition': '完整指南版',
    'Available': '可用',
    'Beta': 'Beta',
    'Experimental': '实验性',
    'Compatibility preset': '兼容性预设',
    'Planned': '计划中',
    'Parked': '暂停',
    'Operator': '操作员',
    'Created': '已创建',
    'Task planned': '任务已计划',
    'Running': '运行中',
    'partial': '部分完成',
    'completed': '已完成',
    'failed': '失败',
    'cancelled': '已取消',
    'discovering': '发现中',
    'negotiating': '协商中',
    'waiting_for_peer': '等待对等节点',
    'waiting_for_owner': '等待所有者',
    'planned': '计划中',
    'Phase': '阶段',
    'Phase 42': '阶段42',
    'Phase 45': '阶段45',
    'Phase 45C': '阶段45C',
    'Phase 45E': '阶段45E',
    'Phase 42I': '阶段42I',
    'Appendix': '附录',
    'Appendix J': '附录J',
    'Appendix K': '附录K',
    'Appendix J.4': '附录J.4',
    'Appendix J.6': '附录J.6',
    'Appendix K': '附录K',
    'Part I': '第一部分',
    'Part II': '第二部分',
    'Part III': '第三部分',
    'Part IV': '第四部分',
    'Part V': '第五部分',
    'Part VI': '第六部分',
    'Part VII': '第七部分',
    'Part VIII': '第八部分',
    'Part IX': '第九部分',
    'Part X': '第十部分',
    'Part XI': '第十一部分',
    'Part XII': '第十二部分',
    'Part XIII': '第十三部分',
    'Part XIV': '第十四部分',
    'Part XV': '第十五部分',
    'Figure': '图',
    'Figure 1': '图1',
    'Figure 2': '图2',
    'Figure 12': '图12',
    'Figure 18': '图18',
    'chat list': '聊天列表',
    'thread': '线程',
    'threads': '线程',
    'thread header': '线程标题',
    'group thread': '群组线程',
    'direct thread': '直接线程',
    'conversation': '对话',
    'conversations': '对话',
    'Chat': '聊天',
    'Conversations': '对话',
    'People': '联系人',
    'Rooms': '房间',
    'New Group': '新建群组',
    'New group': '新建群组',
    'Me': '我',
    'Home': '首页',
    'Node status': '节点状态',
    'connectivity': '连接性',
    'connection status': '连接状态',
    'reachability': '可达性',
    'connected': '已连接',
    'disconnected': '已断开',
    'online': '在线',
    'offline': '离线',
    'pending': '待处理',
    'sent': '已发送',
    'delivered': '已送达',
    'read': '已读',
    'failed': '失败',
    'allow': '允许',
    'deny': '拒绝',
    'outcome': '结果',
    'allow/deny': '允许/拒绝',
    'success': '成功',
    'error': '错误',
    'timeout': '超时',
    'delivery': '送达',
    'delivery indicators': '送达指示器',
    'read receipts': '已读回执',
    'send': '发送',
    'receive': '接收',
    'accept': '接受',
    'reject': '拒绝',
    'request': '请求',
    'requests': '请求',
    'bond request': '绑定请求',
    'pairing': '配对',
    'pairing request': '配对请求',
    'pairing code': '配对码',
    'pairing payload': '配对载荷',
    'Pairing Queue': '配对队列',
    'QR code': '二维码',
    'QR': '二维码',
    'invitation link': '邀请链接',
    'proof': '证明',
    'proof text': '证明文本',
    'proof message': '证明消息',
    'out of band': '带外',
    'out-of-band': '带外',
    'introduction': '介绍',
    'introductions': '介绍',
    'introduce': '介绍',
    'Introduce': '介绍',
    'vouch': '担保',
    'mute': '静音',
    'block': '阻止',
    'remove': '移除',
    'restore': '恢复',
    'revoke': '撤销',
    'revocation': '撤销',
    'rotate': '轮换',
    'credentials': '凭证',
    'secrets': '密钥',
    'keys': '密钥',
    'key': '密钥',
    'private key': '私钥',
    'private keys': '私钥',
    'public key': '公钥',
    'public keys': '公钥',
    'public key fingerprint': '公钥指纹',
    'keypair': '密钥对',
    'Ed25519 keypair': 'Ed25519密钥对',
    'identity': '身份',
    'identities': '身份',
    'owner identity': '所有者身份',
    'device identity': '设备身份',
    'agent identity': '智能体身份',
    'peer identity': '对等身份',
    'peer ID': '对等ID',
    'Peer ID': '对等ID',
    'device certificate': '设备证书',
    'device revocation': '设备撤销',
    'device revocation record': '设备撤销记录',
    'certificate': '证书',
    'certificates': '证书',
    'envelope streams': '信封流',
    'stream lifecycle': '流生命周期',
    'byteStream': 'byteStream',
    '@libp2p/utils': '@libp2p/utils',
    'canonicalJson': 'canonicalJson',
    'signCanonicalPayload': 'signCanonicalPayload',
    'verifyCanonicalPayload': 'verifyCanonicalPayload',
    'forSigning': 'forSigning',
    'serial appender': '串行追加器',
    'createSerialJsonlAppender': 'createSerialJsonlAppender',
    'createAuditEvent': 'createAuditEvent',
    'state files': '状态文件',
    'journal': '日志',
    'journal JSONL': '日志JSONL',
    'audit JSONL': '审计JSONL',
    'trust store': '信任存储',
    'peer directory': '对等目录',
    'profile directory': '资料目录',
    'application-data': '应用数据',
    'application data': '应用数据',
    'data directory': '数据目录',
    'data path': '数据路径',
    'storage': '存储',
    'local-first': '本地优先',
    'local-first storage': '本地优先存储',
    'local store': '本地存储',
    'local data': '本地数据',
    'local profile': '本地资料',
    'local profile store': '本地资料存储',
    'cache': '缓存',
    'cached data': '缓存数据',
    'backup': '备份',
    'backups': '备份',
    'backup and recovery': '备份和恢复',
    'restore': '恢复',
    'restore on': '恢复到',
    'hardware migration': '硬件迁移',
    'OS reinstall': '操作系统重装',
    'security': '安全',
    'security model': '安全模型',
    'security architecture': '安全架构',
    'privacy': '隐私',
    'privacy settings': '隐私设置',
    'privacy preferences': '隐私偏好',
    'disclosure': '披露',
    'disclosure settings': '披露设置',
    'cost': '成本',
    'cost ceiling': '成本上限',
    'maxCost': 'maxCost',
    'max sensitivity': '最大敏感度',
    'maxSensitivity': 'maxSensitivity',
    'expiry': '过期',
    'expiresAt': 'expiresAt',
    'budget': '预算',
    'budget cap': '预算上限',
    'allowedActions': 'allowedActions',
    'disallowedActions': 'disallowedActions',
    'allowed actions': '允许的操作',
    'disallowed actions': '不允许的操作',
    'requiresApprovalFor': 'requiresApprovalFor',
    'closeOnFirstCompletedResult': 'closeOnFirstCompletedResult',
    'collectCompletedResults': 'collectCompletedResults',
    'termination policy': '终止策略',
    'startup': '启动',
    'startup warnings': '启动警告',
    'restart': '重启',
    'reload': '重新加载',
    'node reload': '节点重新加载',
    'shutdown': '关闭',
    'stop': '停止',
    'upgrade': '升级',
    'update': '更新',
    'migrations': '迁移',
    'uninstall': '卸载',
    'gatekeeper': '门控',
    'Gatekeeper': 'Gatekeeper',
    'notarization': '公证',
    'notarization and Gatekeeper': '公证和Gatekeeper',
    'firewall prompts': '防火墙提示',
    'Windows Firewall': 'Windows防火墙',
    'macOS firewall': 'macOS防火墙',
    'inbound peer connections': '入站对等连接',
    'outbound TCP': '出站TCP',
    'dynamic ports': '动态端口',
    'file permissions': '文件权限',
    '0o600': '0o600',
    'encrypted': '加密',
    'unencrypted': '未加密',
    'transport encryption': '传输加密',
    'encryption': '加密',
    'TLS': 'TLS',
    'integrity': '完整性',
    'integrity-checked': '完整性检查',
    'replay': '重放',
    'replay dedup': '重放去重',
    'replay protection': '重放保护',
    'rate-limited': '速率限制',
    'rate limiting': '速率限制',
    'rate limit': '速率限制',
    'fan-out': '扇出',
    'fan-out latency': '扇出延迟',
    'backlog': '积压',
    'catch-up': '追赶',
    'latency': '延迟',
    'latencyMs': 'latencyMs',
    'time-sensitive': '时间敏感',
    'time-sensitive coordination': '时间敏感协调',
    'sync': '同步',
    'syncs': '同步',
    'syncing': '同步',
    'synchronization': '同步',
    'indexing runs automatically': '索引自动运行',
    'auto-send': '自动发送',
    'auto-redial': '自动重拨',
    'auto-bond': '自动绑定',
    'automation': '自动化',
    'automation scope': '自动化范围',
    'autonomous': '自主',
    'autonomous work': '自主工作',
    'autonomous agent': '自主智能体',
    'orchestration': '编排',
    'orchestrator': '编排器',
    'orchestrate': '编排',
    'orchestrates': '编排',
    'orchestrated': '已编排',
    'coordination': '协调',
    'coordinated': '协调的',
    'coordinated reports': '协调报告',
    'eligible workers': '合格工作者',
    'workers': '工作者',
    'worker recruitment': '工作者招募',
    'anonymous workers': '匿名工作者',
    'attributed results': '归因结果',
    'attribution': '归因',
    'attributed': '归因的',
    'attributed text': '归因文本',
    'attributed results': '归因结果',
    'contributed': '贡献',
    'contributed each segment': '贡献每个段',
    'delegation': '委托',
    'delegate': '委托',
    'delegated': '已委托',
    'delegated work': '委托工作',
    'delegated tasks': '委托任务',
    'task delegation': '任务委托',
    'specialized work': '专业工作',
    'split analysis': '拆分分析',
    'split research': '拆分研究',
    'research summaries': '研究摘要',
    'draft reports': '草稿报告',
    'draft assistance': '草稿辅助',
    'suggested completions': '建议补全',
    'suggested text': '建议文本',
    'manual composition': '手动编写',
    'in-app': '应用内',
    'in-app search': '应用内搜索',
    'in-app prompts': '应用内提示',
    'in-app banners': '应用内横幅',
    'inline': '内联',
    'inline codes': '内联代码',
    'inline attachments': '内联附件',
    'inline audio': '内联音频',
    'inline chat': '内联聊天',
    'inline agent messages': '内联智能体消息',
    'inline shell': '内联shell',
    'inline terminal': '内联终端',
    'bubble': '气泡',
    'audio bubble': '音频气泡',
    'microphone control': '麦克风控件',
    'microphone permission': '麦克风权限',
    'audio clip': '音频片段',
    'short audio clip': '短音频片段',
    'recording': '录制',
    'record': '录制',
    'playback': '播放',
    'play': '播放',
    'save': '保存',
    'delete': '删除',
    'size caps': '大小限制',
    'size cap': '大小限制',
    'storage management': '存储管理',
    'storage under': '存储在',
    'storage location': '存储位置',
    'storage migrations': '存储迁移',
    'storage paths': '存储路径',
    'storage for': '存储用于',
    'store': '存储',
    'stores': '存储',
    'stored': '已存储',
    'local history': '本地历史',
    'local copies': '本地副本',
    'local thread metadata': '本地线程元数据',
    'local session state': '本地会话状态',
    'local service': '本地服务',
    'local endpoint': '本地端点',
    'local API': '本地API',
    'local assistant': '本地助手',
    'local tunnel': '本地隧道',
    'local network': '本地网络',
    'local mesh': '本地网络',
    'local peer': '本地对等节点',
    'local agent': '本地智能体',
    'local agent orchestration': '本地智能体编排',
    'local agent plan': '本地智能体计划',
    'local agent runtime': '本地智能体运行时',
    'local agent capability': '本地智能体能力',
    'local agent tools': '本地智能体工具',
    'local agent context': '本地智能体上下文',
    'local agent execution': '本地智能体执行',
    'local agent workflow': '本地智能体工作流',
    'local agent automation': '本地智能体自动化',
    'local agent policy': '本地智能体策略',
    'local agent approval': '本地智能体审批',
    'local agent configuration': '本地智能体配置',
    'local agent setup': '本地智能体设置',
    'local agent integration': '本地智能体集成',
    'local agent bridge': '本地智能体桥接',
    'local agent HTTP': '本地智能体HTTP',
    'local agent endpoint': '本地智能体端点',
    'local agent URL': '本地智能体URL',
    'local agent port': '本地智能体端口',
    'local agent address': '本地智能体地址',
    'local agent connection': '本地智能体连接',
    'local agent communication': '本地智能体通信',
    'local agent collaboration': '本地智能体协作',
    'local agent coordination': '本地智能体协调',
    'local agent team': '本地智能体团队',
    'local agent job': '本地智能体任务',
    'local agent task': '本地智能体任务',
    'local agent knowledge': '本地智能体知识',
    'local agent RAG': '本地智能体RAG',
    'local agent vault': '本地智能体保险库',
    'local agent search': '本地智能体搜索',
    'local agent chat': '本地智能体聊天',
    'local agent message': '本地智能体消息',
    'local agent reply': '本地智能体回复',
    'local agent instruction': '本地智能体指令',
    'local agent response': '本地智能体响应',
    'local agent callback': '本地智能体回调',
    'local agent event': '本地智能体事件',
    'local agent status': '本地智能体状态',
    'local agent health': '本地智能体健康',
    'local agent gateway': '本地智能体网关',
    'local agent proxy': '本地智能体代理',
    'local agent router': '本地智能体路由器',
    'local agent firewall': '本地智能体防火墙',
    'local agent guard': '本地智能体守卫',
    'local agent bond': '本地智能体绑定',
    'local agent trust': '本地智能体信任',
    'local agent sensitivity': '本地智能体敏感度',
    'local agent visibility': '本地智能体可见性',
    'local agent publish': '本地智能体发布',
    'local agent browse': '本地智能体浏览',
    'local agent share': '本地智能体共享',
    'local agent access': '本地智能体访问',
    'local agent permission': '本地智能体权限',
    'local agent authorization': '本地智能体授权',
    'local agent mandate': '本地智能体授权',
    'local agent scope': '本地智能体范围',
    'local agent capability': '本地智能体能力',
    'local agent tool': '本地智能体工具',
    'local agent capability': '本地智能体能力',
    'local agent plugin': '本地智能体插件',
    'local agent extension': '本地智能体扩展',
    'local agent channel': '本地智能体渠道',
    'local agent preset': '本地智能体预设',
    'local agent configuration': '本地智能体配置',
    'local agent setup': '本地智能体设置',
    'local agent integration': '本地智能体集成',
    'local agent bridge': '本地智能体桥接',
    'local agent HTTP': '本地智能体HTTP',
    'local agent endpoint': '本地智能体端点',
    'local agent URL': '本地智能体URL',
    'local agent port': '本地智能体端口',
    'local agent address': '本地智能体地址',
    'local agent connection': '本地智能体连接',
    'local agent communication': '本地智能体通信',
    'local agent collaboration': '本地智能体协作',
    'local agent coordination': '本地智能体协调',
    'local agent team': '本地智能体团队',
    'local agent job': '本地智能体任务',
    'local agent task': '本地智能体任务',
    'local agent knowledge': '本地智能体知识',
    'local agent RAG': '本地智能体RAG',
    'local agent vault': '本地智能体保险库',
    'local agent search': '本地智能体搜索',
    'local agent chat': '本地智能体聊天',
    'local agent message': '本地智能体消息',
    'local agent reply': '本地智能体回复',
    'local agent instruction': '本地智能体指令',
    'local agent response': '本地智能体响应',
    'local agent callback': '本地智能体回调',
    'local agent event': '本地智能体事件',
    'local agent status': '本地智能体状态',
    'local agent health': '本地智能体健康',
    'local agent gateway': '本地智能体网关',
    'local agent proxy': '本地智能体代理',
    'local agent router': '本地智能体路由器',
    'local agent firewall': '本地智能体防火墙',
    'local agent guard': '本地智能体守卫',
    'local agent bond': '本地智能体绑定',
    'local agent trust': '本地智能体信任',
    'local agent sensitivity': '本地智能体敏感度',
    'local agent visibility': '本地智能体可见性',
    'local agent publish': '本地智能体发布',
    'local agent browse': '本地智能体浏览',
    'local agent share': '本地智能体共享',
    'local agent access': '本地智能体访问',
    'local agent permission': '本地智能体权限',
    'local agent authorization': '本地智能体授权',
    'local agent mandate': '本地智能体授权',
    'local agent scope': '本地智能体范围',
    'local agent capability': '本地智能体能力',
    'local agent tool': '本地智能体工具',
    'local agent capability': '本地智能体能力',
    'local agent plugin': '本地智能体插件',
    'local agent extension': '本地智能体扩展',
    'local agent channel': '本地智能体渠道',
    'local agent preset': '本地智能体预设',
    'remote': '远程',
    'remote control': '远程控制',
    'remote access': '远程访问',
    'remote shell access': '远程shell访问',
    'remote terminal': '远程终端',
    'remote terminal access': '远程终端访问',
    'remote attach': '远程连接',
    'remote profile': '远程资料',
    'remote provider': '远程提供商',
    'remote providers': '远程提供商',
    'remote model': '远程模型',
    'remote models': '远程模型',
    'remote inference': '远程推理',
    'remote URL': '远程URL',
    'remote peer': '远程对等节点',
    'remote peer reachability': '远程对等节点可达性',
    'remote client': '远程客户端',
    'remote orchestrator': '远程编排器',
    'remote agent': '远程智能体',
    'remote agent delegation': '远程智能体委托',
    'remote agent capability': '远程智能体能力',
    'remote agent tools': '远程智能体工具',
    'remote agent context': '远程智能体上下文',
    'remote agent execution': '远程智能体执行',
    'remote agent workflow': '远程智能体工作流',
    'remote agent automation': '远程智能体自动化',
    'remote agent policy': '远程智能体策略',
    'remote agent approval': '远程智能体审批',
    'remote agent configuration': '远程智能体配置',
    'remote agent setup': '远程智能体设置',
    'remote agent integration': '远程智能体集成',
    'remote agent bridge': '远程智能体桥接',
    'remote agent HTTP': '远程智能体HTTP',
    'remote agent endpoint': '远程智能体端点',
    'remote agent URL': '远程智能体URL',
    'remote agent port': '远程智能体端口',
    'remote agent address': '远程智能体地址',
    'remote agent connection': '远程智能体连接',
    'remote agent communication': '远程智能体通信',
    'remote agent collaboration': '远程智能体协作',
    'remote agent coordination': '远程智能体协调',
    'remote agent team': '远程智能体团队',
    'remote agent job': '远程智能体任务',
    'remote agent task': '远程智能体任务',
    'remote agent knowledge': '远程智能体知识',
    'remote agent RAG': '远程智能体RAG',
    'remote agent vault': '远程智能体保险库',
    'remote agent search': '远程智能体搜索',
    'remote agent chat': '远程智能体聊天',
    'remote agent message': '远程智能体消息',
    'remote agent reply': '远程智能体回复',
    'remote agent instruction': '远程智能体指令',
    'remote agent response': '远程智能体响应',
    'remote agent callback': '远程智能体回调',
    'remote agent event': '远程智能体事件',
    'remote agent status': '远程智能体状态',
    'remote agent health': '远程智能体健康',
    'remote agent gateway': '远程智能体网关',
    'remote agent proxy': '远程智能体代理',
    'remote agent router': '远程智能体路由器',
    'remote agent firewall': '远程智能体防火墙',
    'remote agent guard': '远程智能体守卫',
    'remote agent bond': '远程智能体绑定',
    'remote agent trust': '远程智能体信任',
    'remote agent sensitivity': '远程智能体敏感度',
    'remote agent visibility': '远程智能体可见性',
    'remote agent publish': '远程智能体发布',
    'remote agent browse': '远程智能体浏览',
    'remote agent share': '远程智能体共享',
    'remote agent access': '远程智能体访问',
    'remote agent permission': '远程智能体权限',
    'remote agent authorization': '远程智能体授权',
    'remote agent mandate': '远程智能体授权',
    'remote agent scope': '远程智能体范围',
    'remote agent capability': '远程智能体能力',
    'remote agent tool': '远程智能体工具',
    'remote agent capability': '远程智能体能力',
    'remote agent plugin': '远程智能体插件',
    'remote agent extension': '远程智能体扩展',
    'remote agent channel': '远程智能体渠道',
    'remote agent preset': '远程智能体预设',
}

SECTION_HEADERS = {
    '# EnvoyMesh Guidebook': '# EnvoyMesh 指南',
    '**Version:**': '**版本：**',
    '**Edition:**': '**版本类型：**',
    '**Revised:**': '**修订日期：**',
    '**Languages:**': '**语言：**',
    '**Audience:**': '**受众：**',
    '**Purpose:**': '**目的：**',
    '## How to read this guide': '## 如何阅读本指南',
    '## Feature status labels': '## 功能状态标签',
    '## Product terminology used in this guide': '## 本指南使用的产品术语',
    '# Table of Contents': '# 目录',
    '## Part I — Discover EnvoyMesh': '## 第一部分 — 认识 EnvoyMesh',
    '### 1. Welcome to EnvoyMesh': '### 1. 欢迎来到 EnvoyMesh',
    '#### 1.1 A private network for people and AI agents': '#### 1.1 面向人类和AI智能体的私有网络',
    '#### 1.2 Local-first and peer-to-peer by design': '#### 1.2 设计上优先本地和点对点',
    '#### 1.3 No central account required': '#### 1.3 无需中央账户',
    '#### 1.4 Your identity, relationships, and data belong to you': '#### 1.4 您的身份、关系和数据属于您自己',
    '#### 1.5 Direct connections and optional relays': '#### 1.5 直接连接和可选中继',
    '#### 1.6 Personal agents and external agents': '#### 1.6 个人智能体和外部智能体',
    '#### 1.7 Trusted multi-agent collaboration': '#### 1.7 可信多智能体协作',
    '#### 1.8 Open protocols and interoperability': '#### 1.8 开放协议和互操作性',
    '#### 1.9 Major features at a glance': '#### 1.9 主要功能一览',
    '#### 1.10 Current availability and limitations': '#### 1.10 当前可用性和限制',
    '### 2. Why EnvoyMesh?': '### 2. 为什么选择 EnvoyMesh？',
    '#### 2.1 Private communication without a central platform': '#### 2.1 无需中央平台的私密通信',
    '#### 2.2 Self-sovereign identity across your devices': '#### 2.2 跨设备的自主身份',
    '#### 2.3 AI assistance under your control': '#### 2.3 由您掌控的AI助手',
    '#### 2.4 Trusted knowledge sharing': '#### 2.4 可信知识共享',
    '#### 2.5 Safe task delegation': '#### 2.5 安全的任务委托',
    '#### 2.6 Collaboration among agents you choose': '#### 2.6 您选择的智能体之间的协作',
    '#### 2.7 Local models, remote models, and external agents': '#### 2.7 本地模型、远程模型和外部智能体',
    '#### 2.8 Auditability instead of invisible automation': '#### 2.8 可审计性而非隐形自动化',
    '#### 2.9 When EnvoyMesh is the right choice': '#### 2.9 何时适合使用 EnvoyMesh',
    '#### 2.10 When another solution may be a better fit': '#### 2.10 何时其他解决方案更合适',
    '### 3. What You Can Do': '### 3. 您可以做什么',
    '#### 3.1 Connect with trusted people': '#### 3.1 与信任的人建立连接',
    '#### 3.2 Exchange private messages': '#### 3.2 交换私密消息',
    '#### 3.3 Create group conversations': '#### 3.3 创建群组对话',
    '#### 3.4 Send audio messages and make voice calls': '#### 3.4 发送语音消息和进行语音通话',
    '#### 3.5 Share files and profile photos': '#### 3.5 共享文件和资料照片',
    '#### 3.6 Talk to your personal AI agent': '#### 3.6 与您的个人AI智能体对话',
    '#### 3.7 Connect OpenClaw, HomeClaw, Hermes, or OpenHuman': '#### 3.7 连接 OpenClaw、HomeClaw、Hermes 或 OpenHuman',
    '#### 3.8 Search local and trusted knowledge': '#### 3.8 搜索本地和可信知识',
    '#### 3.9 Publish and browse mesh content': '#### 3.9 发布和浏览网络内容',
    '#### 3.10 Delegate work to another agent': '#### 3.10 将工作委托给另一个智能体',
    '#### 3.11 Run Team jobs across several agents': '#### 3.11 在多个智能体上运行团队任务',
    '#### 3.12 Connect MCP and A2A applications': '#### 3.12 连接 MCP 和 A2A 应用',
    '#### 3.13 Use terminals remotely': '#### 3.13 远程使用终端',
    '#### 3.14 Operate a private or community relay': '#### 3.14 运行私有或社区中继',
    '### 4. How EnvoyMesh Works': '### 4. EnvoyMesh 如何工作',
    '#### 4.1 A plain-language system overview': '#### 4.1 系统概览（通俗易懂版）',
    '#### 4.2 Owners, devices, agents, and peers': '#### 4.2 所有者、设备、智能体和对等节点',
    '#### 4.3 Contacts, bonds, and trust levels': '#### 4.3 联系人、绑定和信任等级',
    '#### 4.4 Signed messages and verifiable senders': '#### 4.4 签名消息和可验证发送者',
    '#### 4.5 Personal agents and external-agent bridges': '#### 4.5 个人智能体和外部智能体桥接',
    '#### 4.6 Local knowledge, the Library, and the Vault': '#### 4.6 本地知识、库和保险库',
    '#### 4.7 Tasks, mandates, and approvals': '#### 4.7 任务、授权和审批',
    '#### 4.8 Agent Network membership': '#### 4.8 智能体网络成员资格',
    '#### 4.9 Direct networking and relay assistance': '#### 4.9 直接网络和中继协助',
    '#### 4.10 Activity records and end-to-end auditing': '#### 4.10 活动记录和端到端审计',
    '### 5. Common Use Cases': '### 5. 常见用例',
    '#### 5.1 A private personal AI across devices': '#### 5.1 跨设备的私密个人AI',
    '#### 5.2 A family or friends mesh': '#### 5.2 家庭或朋友网络',
    '#### 5.3 Trusted research and knowledge exchange': '#### 5.3 可信研究和知识交流',
    '#### 5.4 A small-team Agent Network': '#### 5.4 小型团队智能体网络',
    '#### 5.5 Multi-agent planning and report generation': '#### 5.5 多智能体规划和报告生成',
    '#### 5.6 OpenClaw with trusted mesh contacts': '#### 5.6 与可信网络联系人一起使用 OpenClaw',
    '#### 5.7 HomeClaw as an external EnvoyMesh agent': '#### 5.7 将 HomeClaw 作为外部 EnvoyMesh 智能体',
    '#### 5.8 Hermes as an external EnvoyMesh agent': '#### 5.8 将 Hermes 作为外部 EnvoyMesh 智能体',
    '#### 5.9 OpenHuman as an external EnvoyMesh agent': '#### 5.9 将 OpenHuman 作为外部 EnvoyMesh 智能体',
    '#### 5.10 Claude Desktop using EnvoyMesh through MCP': '#### 5.10 通过 MCP 使用 EnvoyMesh 的 Claude Desktop',
    '#### 5.11 External A2A clients delegating tasks': '#### 5.11 委托任务的外部 A2A 客户端',
    '#### 5.12 A self-hosted relay fleet': '#### 5.12 自托管中继集群',
    '### 6. Product and Protocol Comparisons': '### 6. 产品和协议比较',
    '#### 6.1 EnvoyMesh and centralized messengers': '#### 6.1 EnvoyMesh 与集中式信使',
    '#### 6.2 EnvoyMesh and cloud AI assistants': '#### 6.2 EnvoyMesh 与云AI助手',
    '#### 6.3 EnvoyMesh and standalone OpenClaw': '#### 6.3 EnvoyMesh 与独立 OpenClaw',
    '#### 6.4 EnvoyMesh and external agent runtimes': '#### 6.4 EnvoyMesh 与外部智能体运行时',
    '#### 6.5 EnvoyMesh and MCP': '#### 6.5 EnvoyMesh 与 MCP',
    '#### 6.6 EnvoyMesh and A2A': '#### 6.6 EnvoyMesh 与 A2A',
    '#### 6.7 EnvoyMesh native Agent Network versus public marketplaces': '#### 6.7 EnvoyMesh 原生智能体网络与公共市场',
    '#### 6.8 Native protocols versus interoperability bridges': '#### 6.8 原生协议与互操作性桥接',
    '## Part II — Install and Get Started': '## 第二部分 — 安装和入门',
    '### 7. Choose Your Setup': '### 7. 选择您的设置',
    '#### 7.1 Desktop only': '#### 7.1 仅桌面',
    '#### 7.2 Desktop with EnvoyGo mobile access': '#### 7.2 桌面配合 EnvoyGo 移动访问',
    '#### 7.3 Desktop with the bundled EnvoyAI agent': '#### 7.3 桌面配合捆绑的 EnvoyAI 智能体',
    '#### 7.4 Desktop with an external agent': '#### 7.4 桌面配合外部智能体',
    '#### 7.5 Desktop with local or remote models': '#### 7.5 桌面配合本地或远程模型',
    '#### 7.6 Personal relay or community relay': '#### 7.6 个人中继或社区中继',
    '#### 7.7 Small-team and organization deployments': '#### 7.7 小型团队和组织部署',
    '#### 7.8 Recommended first-time setup': '#### 7.8 推荐的首次设置',
    '### 8. Install EnvoyMesh': '### 8. 安装 EnvoyMesh',
    '#### 8.1 System requirements': '#### 8.1 系统要求',
    '#### 8.2 Install on macOS': '#### 8.2 在 macOS 上安装',
    '#### 8.3 Install on Windows': '#### 8.3 在 Windows 上安装',
    '#### 8.4 Install EnvoyGo on iOS': '#### 8.4 在 iOS 上安装 EnvoyGo',
    '#### 8.5 Install EnvoyGo on Android': '#### 8.5 在 Android 上安装 EnvoyGo',
    '#### 8.6 Install from source': '#### 8.6 从源码安装',
    '#### 8.7 Verify the installation': '#### 8.7 验证安装',
    '#### 8.8 Application data locations': '#### 8.8 应用数据位置',
    '#### 8.9 Update EnvoyMesh': '#### 8.9 更新 EnvoyMesh',
    '#### 8.10 Uninstall without losing identity or data': '#### 8.10 卸载而不丢失身份或数据',
    '### 9. Platform and Package Differences': '### 9. 平台和包差异',
    '#### 9.1 Desktop and mobile feature comparison': '#### 9.1 桌面和移动功能比较',
    '#### 9.2 macOS packaging': '#### 9.2 macOS 打包',
    '#### 9.3 Windows packaging': '#### 9.3 Windows 打包',
    '#### 9.4 OpenClaw extensions bundled on macOS': '#### 9.4 macOS 上捆绑的 OpenClaw 扩展',
    '#### 9.5 Essential OpenClaw extension selection on Windows': '#### 9.5 Windows 上的必要 OpenClaw 扩展选择',
    '#### 9.6 Full and slim desktop bundles': '#### 9.6 完整和精简桌面包',
    '#### 9.7 Optional IPFS sidecars': '#### 9.7 可选 IPFS 辅助组件',
    '#### 9.8 Features requiring a home node': '#### 9.8 需要主节点的功能',
    '#### 9.9 Features available as an EnvoyGo mobile mirror': '#### 9.9 EnvoyGo 移动镜像可用的功能',
    '#### 9.10 Legacy mobile experiments and current product boundaries': '#### 9.10 遗留移动实验和当前产品边界',
    '### 10. Create Your Identity': '### 10. 创建您的身份',
    '#### 10.1 What your EnvoyMesh identity represents': '#### 10.1 您的 EnvoyMesh 身份代表什么',
    '#### 10.2 Create an owner identity': '#### 10.2 创建所有者身份',
    '#### 10.3 Create your first device identity': '#### 10.3 创建您的第一个设备身份',
    '#### 10.4 Create or activate your agent identity': '#### 10.4 创建或激活您的智能体身份',
    '#### 10.5 Set your display profile': '#### 10.5 设置您的显示资料',
    '#### 10.6 Understand your DID': '#### 10.6 理解您的 DID',
    '#### 10.7 Protect your cryptographic keys': '#### 10.7 保护您的加密密钥',
    '#### 10.8 Back up identity and recovery data': '#### 10.8 备份身份和恢复数据',
    '#### 10.9 Add another device': '#### 10.9 添加另一台设备',
    '#### 10.10 Revoke a lost or compromised device': '#### 10.10 撤销丢失或受损的设备',
    '### 11. Tour the Application': '### 11. 应用程序导览',
    '#### 11.1 Home and node status': '#### 11.1 首页和节点状态',
    '#### 11.2 Conversations': '#### 11.2 对话',
    '#### 11.3 Contacts and discovery': '#### 11.3 联系人与发现',
    '#### 11.4 Groups': '#### 11.4 群组',
    '#### 11.5 Knowledge Base and Library': '#### 11.5 知识库和库',
    '#### 11.6 Browser': '#### 11.6 浏览器',
    '#### 11.7 Team jobs': '#### 11.7 团队任务',
    '#### 11.8 Terminals': '#### 11.8 终端',
    '#### 11.9 Approvals and activity': '#### 11.9 审批和活动',
    '#### 11.10 Profile': '#### 11.10 资料',
    '#### 11.11 Settings': '#### 11.11 设置',
    '#### 11.12 Connection and agent status indicators': '#### 11.12 连接和智能体状态指示器',
    '### 12. Connect Your First Contact': '### 12. 连接您的第一个联系人',
    '#### 12.1 What pairing and bonding do': '#### 12.1 配对和绑定的作用',
    '#### 12.2 Pair with a QR code': '#### 12.2 使用二维码配对',
    '#### 12.3 Pair with an invitation link': '#### 12.3 使用邀请链接配对',
    '#### 12.4 Pair on a local network': '#### 12.4 在本地网络上配对',
    '#### 12.5 Verify identity information': '#### 12.5 验证身份信息',
    '#### 12.6 Choose an appropriate trust level': '#### 12.6 选择适当的信任等级',
    '#### 12.7 Accept a bond request': '#### 12.7 接受绑定请求',
    '#### 12.8 Send the first message': '#### 12.8 发送第一条消息',
    '#### 12.9 Confirm direct or relay-assisted delivery': '#### 12.9 确认直接或中继辅助送达',
    '#### 12.10 Troubleshoot pairing': '#### 12.10 排查配对问题',
    '#### 12.11 Bundled sponsor contact': '#### 12.11 捆绑的赞助商联系人',
    '### 13. Connect EnvoyGo': '### 13. 连接 EnvoyGo',
    '#### 13.1 How EnvoyGo works with a home node': '#### 13.1 EnvoyGo 如何与主节点协作',
    '#### 13.2 Pair the mobile app': '#### 13.2 配对移动应用',
    '#### 13.3 Confirm the home connection': '#### 13.3 确认主连接',
    '#### 13.4 Use chat and contacts': '#### 13.4 使用聊天和联系人',
    '#### 13.5 Use remote terminals': '#### 13.5 使用远程终端',
    '#### 13.6 View Team jobs': '#### 13.6 查看团队任务',
    '#### 13.7 Browse mesh content': '#### 13.7 浏览网络内容',
    '#### 13.8 Receive notifications': '#### 13.8 接收通知',
    '#### 13.9 Make and receive voice calls': '#### 13.9 拨打和接听语音通话',
    '#### 13.10 Revoke a lost phone': '#### 13.10 撤销丢失的手机',
    '#### 13.11 Current mobile limitations': '#### 13.11 当前移动限制',
    '### 14. First-Day Tutorials': '### 14. 第一天教程',
    '#### 14.1 Send a private message': '#### 14.1 发送私密消息',
    '#### 14.2 Create a group conversation': '#### 14.2 创建群组对话',
    '#### 14.3 Send an audio message': '#### 14.3 发送语音消息',
    '#### 14.4 Make a voice call': '#### 14.4 进行语音通话',
    '#### 14.5 Share a file': '#### 14.5 共享文件',
    '#### 14.6 Ask EnvoyAI a question': '#### 14.6 向 EnvoyAI 提问',
    '#### 14.7 Add knowledge to your Library': '#### 14.7 向您的库中添加知识',
    '#### 14.8 Search your Vault': '#### 14.8 搜索您的保险库',
    '#### 14.9 Ask a bonded agent for knowledge': '#### 14.9 向绑定的智能体询问知识',
    '#### 14.10 Approve a sensitive action': '#### 14.10 审批敏感操作',
    '#### 14.11 Start a simple Team job': '#### 14.11 启动简单的团队任务',
    '#### 14.12 Connect an external agent': '#### 14.12 连接外部智能体',
    '## Part III — People, Profiles, and Conversations': '## 第三部分 — 人员、资料和对话',
    '### 15. Contacts and Bonds': '### 15. 联系人与绑定',
    '#### 15.1 View and search contacts': '#### 15.1 查看和搜索联系人',
    '#### 15.2 Understand contact identity': '#### 15.2 理解联系人身份',
    '#### 15.3 Contact profiles and photos': '#### 15.3 联系人资料和照片',
    '#### 15.4 Online, offline, and connection states': '#### 15.4 在线、离线和连接状态',
    '#### 15.5 Direct, referred, public, and blocked trust': '#### 15.5 直接、推荐、公开和阻止信任',
    '#### 15.6 Change a contact’s trust level': '#### 15.6 更改联系人的信任等级',
    '#### 15.7 Refer or introduce a contact': '#### 15.7 推荐或介绍联系人',
    '#### 15.8 Mute, block, or remove a contact': '#### 15.8 静音、阻止或移除联系人',
    '#### 15.9 Restore a connection': '#### 15.9 恢复连接',
    '#### 15.10 Contact privacy and disclosure settings': '#### 15.10 联系人隐私和披露设置',
    '### 16. Private Messaging': '### 16. 私密消息',
    '#### 16.1 Start a conversation': '#### 16.1 开始对话',
    '#### 16.2 Human-to-human messages': '#### 16.2 人对人消息',
    '#### 16.3 Human-to-agent messages': '#### 16.3 人对智能体消息',
    '#### 16.4 Replies and conversation continuity': '#### 16.4 回复和对话连续性',
    '#### 16.5 Message delivery states': '#### 16.5 消息送达状态',
    '#### 16.6 Offline behavior and retries': '#### 16.6 离线行为和重试',
    '#### 16.7 Search conversation history': '#### 16.7 搜索对话历史',
    '#### 16.8 Draft assistance': '#### 16.8 草稿辅助',
    '#### 16.9 Manage conversation data': '#### 16.9 管理对话数据',
    '#### 16.10 Message privacy and security': '#### 16.10 消息隐私和安全',
    '### 17. Group Conversations': '### 17. 群组对话',
    '#### 17.1 Create a group': '#### 17.1 创建群组',
    '#### 17.2 Invite members': '#### 17.2 邀请成员',
    '#### 17.3 Send group messages': '#### 17.3 发送群组消息',
    '#### 17.4 Manage membership': '#### 17.4 管理成员',
    '#### 17.5 Leave a group': '#### 17.5 离开群组',
    '#### 17.6 Group trust boundaries': '#### 17.6 群组信任边界',
    '#### 17.7 Group delivery and offline members': '#### 17.7 群组送达和离线成员',
    '#### 17.8 Group troubleshooting': '#### 17.8 群组排查',
    '### 18. Audio and Voice Calls': '### 18. 音频和语音通话',
    '#### 18.1 Record and send an audio message': '#### 18.1 录制和发送语音消息',
    '#### 18.2 Play and manage audio attachments': '#### 18.2 播放和管理音频附件',
    '#### 18.3 Start a voice call': '#### 18.3 发起语音通话',
    '#### 18.4 Answer or decline a call': '#### 18.4 接听或拒绝通话',
    '#### 18.5 Call status and controls': '#### 18.5 通话状态和控制',
}

SENTENCE_TRANSLATIONS = {
    'This guide reflects the EnvoyMesh 0.1.0 repository state at the revision date.': '本指南反映了修订日期时 EnvoyMesh 0.1.0 存储库的状态。',
    'It is written for end users, not as a content-outline stub.': '它是为最终用户编写的，而不是作为内容大纲存根。',
    'Feature status can differ by platform and deployment—verify each Beta or Experimental capability in your build (release notes, Settings labels, and Appendix J) before relying on it in production.': '功能状态可能因平台和部署而异——在生产中依赖它之前，请验证您的构建（版本说明、设置标签和附录J）中的每个Beta或实验性功能。',
    '- **Parts I–XIV** explain the product for end users and operators.': '- **第一至十四部分**向最终用户和操作员解释该产品。',
    '- **Part XV** is for website editors and content operators and is optional for end users.': '- **第十五部分**适用于网站编辑和内容运营商，对于最终用户来说是可选的。',
    'Task lifecycle names such as *Created* / *Task planned* / *Running* are EnvoyMesh states, not product **Planned** / **Available** status labels.': '任务生命周期名称（例如*已创建* / *任务已计划* / *运行中*）是 EnvoyMesh 状态，而不是产品**计划中** / **可用**状态标签。',
    '- **Mobile** in this guide means **EnvoyGo** (thin client paired to a home node), unless a section explicitly discusses legacy mobile experiments.': '- 本指南中的**移动**指的是**EnvoyGo**（与主节点配对的瘦客户端），除非某节明确讨论遗留移动实验。',
    '- **Available** — implemented and intended for current use.': '- **可用** — 已实施并供当前使用。',
    '- **Beta** — implemented, but still receiving validation or product polish.': '- **Beta** — 已实施，但仍在接受验证或产品完善。',
    '- **Experimental** — usable for evaluation; behavior or interfaces may change.': '- **实验性** — 可用于评估；行为或界面可能会改变。',
    '- **Compatibility preset** — EnvoyMesh includes configuration for the integration, while part of the integration is maintained by another project.': '- **兼容性预设** — EnvoyMesh 包括集成的配置，而部分集成由另一个项目维护。',
    '- **Planned** — designed or documented, but not currently available as a complete product feature.': '- **计划中** — 已设计或记录，但目前不作为完整的产品功能提供。',
    '- **Parked** — intentionally deferred without a committed release date.': '- **暂停** — 有意推迟，没有承诺的发布日期。',
    '- **Desktop** — available through the EnvoyMesh desktop application or home node.': '- **桌面** — 通过 EnvoyMesh 桌面应用程序或主节点可用。',
    '- **Mobile** — available in EnvoyGo, the current EnvoyMesh mobile product (home-paired thin client).': '- **移动** — 在当前的 EnvoyMesh 移动产品 EnvoyGo（与家庭配对的瘦客户端）中可用。',
    '- **Operator** — intended for node, relay, or fleet administrators.': '- **操作员** — 适用于节点、中继或集群管理员。',
    '- **EnvoyAI / OpenClaw** is the richer bundled agent integration included with EnvoyMesh.': '- **EnvoyAI / OpenClaw**是 EnvoyMesh 中包含的更丰富的捆绑智能体