#!/usr/bin/env python3
import re

TERM_MAP = {
    'EnvoyMesh': 'EnvoyMesh',
    'EnvoyGo': 'EnvoyGo',
    'EnvoyAI': 'EnvoyAI',
    'OpenClaw': 'OpenClaw',
    'HomeClaw': 'HomeClaw',
    'Hermes': 'Hermes',
    'OpenHuman': 'OpenHuman',
    'libp2p': 'libp2p',
    'Ed25519': 'Ed25519',
    'DID': 'DID',
    'DIDs': 'DID',
    'MCP': 'MCP',
    'A2A': 'A2A',
    'JSON-RPC': 'JSON-RPC',
    'WebSocket': 'WebSocket',
    'RAG': 'RAG',
    'Vault': '保险库',
    'Library': '库',
    'Social': 'Social',
    'Node': '节点',
    'Home Node': '家庭节点',
    'Agent': '智能体',
    'Bond': '绑定',
    'Trust': '信任',
    'Peer': '对等节点',
    'Mesh': '网格',
    'Profile': '资料',
    'Contact': '联系人',
    'Team jobs': '团队任务',
    'Relay': '中继',
    'Terminal': '终端',
    'Browser': '浏览器',
    'Mandate': '授权',
    'Approval': '审批',
    'Audit': '审计',
    'Knowledge': '知识',
    'Conversation': '对话',
    'Group': '群组',
    'Voice call': '语音通话',
    'Audio message': '语音消息',
    'QR code': '二维码',
    'Pairing': '配对',
    'Discovery': '发现',
    'mDNS': 'mDNS',
    'DHT': 'DHT',
    'TCP': 'TCP',
    'QUIC': 'QUIC',
    'LAN': '局域网',
    'WAN': '广域网',
    'NAT': 'NAT',
    'TURN': 'TURN',
    'PTY': 'PTY',
    'JSONL': 'JSONL',
    'Claude': 'Claude',
    'Obsidian': 'Obsidian',
    'OpenAI': 'OpenAI',
    'LiteLLM': 'LiteLLM',
    'Phase': '阶段',
    'Beta': 'Beta',
    'Experimental': '实验性',
    'Available': '可用',
    'Planned': '计划中',
    'Parked': '暂停',
    'Desktop': '桌面',
    'Mobile': '移动',
    'Operator': '操作员',
    'Compatibility preset': '兼容性预设',
    'Settings': '设置',
    'AI': 'AI',
    'People': '联系人',
    'Chat': '聊天',
    'Groups': '群组',
    'Terminals': '终端',
    'Activity': '活动',
    'Home': '首页',
    'Me': '我',
    'Node status': '节点状态',
    'Gallery': '相册',
    'Knowledge Base': '知识库',
    'Ext Agent': '外部智能体',
    'Knowledge': '知识',
    'Network': '网络',
    'Privacy': '隐私',
    'Automation': '自动化',
    'Tools': '工具',
    'AI Engine': 'AI引擎',
    'Team job defaults': '团队任务默认设置',
    'Workers status': '工作节点状态',
    'Introduce': '介绍',
    'Trust': '信任',
    'Mute': '静音',
    'Block': '阻止',
    'Remove': '移除',
    'Leave group': '离开群组',
    'New group': '新建群组',
    'New Note': '新建笔记',
    'Refresh workers': '刷新工作节点',
    'Join Agent Network': '加入智能体网络',
    'Blocked': '阻止',
    'Public': '公开',
    'Referred': '推荐',
    'Direct': '直接',
    'Self': '自己',
}

SECTION_TRANSLATIONS = {
    '# EnvoyMesh Guidebook': '# EnvoyMesh 指南',
    '**Version:**': '**版本:**',
    '**Edition:**': '**版本类型:**',
    '**Revised:**': '**修订日期:**',
    '**Languages:**': '**语言:**',
    '**Audience:**': '**受众:**',
    '**Purpose:**': '**目的:**',
    '> **Complete Guidebook Edition.**': '> **完整指南版。**',
    '## How to read this guide': '## 如何阅读本指南',
    '## Feature status labels': '## 功能状态标签',
    '## Product terminology used in this guide': '## 本指南使用的产品术语',
    '# Table of Contents': '# 目录',
    '## Part I — Discover EnvoyMesh': '## 第一部分 — 认识 EnvoyMesh',
    '### 1. Welcome to EnvoyMesh': '### 1. 欢迎来到 EnvoyMesh',
    '#### 1.1 A private network for people and AI agents': '#### 1.1 面向人类和AI智能体的私有网络',
    '#### 1.2 Local-first and peer-to-peer by design': '#### 1.2 设计上优先本地和点对点',
    '#### 1.3 No central account required': '#### 1.3 无需中央账户',
    '#### 1.4 Your identity, relationships, and data belong to you': '#### 1.4 您的身份、关系和数据属于您自己',
    '#### 1.5 Direct connections and optional relays': '#### 1.5 直接连接和可选中继',
    '#### 1.6 Personal agents and external agents': '#### 1.6 个人智能体和外部智能体',
    '#### 1.7 Trusted multi-agent collaboration': '#### 1.7 可信多智能体协作',
    '#### 1.8 Open protocols and interoperability': '#### 1.8 开放协议和互操作性',
    '#### 1.9 Major features at a glance': '#### 1.9 主要功能一览',
    '#### 1.10 Current availability and limitations': '#### 1.10 当前可用性和限制',
    '### 2. Why EnvoyMesh?': '### 2. 为什么选择 EnvoyMesh？',
    '#### 2.1 Private communication without a central platform': '#### 2.1 无需中央平台的私密通信',
    '#### 2.2 Self-sovereign identity across your devices': '#### 2.2 跨设备的自主身份',
    '#### 2.3 AI assistance under your control': '#### 2.3 由您掌控的AI助手',
    '#### 2.4 Trusted knowledge sharing': '#### 2.4 可信知识共享',
    '#### 2.5 Safe task delegation': '#### 2.5 安全的任务委托',
    '#### 2.6 Collaboration among agents you choose': '#### 2.6 您选择的智能体之间的协作',
    '#### 2.7 Local models, remote models, and external agents': '#### 2.7 本地模型、远程模型和外部智能体',
    '#### 2.8 Auditability instead of invisible automation': '#### 2.8 可审计性而非隐形自动化',
    '#### 2.9 When EnvoyMesh is the right choice': '#### 2.9 何时适合使用 EnvoyMesh',
    '#### 2.10 When another solution may be a better fit': '#### 2.10 何时其他解决方案更合适',
    '### 3. What You Can Do': '### 3. 您可以做什么',
    '#### 3.1 Connect with trusted people': '#### 3.1 与信任的人建立连接',
    '#### 3.2 Exchange private messages': '#### 3.2 交换私密消息',
    '#### 3.3 Create group conversations': '#### 3.3 创建群组对话',
    '#### 3.4 Send audio messages and make voice calls': '#### 3.4 发送语音消息和进行语音通话',
    '#### 3.5 Share files and profile photos': '#### 3.5 共享文件和资料照片',
    '#### 3.6 Talk to your personal AI agent': '#### 3.6 与您的个人AI智能体对话',
    '#### 3.7 Connect OpenClaw, HomeClaw, Hermes, or OpenHuman': '#### 3.7 连接 OpenClaw、HomeClaw、Hermes 或 OpenHuman',
    '#### 3.8 Search local and trusted knowledge': '#### 3.8 搜索本地和可信知识',
    '#### 3.9 Publish and browse mesh content': '#### 3.9 发布和浏览网络内容',
    '#### 3.10 Delegate work to another agent': '#### 3.10 将工作委托给另一个智能体',
    '#### 3.11 Run Team jobs across several agents': '#### 3.11 在多个智能体上运行团队任务',
    '#### 3.12 Connect MCP and A2A applications': '#### 3.12 连接 MCP 和 A2A 应用',
    '#### 3.13 Use terminals remotely': '#### 3.13 远程使用终端',
    '#### 3.14 Operate a private or community relay': '#### 3.14 运行私有或社区中继',
    '### 4. How EnvoyMesh Works': '### 4. EnvoyMesh 如何工作',
    '#### 4.1 A plain-language system overview': '#### 4.1 系统概览（通俗易懂版）',
    '#### 4.2 Owners, devices, agents, and peers': '#### 4.2 所有者、设备、智能体和对等节点',
    '#### 4.3 Contacts, bonds, and trust levels': '#### 4.3 联系人、绑定和信任等级',
    '#### 4.4 Signed messages and verifiable senders': '#### 4.4 签名消息和可验证发送者',
    '#### 4.5 Personal agents and external-agent bridges': '#### 4.5 个人智能体和外部智能体桥接',
    '#### 4.6 Local knowledge, the Library, and the Vault': '#### 4.6 本地知识、库和保险库',
    '#### 4.7 Tasks, mandates, and approvals': '#### 4.7 任务、授权和审批',
    '#### 4.8 Agent Network membership': '#### 4.8 智能体网络成员资格',
    '#### 4.9 Direct networking and relay assistance': '#### 4.9 直接网络和中继协助',
    '#### 4.10 Activity records and end-to-end auditing': '#### 4.10 活动记录和端到端审计',
    '### 5. Common Use Cases': '### 5. 常见用例',
    '#### 5.1 A private personal AI across devices': '#### 5.1 跨设备的私密个人AI',
    '#### 5.2 A family or friends mesh': '#### 5.2 家庭或朋友网络',
    '#### 5.3 Trusted research and knowledge exchange': '#### 5.3 可信研究和知识交流',
    '#### 5.4 A small-team Agent Network': '#### 5.4 小型团队智能体网络',
    '#### 5.5 Multi-agent planning and report generation': '#### 5.5 多智能体规划和报告生成',
    '#### 5.6 OpenClaw with trusted mesh contacts': '#### 5.6 与可信网络联系人一起使用 OpenClaw',
    '#### 5.7 HomeClaw as an external EnvoyMesh agent': '#### 5.7 将 HomeClaw 作为外部 EnvoyMesh 智能体',
    '#### 5.8 Hermes as an external EnvoyMesh agent': '#### 5.8 将 Hermes 作为外部 EnvoyMesh 智能体',
    '#### 5.9 OpenHuman as an external EnvoyMesh agent': '#### 5.9 将 OpenHuman 作为外部 EnvoyMesh 智能体',
    '#### 5.10 Claude Desktop using EnvoyMesh through MCP': '#### 5.10 通过 MCP 使用 EnvoyMesh 的 Claude Desktop',
    '#### 5.11 External A2A clients delegating tasks': '#### 5.11 委托任务的外部 A2A 客户端',
    '#### 5.12 A self-hosted relay fleet': '#### 5.12 自托管中继集群',
    '### 6. Product and Protocol Comparisons': '### 6. 产品和协议比较',
    '#### 6.1 EnvoyMesh and centralized messengers': '#### 6.1 EnvoyMesh 与集中式信使',
    '#### 6.2 EnvoyMesh and cloud AI assistants': '#### 6.2 EnvoyMesh 与云AI助手',
    '#### 6.3 EnvoyMesh and standalone OpenClaw': '#### 6.3 EnvoyMesh 与独立 OpenClaw',
    '#### 6.4 EnvoyMesh and external agent runtimes': '#### 6.4 EnvoyMesh 与外部智能体运行时',
    '#### 6.5 EnvoyMesh and MCP': '#### 6.5 EnvoyMesh 与 MCP',
    '#### 6.6 EnvoyMesh and A2A': '#### 6.6 EnvoyMesh 与 A2A',
    '#### 6.7 EnvoyMesh native Agent Network versus public marketplaces': '#### 6.7 EnvoyMesh 原生智能体网络与公共市场',
    '#### 6.8 Native protocols versus interoperability bridges': '#### 6.8 原生协议与互操作性桥接',
    '## Part II — Install and Get Started': '## 第二部分 — 安装和入门',
    '### 7. Choose Your Setup': '### 7. 选择您的设置',
    '#### 7.1 Desktop only': '#### 7.1 仅桌面',
    '#### 7.2 Desktop with EnvoyGo mobile access': '#### 7.2 桌面与 EnvoyGo 移动访问',
    '#### 7.3 Desktop with the bundled EnvoyAI agent': '#### 7.3 桌面与捆绑的 EnvoyAI 智能体',
    '#### 7.4 Desktop with an external agent': '#### 7.4 桌面与外部智能体',
    '#### 7.5 Desktop with local or remote models': '#### 7.5 桌面与本地或远程模型',
    '#### 7.6 Personal relay or community relay': '#### 7.6 个人中继或社区中继',
    '#### 7.7 Small-team and organization deployments': '#### 7.7 小型团队和组织部署',
    '#### 7.8 Recommended first-time setup': '#### 7.8 推荐的首次设置',
    '### 8. Install EnvoyMesh': '### 8. 安装 EnvoyMesh',
    '#### 8.1 System requirements': '#### 8.1 系统要求',
    '#### 8.2 Install on macOS': '#### 8.2 在 macOS 上安装',
    '#### 8.3 Install on Windows': '#### 8.3 在 Windows 上安装',
    '#### 8.4 Install EnvoyGo on iOS': '#### 8.4 在 iOS 上安装 EnvoyGo',
    '#### 8.5 Install EnvoyGo on Android': '#### 8.5 在 Android 上安装 EnvoyGo',
    '#### 8.6 Install from source': '#### 8.6 从源代码安装',
    '#### 8.7 Verify the installation': '#### 8.7 验证安装',
    '#### 8.8 Application data locations': '#### 8.8 应用数据位置',
    '#### 8.9 Update EnvoyMesh': '#### 8.9 更新 EnvoyMesh',
    '#### 8.10 Uninstall without losing identity or data': '#### 8.10 卸载而不丢失身份或数据',
    '### 9. Platform and Package Differences': '### 9. 平台和软件包差异',
    '#### 9.1 Desktop and mobile feature comparison': '#### 9.1 桌面和移动功能比较',
    '#### 9.2 macOS packaging': '#### 9.2 macOS 打包',
    '#### 9.3 Windows packaging': '#### 9.3 Windows 打包',
    '#### 9.4 OpenClaw extensions bundled on macOS': '#### 9.4 macOS 上捆绑的 OpenClaw 扩展',
    '#### 9.5 Essential OpenClaw extension selection on Windows': '#### 9.5 Windows 上的基本 OpenClaw 扩展选择',
    '#### 9.6 Full and slim desktop bundles': '#### 9.6 完整和精简桌面捆绑包',
    '#### 9.7 Optional IPFS sidecars': '#### 9.7 可选的 IPFS 附属组件',
    '#### 9.8 Features requiring a home node': '#### 9.8 需要家庭节点的功能',
    '#### 9.9 Features available as an EnvoyGo mobile mirror': '#### 9.9 作为 EnvoyGo 移动镜像可用的功能',
    '#### 9.10 Legacy mobile experiments and current product boundaries': '#### 9.10 遗留移动实验和当前产品边界',
    '### 10. Create Your Identity': '### 10. 创建您的身份',
    '#### 10.1 What your EnvoyMesh identity represents': '#### 10.1 EnvoyMesh 身份代表什么',
    '#### 10.2 Create an owner identity': '#### 10.2 创建所有者身份',
    '#### 10.3 Create your first device identity': '#### 10.3 创建您的第一个设备身份',
    '#### 10.4 Create or activate your agent identity': '#### 10.4 创建或激活您的智能体身份',
    '#### 10.5 Set your display profile': '#### 10.5 设置您的显示资料',
    '#### 10.6 Understand your DID': '#### 10.6 理解您的 DID',
    '#### 10.7 Protect your cryptographic keys': '#### 10.7 保护您的加密密钥',
    '#### 10.8 Back up identity and recovery data': '#### 10.8 备份身份和恢复数据',
    '#### 10.9 Add another device': '#### 10.9 添加另一台设备',
    '#### 10.10 Revoke a lost or compromised device': '#### 10.10 吊销丢失或受损的设备',
    '### 11. Tour the Application': '### 11. 应用程序导览',
    '#### 11.1 Home and node status': '#### 11.1 首页和节点状态',
    '#### 11.2 Conversations': '#### 11.2 对话',
    '#### 11.3 Contacts and discovery': '#### 11.3 联系人和发现',
    '#### 11.4 Groups': '#### 11.4 群组',
    '#### 11.5 Knowledge Base and Library': '#### 11.5 知识库和库',
    '#### 11.6 Browser': '#### 11.6 浏览器',
    '#### 11.7 Team jobs': '#### 11.7 团队任务',
    '#### 11.8 Terminals': '#### 11.8 终端',
    '#### 11.9 Approvals and activity': '#### 11.9 审批和活动',
    '#### 11.10 Profile': '#### 11.10 资料',
    '#### 11.11 Settings': '#### 11.11 设置',
    '#### 11.12 Connection and agent status indicators': '#### 11.12 连接和智能体状态指示器',
    '### 12. Connect Your First Contact': '### 12. 连接您的第一个联系人',
    '#### 12.1 What pairing and bonding do': '#### 12.1 配对和绑定的作用',
    '#### 12.2 Pair with a QR code': '#### 12.2 使用二维码配对',
    '#### 12.3 Pair with an invitation link': '#### 12.3 使用邀请链接配对',
    '#### 12.4 Pair on a local network': '#### 12.4 在本地网络上配对',
    '#### 12.5 Verify identity information': '#### 12.5 验证身份信息',
    '#### 12.6 Choose an appropriate trust level': '#### 12.6 选择适当的信任等级',
    '#### 12.7 Accept a bond request': '#### 12.7 接受绑定请求',
    '#### 12.8 Send the first message': '#### 12.8 发送第一条消息',
    '#### 12.9 Confirm direct or relay-assisted delivery': '#### 12.9 确认直接或中继辅助传递',
    '#### 12.10 Troubleshoot pairing': '#### 12.10 配对故障排除',
    '#### 12.11 Bundled sponsor contact': '#### 12.11 捆绑的赞助联系人',
    '### 13. Connect EnvoyGo': '### 13. 连接 EnvoyGo',
    '#### 13.1 How EnvoyGo works with a home node': '#### 13.1 EnvoyGo 如何与家庭节点配合工作',
    '#### 13.2 Pair the mobile app': '#### 13.2 配对移动应用',
    '#### 13.3 Confirm the home connection': '#### 13.3 确认家庭连接',
    '#### 13.4 Use chat and contacts': '#### 13.4 使用聊天和联系人',
    '#### 13.5 Use remote terminals': '#### 13.5 使用远程终端',
    '#### 13.6 View Team jobs': '#### 13.6 查看团队任务',
    '#### 13.7 Browse mesh content': '#### 13.7 浏览网络内容',
    '#### 13.8 Receive notifications': '#### 13.8 接收通知',
    '#### 13.9 Make and receive voice calls': '#### 13.9 拨打和接听语音通话',
    '#### 13.10 Revoke a lost phone': '#### 13.10 吊销丢失的手机',
    '#### 13.11 Current mobile limitations': '#### 13.11 当前移动限制',
    '### 14. First-Day Tutorials': '### 14. 首日教程',
    '#### 14.1 Send a private message': '#### 14.1 发送私密消息',
    '#### 14.2 Create a group conversation': '#### 14.2 创建群组对话',
    '#### 14.3 Send an audio message': '#### 14.3 发送语音消息',
    '#### 14.4 Make a voice call': '#### 14.4 进行语音通话',
    '#### 14.5 Share a file': '#### 14.5 共享文件',
    '#### 14.6 Ask EnvoyAI a question': '#### 14.6 向 EnvoyAI 提问',
    '#### 14.7 Add knowledge to your Library': '#### 14.7 向库添加知识',
    '#### 14.8 Search your Vault': '#### 14.8 搜索您的保险库',
    '#### 14.9 Ask a bonded agent for knowledge': '#### 14.9 向绑定的智能体询问知识',
    '#### 14.10 Approve a sensitive action': '#### 14.10 批准敏感操作',
    '#### 14.11 Start a simple Team job': '#### 14.11 启动简单的团队任务',
    '#### 14.12 Connect an external agent': '#### 14.12 连接外部智能体',
    '## Part III — People, Profiles, and Conversations': '## 第三部分 — 人员、资料和对话',
    '### 15. Contacts and Bonds': '### 15. 联系人和绑定',
    '#### 15.1 View and search contacts': '#### 15.1 查看和搜索联系人',
    '#### 15.2 Understand contact identity': '#### 15.2 理解联系人身份',
    '#### 15.3 Contact profiles and photos': '#### 15.3 联系人资料和照片',
    '#### 15.4 Online, offline, and connection states': '#### 15.4 在线、离线和连接状态',
    '#### 15.5 Direct, referred, public, and blocked trust': '#### 15.5 直接、推荐、公开和阻止信任',
    '#### 15.6 Change a contact’s trust level': '#### 15.6 更改联系人的信任等级',
    '#### 15.7 Refer or introduce a contact': '#### 15.7 推荐或介绍联系人',
    '#### 15.8 Mute, block, or remove a contact': '#### 15.8 静音、阻止或移除联系人',
    '#### 15.9 Restore a connection': '#### 15.9 恢复连接',
    '#### 15.10 Contact privacy and disclosure settings': '#### 15.10 联系人隐私和披露设置',
    '### 16. Private Messaging': '### 16. 私密消息',
    '#### 16.1 Start a conversation': '#### 16.1 开始对话',
    '#### 16.2 Human-to-human messages': '#### 16.2 人与人消息',
    '#### 16.3 Human-to-agent messages': '#### 16.3 人与智能体消息',
    '#### 16.4 Replies and conversation continuity': '#### 16.4 回复和对话连续性',
    '#### 16.5 Message delivery states': '#### 16.5 消息传递状态',
    '#### 16.6 Offline behavior and retries': '#### 16.6 离线行为和重试',
    '#### 16.7 Search conversation history': '#### 16.7 搜索对话历史',
    '#### 16.8 Draft assistance': '#### 16.8 草稿辅助',
    '#### 16.9 Manage conversation data': '#### 16.9 管理对话数据',
    '#### 16.10 Message privacy and security': '#### 16.10 消息隐私和安全',
    '### 17. Group Conversations': '### 17. 群组对话',
    '#### 17.1 Create a group': '#### 17.1 创建群组',
    '#### 17.2 Invite members': '#### 17.2 邀请成员',
    '#### 17.3 Send group messages': '#### 17.3 发送群组消息',
    '#### 17.4 Manage membership': '#### 17.4 管理成员资格',
    '#### 17.5 Leave a group': '#### 17.5 离开群组',
    '#### 17.6 Group trust boundaries': '#### 17.6 群组信任边界',
    '#### 17.7 Group delivery and offline members': '#### 17.7 群组传递和离线成员',
    '#### 17.8 Group troubleshooting': '#### 17.8 群组故障排除',
    '### 18. Audio and Voice Calls': '### 18. 音频和语音通话',
    '#### 18.1 Record and send an audio message': '#### 18.1 录制和发送语音消息',
    '#### 18.2 Play and manage audio attachments': '#### 18.2 播放和管理音频附件',
    '#### 18.3 Start a voice call': '#### 18.3 开始语音通话',
}

SENTENCE_TRANSLATIONS = {
    'This guide reflects the EnvoyMesh 0.1.0 repository state at the revision date.': '本指南反映了修订日期时 EnvoyMesh 0.1.0 仓库的状态。',
    'It is written for end users, not as a content-outline stub.': '它是为最终用户编写的，而不是作为内容大纲的存根。',
    'Feature status can differ by platform and deployment—verify each Beta or Experimental capability in your build (release notes, Settings labels, and Appendix J) before relying on it in production.': '功能状态可能因平台和部署而异——在生产环境中依赖之前，请在您的构建中验证每个 Beta 或实验性功能（发行说明、设置标签和附录 J）。',
    'Parts I–XIV explain the product for end users and operators.': '第一至第十四部分为最终用户和操作员解释产品。',
    'Part XV is for website editors and content operators and is optional for end users.': '第十五部分面向网站编辑和内容操作员，对最终用户是可选的。',
    'Task lifecycle names such as *Created* / *Task planned* / *Running* are EnvoyMesh states, not product **Planned** / **Available** status labels.': '任务生命周期名称，如 *已创建* / *任务计划中* / *运行中* 是 EnvoyMesh 状态，不是产品的 **计划中** / **可用** 状态标签。',
    '**Mobile** in this guide means **EnvoyGo** (thin client paired to a home node), unless a section explicitly discusses legacy mobile experiments.': '本指南中的 **移动** 指的是 **EnvoyGo**（配对到家庭节点的瘦客户端），除非某个部分明确讨论遗留的移动实验。',
    '**Available** — implemented and intended for current use.': '**可用** — 已实现并打算当前使用。',
    '**Beta** — implemented, but still receiving validation or product polish.': '**Beta** — 已实现，但仍在接受验证或产品打磨。',
    '**Experimental** — usable for evaluation; behavior or interfaces may change.': '**实验性** — 可用于评估；行为或接口可能会更改。',
    '**Compatibility preset** — EnvoyMesh includes configuration for the integration, while part of the integration is maintained by another project.': '**兼容性预设** — EnvoyMesh 包含集成配置，而集成的一部分由另一个项目维护。',
    '**Planned** — designed or documented, but not currently available as a complete product feature.': '**计划中** — 已设计或文档化，但当前不可用作为完整的产品功能。',
    '**Parked** — intentionally deferred without a committed release date.': '**暂停** — 有意推迟，没有确定的发布日期。',
    '**Desktop** — available through the EnvoyMesh desktop application or home node.': '**桌面** — 可通过 EnvoyMesh 桌面应用或家庭节点使用。',
    '**Mobile** — available in EnvoyGo, the current EnvoyMesh mobile product (home-paired thin client).': '**移动** — 在 EnvoyGo 中可用，这是当前的 EnvoyMesh 移动产品（家庭配对瘦客户端）。',
    '**Operator** — intended for node, relay, or fleet administrators.': '**操作员** — 面向节点、中继或集群管理员。',
    '**EnvoyAI / OpenClaw** is the richer bundled agent integration included with EnvoyMesh.': '**EnvoyAI / OpenClaw** 是 EnvoyMesh 中包含的更丰富的捆绑智能体集成。',
    '**HomeClaw** and **Hermes** are built-in external-agent compatibility presets.': '**HomeClaw** 和 **Hermes** 是内置的外部智能体兼容性预设。',
    '**OpenHuman** is a built-in compatibility preset that is disabled by default.': '**OpenHuman** 是默认禁用的内置兼容性预设。',
    'Agent-side code for HomeClaw, Hermes, and OpenHuman is maintained by their respective projects; EnvoyMesh provides the bridge, presets, policy boundary, and mesh tools.': 'HomeClaw、Hermes 和 OpenHuman 的智能体端代码由各自的项目维护；EnvoyMesh 提供桥接、预设、策略边界和网络工具。',
    '**Agent Network** means bonded people allowing their opted-in local agents to collaborate. It is not a public agent marketplace.': '**智能体网络** 指的是已绑定的用户允许其选择加入的本地智能体进行协作。它不是公共智能体市场。',
    '**Team jobs** is the user-facing name for multi-agent collaboration. Source code and older documentation may call these workflows **chains**.': '**团队任务** 是多智能体协作的用户面向名称。源代码和旧文档可能将这些工作流称为 **链**。',
    '**EnvoyGo** is the current mobile product: a thin client that pairs to a home EnvoyMesh node.': '**EnvoyGo** 是当前的移动产品：一个配对到家庭 EnvoyMesh 节点的瘦客户端。',
    'The earlier Capacitor mobile tree (in-process full node) is a legacy experiment and is not the primary mobile application.': '早期的 Capacitor 移动树（进程内完整节点）是一个遗留实验，不是主要的移动应用。',
    'Running EnvoyGo itself as a full mesh node is parked (Appendix J.6).': '将 EnvoyGo 本身作为完整网络节点运行已暂停（附录 J.6）。',
    'EnvoyMesh connects people and AI agents through a private mesh rather than a central account service.': 'EnvoyMesh 通过私有网络连接人类和 AI 智能体，而不是中央账户服务。',
    'Each participant keeps a local identity, chooses trusted contacts (bonded at one of four user-selectable trust tiers — blocked, public, referred, or direct; `self` is the implicit tier for your own owner, devices, and agents), and decides which agents, tools, and information may cross those relationships.': '每个参与者保留本地身份，选择可信联系人（绑定在四个用户可选的信任等级之一 — 阻止、公开、推荐或直接；`self` 是您自己的所有者、设备和智能体的隐式等级），并决定哪些智能体、工具和信息可以跨越这些关系。',
    'The home node stores identity, policy, conversations, tasks, and knowledge locally.': '家庭节点在本地存储身份、策略、对话、任务和知识。',
    'Peer-to-peer transport is preferred, so routine communication does not depend on a hosted application database.': '优先使用点对点传输，因此日常通信不依赖于托管的应用数据库。',
    'You create cryptographic identities instead of registering a global username and password.': '您创建加密身份，而不是注册全球用户名和密码。',
    'Public relays may help peers find and reach each other, but they are not an account authority.': '公共中继可以帮助对等节点找到并联系彼此，但它们不是账户权威。',
    'Owner keys establish control, bonds record relationships, and sensitivity labels protect data.': '所有者密钥建立控制权，绑定记录关系，敏感度标签保护数据。',
    'Backups therefore matter: losing the only copy of an owner key can mean losing continuity of that identity.': '因此备份很重要：丢失所有者密钥的唯一副本可能意味着该身份的连续性丢失。',
    'EnvoyMesh first attempts a direct peer path.': 'EnvoyMesh 首先尝试直接对等节点路径。',
    'When NAT, firewalls, or mobility prevent that path, an optional relay supplies rendezvous and forwarding without becoming the application brain.': '当 NAT、防火墙或移动性阻止该路径时，可选的中继提供会合和转发功能，而不会成为应用程序的核心。',
    'EnvoyAI is the bundled OpenClaw-based assistant.': 'EnvoyAI 是基于 OpenClaw 的捆绑助手。',
    'A separate bridge can connect HomeClaw, Hermes, OpenHuman, or a custom HTTP agent without giving that external process raw P2P keys.': '一个单独的桥接可以连接 HomeClaw、Hermes、OpenHuman 或自定义 HTTP 智能体，而不向该外部进程提供原始 P2P 密钥。',
    'Agent Network lets bonded owners opt their local agents into Team jobs.': '智能体网络允许已绑定的所有者将其本地智能体选择加入团队任务。',
    'The requesting node plans work, eligible workers execute locally, and the orchestrator combines attributed results.': '请求节点计划工作，合格的工作节点在本地执行，协调者合并带有归属信息的结果。',
    'Native signed EnvoyMesh envelopes remain the internal protocol.': '原生签名的 EnvoyMesh 信封仍然是内部协议。',
    'MCP exposes tools to compatible applications, while A2A publishes agent discovery and task interfaces at the network edge.': 'MCP 向兼容应用暴露工具，而 A2A 在网络边缘发布智能体发现和任务接口。',
    'Available areas include messaging, groups, audio, voice calls, files, profiles, personal AI, knowledge and RAG, external-agent bridges, Team jobs, terminals, Browser, relays, MCP, and A2A.': '可用领域包括消息传递、群组、音频、语音通话、文件、资料、个人 AI、知识和 RAG、外部智能体桥接、团队任务、终端、浏览器、中继、MCP 和 A2A。',
    'Some capabilities remain platform-specific or deferred.': '某些功能仍然是平台特定的或已推迟。',
    'In particular, video calls, broad anonymous worker recruitment, full-node EnvoyGo operation, global reputation, commerce, Filecoin persistence, and a complete hierarchical relay graph are not current general features.': '特别是，视频通话、广泛的匿名工作节点招募、完整节点的 EnvoyGo 操作、全球声誉、商业、Filecoin 持久性和完整的分层中继图目前不是通用功能。',
    'EnvoyMesh treats messaging as signed peer traffic rather than rows in a hosted database.': 'EnvoyMesh 将消息传递视为签名的对等节点流量，而不是托管数据库中的行。',
    'You choose who appears in your contact list, and conversations stay on devices you control unless you explicitly share outward.': '您选择谁出现在您的联系人列表中，对话保留在您控制的设备上，除非您明确向外共享。',
    'This differs from centralized messengers that can change terms, scan content, or freeze accounts without your keys.': '这与集中式信使不同，后者可以在没有您的密钥的情况下更改条款、扫描内容或冻结账户。',
    'Your owner identity is an Ed25519 keypair, not a username registered by a vendor.': '您的所有者身份是 Ed25519 密钥对，而不是供应商注册的用户名。',
    'Devices and agents derive from that owner with signed certificates and mandates, so you can prove continuity across laptops, desktops, and paired phones.': '设备和智能体通过签名证书和授权从该所有者派生，因此您可以在笔记本电脑、台式机和配对手机之间证明连续性。',
    'Losing the only copy of an owner key can end that identity history, so backup and recovery planning matter from day one.': '丢失所有者密钥的唯一副本可能会结束该身份的历史，因此备份和恢复计划从第一天就很重要。',
    'EnvoyAI and external agents run on your home node under bond policy, mandate limits, and optional human approvals.': 'EnvoyAI 和外部智能体在您的家庭节点上运行，受绑定策略、授权限制和可选的人工审批约束。',
    'You decide which models, tools, and contacts an agent may use instead of accepting a vendor default automation scope.': '您决定智能体可以使用哪些模型、工具和联系人，而不是接受供应商的默认自动化范围。',
    'Remote model providers receive only prompts the node approves after its semantic firewall and policy checks.': '远程模型提供商仅接收节点在其语义防火墙和策略检查后批准的提示。',
    'Notes and files live in your Vault, appear in the Library UI, and can be shared with sensitivity labels that the Bonds engine enforces.': '笔记和文件存储在您的保险库中，出现在库界面中，并可以通过绑定引擎强制执行的敏感度标签进行共享。',
    'Bonded contacts can query your public or friends-tier material through `knowledge.query`, while strangers see only the public sub-graph and are rate-limited.': '已绑定的联系人可以通过 `knowledge.query` 查询您的公开或朋友等级的材料，而陌生人只能看到公开子图并受到限速。',
    'Publishing for browsing uses separate web-content paths and visibility rules described in Part V.': '发布以供浏览使用单独的网络内容路径以及第五部分中描述的可见性规则。',
    'Task delegation uses owner-signed mandates that cap cost, sensitivity, allowed actions, and expiry.': '任务委托使用所有者签名的授权，这些授权限制成本、敏感度、允许的操作和过期时间。',
    'An agent cannot silently exceed those bounds; risky steps can require explicit approval before execution.': '智能体不能静默地超出这些限制；有风险的步骤可能需要在执行前获得明确批准。',
    'This makes autonomous work legible rather than a black box running on someone else servers.': '这使自主工作清晰可读，而不是在其他人的服务器上运行的黑盒。',
    'Agent Network is opt-in collaboration among bonded owners, not an anonymous worker marketplace.': '智能体网络是已绑定所有者之间的选择加入协作，而不是匿名工作者市场。',
    'Team jobs let your local agent plan work and call workers you already trust, with attributed results returned to the orchestrator.': '团队任务允许您的本地智能体计划工作并调用您已经信任的工作者，带有归属信息的结果返回到协调者。',
    'You stay in control of which contacts agents may participate.': '您可以控制哪些联系人的智能体可以参与。',
    'EnvoyMesh supports local inference, configured remote providers, and external HTTP agents such as HomeClaw or Hermes through a single bridge at a time.': 'EnvoyMesh 支持本地推理、配置的远程提供商以及通过单个桥接同时支持的 HomeClaw 或 Hermes 等外部 HTTP 智能体。',
    'The node signs mesh traffic on the agent behalf without handing over Ed25519 keys.': '节点代表智能体签署网络流量，而不交出 Ed25519 密钥。',
    'Mix providers to balance privacy, latency, and capability without locking into one vendor stack.': '混合提供商以平衡隐私、延迟和能力，而不锁定到一个供应商栈。',
    'Operations append JSONL audit events with correlation IDs that stitch multi-step flows together.': '操作会附加 JSONL 审计事件，带有关联 ID，这些 ID 将多步骤流程拼接在一起。',
    'You can review what an agent attempted, what policy allowed or denied, and which peer participated.': '您可以查看智能体尝试了什么、策略允许或拒绝了什么以及哪个对等节点参与了。',
    'This audit trail complements chat history when diagnosing automation or sharing disputes.': '此审计跟踪在诊断自动化或共享争议时补充聊天历史。',
    'EnvoyMesh fits when you want cryptographic identity, explicit trust tiers, local-first storage, and agent tooling under your policy.': '当您需要加密身份、明确的信任等级、优先本地存储以及在您的策略控制下的智能体工具时，EnvoyMesh 是合适的选择。',
    'It works well for small trusted groups, personal AI with mesh reach, and teams that need verifiable messaging plus delegated tasks.': '它适用于小型可信群体、具有网络覆盖范围的个人 AI 以及需要可验证消息传递和委托任务的团队。',
    'Start with one home node and a few bonded contacts before expanding relays or Agent Network membership.': '在扩展中继或智能体网络成员资格之前，从一个家庭节点和几个已绑定的联系人开始。',
    'A global consumer messenger with effortless signup, massive groups, and vendor-managed moderation may serve you better than running a home node.': '一个具有轻松注册、大规模群组和供应商管理的审核功能的全球消费者信使可能比运行家庭节点更适合您。',
    'Likewise, if you only need a single cloud chatbot with no peer relationships or local vault, a hosted assistant is simpler.': '同样，如果您只需要一个没有对等关系或本地保险库的单一云聊天机器人，托管助手更简单。',
    'EnvoyMesh rewards operators willing to own keys, backups, and trust decisions.': 'EnvoyMesh 奖励愿意拥有密钥、备份和信任决策的操作员。',
    'Add contacts through introductions, QR pairing, or relay-assisted discovery once you verify their public key fingerprint.': '验证他们的公钥指纹后，通过介绍、二维码配对或中继辅助发现添加联系人。',
    'Bonds record trust tiers—blocked, public, referred, or direct—that gate what each peer may request.': '绑定记录信任等级——阻止、公开、推荐或直接——这些等级控制每个对等节点可以请求什么。',
    'You can upgrade or downgrade trust as relationships change without migrating to a new account.': '您可以随着关系变化升级或降级信任，而无需迁移到新账户。',
    'Send one-to-one chat as signed envelopes with human-to-human role policy enforced by the protocol.': '发送一对一聊天，作为签名信封，带有协议强制执行的人与人角色策略。',
    'Messages prefer direct libp2p paths and fall back to circuit relay when NAT blocks a straight connection.': '消息优先使用直接 libp2p 路径，当 NAT 阻止直接连接时回退到电路中继。',
    'Read receipts and delivery behavior follow the settings in Social or EnvoyGo once paired to your home node.': '配对到您的家庭节点后，阅读回执和传递行为遵循在 Social 或 EnvoyGo 中的设置。',
    'Create group threads that include multiple bonded contacts with the same signature and policy guarantees as direct chat.': '创建包含多个已绑定联系人的群组线程，具有与直接聊天相同的签名和策略保证。',
    'Group membership and naming are local-first constructs coordinated through your node.': '群组成员身份和命名是通过您的节点协调的本地优先结构。',
    'Use groups for family, project, or research circles where everyone already shares an explicit trust relationship.': '将群组用于家庭、项目或研究圈子，其中每个人已经共享明确的信任关系。',
    'Record short audio clips in chat or start voice calls when both sides support the feature and policy allows.': '在聊天中录制短音频片段，或在双方都支持该功能且策略允许时开始语音通话。',
    'Media flows over the same mesh transport as messages rather than through a separate proprietary calling backend.': '媒体通过与消息相同的网络传输，而不是通过单独的专有通话后端。',
    'Quality and availability depend on network paths and whether peers are reachable via direct or relayed connections.': '质量和可用性取决于网络路径以及对等节点是否可以通过直接或中继连接访问。',
    'Share files with contacts using signed data-transfer vouchers that land in vault inbox folders on the recipient side.': '使用签名的数据传输凭证与联系人共享文件，这些凭证在接收方端的保险库收件箱文件夹中着陆。',
    'Profile photos and avatars follow the same identity and storage model as other local assets.': '资料照片和头像遵循与其他本地资产相同的身份和存储模型。',
    'Recipients index received files under their own sensitivity rules.': '接收方根据自己的敏感度规则索引收到的文件。',
    'Chat with EnvoyAI (bundled OpenClaw) from Social desktop or through EnvoyGo when paired to a running home node.': '与 EnvoyAI（捆绑的 OpenClaw）聊天，从 Social 桌面或在配对到运行中的家庭节点时通过 EnvoyGo。',
    'The assistant can search your vault, message bonded contacts, and invoke allowed tools subject to mandates and approvals.': '助手可以搜索您的保险库、向已绑定的联系人发送消息，并根据授权和审批调用允许的工具。',
    'Enable or disable the bundled agent in Settings → AI according to your comfort with automation.': '在设置 → AI 中启用或禁用捆绑智能体，根据您对自动化的舒适度。',
    'Connect HomeClaw, Hermes, OpenHuman, or a custom HTTP agent through Settings → AI → Ext Agent when you prefer an external runtime over bundled EnvoyAI.': '通过设置 → AI → 外部智能体连接 HomeClaw、Hermes、OpenHuman 或自定义 HTTP 智能体，当您更喜欢外部运行时而不是捆绑的 EnvoyAI 时。',
    'EnvoyMesh translates mesh tools into the external agent message contract without exposing raw libp2p keys.': 'EnvoyMesh 将网络工具转换为外部智能体的消息契约，而不暴露原始 libp2p 密钥。',
    'Only one external bridge runs at a time; verify you trust the local endpoint before enabling it.': '一次只运行一个外部桥接；在启用之前验证您信任本地端点。',
    'Search your vault locally from the Library tab or ask EnvoyAI to retrieve chunks through the RAG pipeline indexed on save.': '从库选项卡本地搜索您的保险库，或让 EnvoyAI 通过保存时索引的 RAG 管道检索块。',
    'Federated search can query bonded contacts syndicated knowledge within sensitivity ceilings you configure per contact.': '联合搜索可以在您为每个联系人配置的敏感度上限内查询已绑定联系人的联合知识。',
    'Public notes participate in the wider mesh through rate-limited `knowledge.query` for strangers.': '公开笔记通过对陌生人的限速 `knowledge.query` 参与更广泛的网络。',
    'Publish Markdown, images, and PDFs under `envoy://` URLs served from your home node web content directory.': '在 `envoy://` URL 下发布 Markdown、图像和 PDF，从您的家庭节点的网络内容目录提供服务。',
    'Bonded contacts—and, when visibility allows, wider mesh peers—open pages in the Social Browser or EnvoyGo Browser while paired to home.': '已绑定的联系人——以及在可见性允许时，更广泛的网络对等节点——在配对到家庭时在 Social 浏览器或 EnvoyGo 浏览器中打开页面。',
    'Pull-based `library.read` fetches bytes on demand; push notifications for feeds arrived in Phase 45E.': '基于拉取的 `library.read` 按需获取字节；订阅源的推送通知在阶段 45E 中推出。',
    'Send a task mandate to another owner agent when you need specialized work within signed bounds.': '当您需要在签名范围内进行专业工作时，向另一个所有者的智能体发送任务授权。',
    'Negotiation follows the task lifecycle from propose through accept, running, and result.': '协商遵循任务生命周期，从提议到接受、运行和结果。',
    'Human approval gates remain available for actions the mandate marks as sensitive.': '人工审批门仍然可用于授权标记为敏感的操作。',
    'Run Team jobs (multi-agent chains) across opted-in Agent Network members when bonded owners allow their agents to collaborate.': '当已绑定的所有者允许其智能体协作时，在选择加入的智能体网络成员上运行团队任务（多智能体链）。',
    'The requesting node plans steps, workers execute locally on their own hardware, and results return with attribution.': '请求节点计划步骤，工作节点在自己的硬件上本地执行，结果带有归属信息返回。',
    'This is suited to research summaries, split analysis, or coordinated reports—not open recruitment of anonymous workers.': '这适用于研究摘要、拆分分析或协调报告——而不是匿名工作者的公开招募。',
    'Expose selected mesh tools to MCP-compatible desktop apps such as Claude Desktop, or publish an A2A agent card for external task clients.': '向兼容 MCP 的桌面应用（如 Claude Desktop）暴露选定的网络工具，或为外部任务客户端发布 A2A 智能体卡片。',
    'MCP and A2A sit at the network edge; native signed envelopes remain the internal protocol.': 'MCP 和 A2A 位于网络边缘；原生签名信封仍然是内部协议。',
    'Configure bridges only after you understand which tools cross the boundary.': '只有在您了解哪些工具跨越边界后，才配置桥接。',
    'Open browser-based terminals in Social or EnvoyGo that attach to PTY sessions on your home node over WebSocket when you are paired or on desktop.': '在配对或在桌面上时，通过 WebSocket 在 Social 或 EnvoyGo 中打开基于浏览器的终端，这些终端连接到您的家庭节点上的 PTY 会话。',
    'Remote shell access inherits the same authentication and pairing model as other home RPC features.': '远程 shell 访问继承与其他家庭 RPC 功能相同的身份验证和配对模型。',
    'Treat terminal exposure as high privilege and restrict it to devices you control.': '将终端暴露视为高权限，并将其限制为您控制的设备。',
    'Run a private relay for your fleet or bootstrap against the community relay for casual testing.': '为您的集群运行私有中继，或针对社区中继进行引导以进行临时测试。',
    'Relays provide rendezvous and circuit forwarding—they do not store your messages, run models, or act as account servers.': '中继提供会合和电路转发——它们不存储您的消息、运行模型或充当账户服务器。',
    'Operators advertise listen addresses and may configure hierarchical relay graphs for larger deployments.': '操作员公布监听地址，并可以为更大的部署配置分层中继图。',
    'At a high level, your home node combines identity, policy, storage, models, and libp2p networking in one process.': '从高层次来看，您的家庭节点在一个进程中结合了身份、策略、存储、模型和 libp2p 网络。',
    'Social desktop and paired EnvoyGo are thin clients that call JSON-RPC on that node.': 'Social 桌面和配对的 EnvoyGo 是调用该节点上的 JSON-RPC 的瘦客户端。',
    'Inbound traffic passes through guards for size, signature, replay, and bond decisions before any model or vault access occurs.': '入站流量在任何模型或保险库访问发生之前，先经过大小、签名、重放和绑定决策的防护。',
    'The owner key is the long-lived human root; devices receive owner-signed certificates; agents receive mandates linking them to that owner.': '所有者密钥是长期的人类根；设备接收所有者签名的证书；智能体接收将它们链接到该所有者的授权。',
    'Runtime peer IDs sign individual envelopes and may rotate with keys while preserving trust links.': '运行时对等 ID 签署单个信封，并可能在保留信任链接的同时随密钥轮换。',
    'Understanding this stack helps you reason about backups, pairing, and agent authorization.': '理解这个堆栈有助于您推理备份、配对和智能体授权。',
    'Contacts map to bond records with tiers that determine which intents and sensitivity levels are allowed.': '联系人映射到具有信任等级的绑定记录，这些等级确定允许哪些意图和敏感度级别。',
    'Public strangers may ping or request bonds; referred contacts gain broader query access; direct bonds unlock friends-tier sharing.': '公开陌生人可以 ping 或请求绑定；推荐联系人获得更广泛的查询访问；直接绑定解锁朋友等级分享。',
    'Policy evaluation is deterministic and logged for audit.': '策略评估是确定性的，并记录用于审计。',
    'Every envelope carries an Ed25519 signature over canonical JSON so recipients verify sender identity before acting on content.': '每个信封都带有 Ed25519 签名，覆盖规范 JSON，以便接收者在对内容采取行动之前验证发送者身份。',
    'Role fields enforce human-to-human chat versus agent-to-agent task traffic at the schema level.': '角色字段在架构层面强制执行人与人聊天与智能体与智能体任务流量。',
    'Tampered or replayed messages fail inbound guards.': '被篡改或重放的消息在入站防护中失败。',
    'Bundled EnvoyAI runs in-process with mesh tools, while external agents connect through an HTTP bridge that never receives your private signing keys.': '捆绑的 EnvoyAI 进程内运行并带有网络工具，而外部智能体通过从不接收您的私钥签名的 HTTP 桥接连接。',
    'The bridge forwards allowed tool calls and translates responses into mesh envelopes.': '桥接转发允许的工具调用，并将响应转换为网络信封。',
    'Choose one primary agent surface to avoid conflicting automation.': '选择一个主要的智能体界面以避免冲突的自动化。',
    'The Vault stores files on disk under path-safe rules; the Library is the UI and metadata layer for notes, imports, and published items; RAG indexes vault chunks for retrieval during chat.': '保险库在路径安全规则下将文件存储在磁盘上；库是笔记、导入和发布项目的 UI 和元数据层；RAG 索引保险库块以便在聊天期间检索。',
    'Sensitivity overrides live in `.envoy/sensitivity.json` per item, not per folder.': '敏感度覆盖每个项目存储在 `.envoy/sensitivity.json` 中，而不是每个文件夹。',
    'Web content for browsing lives under a separate `web/` directory mapped to `envoy://` paths.': '用于浏览的网络内容位于单独的 `web/` 目录下，映射到 `envoy://` 路径。',
    'Tasks progress through named lifecycle states with mandates defining authorized intent, cost ceilings, and termination policy.': '任务通过命名的生命周期状态进行，授权定义了授权意图、成本上限和终止策略。',
    'Owners can require approval before specific actions even when a mandate otherwise allows automation.': '所有者可以在特定操作之前要求批准，即使授权允许自动化。',
    'Cancel and heartbeat intents keep long-running work accountable.': '取消和心跳意图使长时间运行的工作保持可问责。',
    'Agent Network membership is mutual opt-in among bonded contacts who enable their agents for collaboration.': '智能体网络成员资格是已绑定联系人之间的双向选择加入，他们为协作启用了智能体。',
    'It is not a public marketplace listing anonymous workers.': '它不是列出匿名工作者的公共市场。',
    'Team jobs consume this membership graph when selecting eligible workers.': '团队任务在选择合格工作者时使用此成员资格图。',
    'Nodes attempt direct TCP or QUIC connections first, using mDNS on LAN and DHT discovery when configured.': '节点首先尝试直接 TCP 或 QUIC 连接，在局域网上使用 mDNS，在配置时使用 DHT 发现。',
    'When NAT blocks direct paths, circuit relay v2 reservations forward streams without decrypting application payloads.': '当 NAT 阻止直接路径时，电路中继 v2 保留转发流，而不解密应用载荷。',
    'You choose bootstrap relays; they assist connectivity rather than owning your identity.': '您选择引导中继；它们协助连接而不是拥有您的身份。',
    'Audit and journal JSONL files record intents, outcomes, latency, and correlation IDs for multi-hop flows.': '审计和日志 JSONL 文件记录意图、结果、延迟和多跳流的关联 ID。',
    'Operators can trace a Team job, knowledge query, or file transfer across peers using those IDs.': '操作员可以使用这些 ID 跨对等节点跟踪团队任务、知识查询或文件传输。',
    'Logs intentionally avoid storing raw sensitive payloads unless required for debugging policy.': '日志有意避免存储原始敏感载荷，除非需要用于调试策略。',
    'Run EnvoyAI on a desktop home node and reach it from Social locally or EnvoyGo when paired away from home.': '在桌面家庭节点上运行 EnvoyAI，并从本地 Social 或外出时通过 EnvoyGo 访问它。',
    'Your vault, models, and bonds stay on the computer you trust while the phone acts as a remote control.': '您的保险库、模型和绑定保留在您信任的计算机上，而手机充当遥控器。',
    'Back up owner keys and vault data so device loss does not strand your agent history.': '备份所有者密钥和保险库数据，以便设备丢失不会使您的智能体历史搁浅。',
    'Invite family or friends through introductions, establish direct bonds, and use group chat plus file sharing without a shared cloud account.': '通过介绍邀请家人或朋友，建立直接绑定，并使用群聊和文件共享，无需共享云账户。',
    'Each participant keeps their own node and data; sharing is explicit through messages, vouchers, and syndicated knowledge settings.': '每个参与者保留自己的节点和数据；共享通过消息、凭证和联合知识设置显式进行。',
    'Relays help when members are on different networks.': '当成员在不同网络上时，中继会有所帮助。',
    'Exchange research notes with public or friends sensitivity, query peers syndicated libraries, and save attributed results back to your vault through MCP write-back.': '以公开或朋友敏感度交换研究笔记，查询对等节点的联合库，并通过 MCP 写回将归属结果保存回您的保险库。',
    'Federated RAG respects per-contact ceilings so you never silently exfiltrate private material.': '联合 RAG 尊重每个联系人的上限，因此您永远不会静默泄露私人材料。',
    'Publish finished summaries as mesh pages when you want durable `envoy://` links.': '当您需要持久的 `envoy://` 链接时，将完成的摘要发布为网格页面。',
    'Enable Agent Network among a small team that already shares direct bonds and aligned mandates.': '在已经共享直接绑定和对齐授权的小型团队中启用智能体网络。',
    'Assign Team jobs for split research, code review assistance, or draft reports with each worker executing on local hardware.': '分配团队任务进行拆分研究、代码审查辅助或草稿报告，每个工作者在本地硬件上执行。',
    'Review audit trails to see which agent contributed each segment.': '查看审计跟踪以查看哪个智能体贡献了每个段。',
    'Plan a multi-step report where one agent outlines sections, workers gather evidence from local vaults, and the orchestrator merges attributed text.': '规划一个多步骤报告，其中一个智能体概述部分，工作者从本地保险库收集证据，协调者合并归属文本。',
    'Mandates cap cost and require approval before sending external email or spending credits.': '授权限制成本，并要求在发送外部电子邮件或花费积分之前获得批准。',
    'Results land in chat and can be saved as vault notes for later citation.': '结果出现在聊天中，并可以保存为保险库笔记以供日后引用。',
    'Keep OpenClaw as EnvoyAI on your node while using mesh tools to message bonded contacts and search syndicated knowledge.': '在您的节点上保持 OpenClaw 作为 EnvoyAI，同时使用网络工具向已绑定的联系人发送消息并搜索联合知识。',
    'OpenClaw never receives raw libp2p access; it calls `mesh.findKnowledge`, `mesh.sendMessage`, and related tools through the registry.': 'OpenClaw 永远不会接收原始 libp2p 访问；它通过注册表调用 `mesh.findKnowledge`、`mesh.sendMessage` 和相关工具。',
    'This pattern suits power users who want OpenClaw skills with trusted peer reach.': '这种模式适合想要 OpenClaw 技能并具有可信对等节点访问权限的高级用户。',
    'Point EnvoyMesh at a local HomeClaw HTTP endpoint so HomeClaw becomes the conversational surface while the node handles identity and mesh I/O.': '将 EnvoyMesh 指向本地 HomeClaw HTTP 端点，使 HomeClaw 成为对话表面，而节点处理身份和网格 I/O。',
    'HomeClaw own memory and plugins stay in its process; EnvoyMesh enforces bonds on outbound actions.': 'HomeClaw 自己的内存和插件保留在其进程中；EnvoyMesh 对出站操作强制执行绑定。',
    'Enable the preset only on machines where you already run and trust HomeClaw.': '仅在您已经运行并信任 HomeClaw 的机器上启用预设。',
    'Use Hermes when you prefer its Obsidian-style knowledge tooling alongside mesh messaging.': '当您喜欢其 Obsidian 风格的知识工具以及网格消息传递时，使用 Hermes。',
    'The bridge forwards Hermes responses and tool results through the same policy boundary as other external agents.': '桥接通过与其他外部智能体相同的策略边界转发 Hermes 响应和工具结果。',
    'Configure the default `http://127.0.0.1:8020/message` endpoint or your custom URL in Settings → AI.': '在设置 → AI 中配置默认的 `http://127.0.0.1:8020/message` 端点或您的自定义 URL。',
    'OpenHuman is available as a disabled-by-default compatibility preset for teams experimenting with that runtime.': 'OpenHuman 作为默认禁用的兼容性预设提供，适用于实验该运行时的团队。',
    'When enabled, it follows the same one-bridge-at-a-time rule and never receives signing keys.': '启用时，它遵循相同的一次一桥接规则，并且永远不会接收签名密钥。',
    'Treat it as optional until your organization validates OpenHuman local deployment model.': '在您的组织验证 OpenHuman 的本地部署模型之前，将其视为可选。',
    'Register EnvoyMesh as an MCP server in Claude Desktop to expose mesh search, contacts, and messaging tools to Anthropic client.': '在 Claude Desktop 中将 EnvoyMesh 注册为 MCP 服务器，以向 Anthropic 的客户端暴露网格搜索、联系人和消息传递工具。',
    'MCP crosses a desktop boundary—review which tools you enable and what data they can read from your vault.': 'MCP 跨越桌面边界——查看您启用哪些工具以及它们可以从您的保险库读取什么数据。',
    'The home node must be running for MCP sessions to succeed.': '家庭节点必须运行才能使 MCP 会话成功。',
    'Publish an A2A agent card from your node so external A2A clients can discover capabilities and delegate tasks through JSON-RPC proxies.': '从您的节点发布 A2A 智能体卡片，以便外部 A2A 客户端可以发现能力并通过 JSON-RPC 代理委托任务。',
    'Home tunnel and relay paths let remote clients reach a home node without exposing raw libp2p to the external runtime.': '家庭隧道和中继路径让远程客户端无需向外部运行时暴露原始 libp2p 即可访问家庭节点。',
    'Mandates and approvals still apply to delegated work.': '授权和审批仍然适用于委托工作。',
    'Deploy one or more relay binaries with advertised addresses for a family, lab, or organization that wants private bootstrap and circuit relay capacity.': '部署一个或多个中继二进制文件，带有公布的地址，用于家庭、实验室或组织，这些组织想要私有引导和电路中继容量。',
    'Relays stay lean: no LLM, no vault, no payload inspection beyond transport forwarding.': '中继保持精简：没有 LLM、没有保险库、除传输转发外没有载荷检查。',
    'Monitor relay audit snapshots when operating fleet infrastructure.': '操作集群基础设施时监控中继审计快照。',
    'Centralized messengers optimize for frictionless signup, phone-number identity, and vendor-operated moderation at scale.': '集中式信使优化无摩擦注册、电话号码身份以及大规模供应商运营的审核。',
    'EnvoyMesh trades that convenience for self-sovereign keys, explicit bonds, and local-first storage you operate.': 'EnvoyMesh 用这种便利换取自主主权密钥、明确的绑定以及您操作的本地优先存储。',
    'Choose messengers for mass reach; choose EnvoyMesh when trust boundaries and auditability matter more.': '选择信使以实现大规模覆盖；当信任边界和可审计性更重要时选择 EnvoyMesh。',
    'Cloud AI assistants run inference and memory on vendor infrastructure with account login and vendor policy.': '云 AI 助手在供应商基础设施上运行推理和内存，具有账户登录和供应商策略。',
    'EnvoyMesh keeps models, vault, and bonds on your node while optionally calling remote providers you configure.': 'EnvoyMesh 将模型、保险库和绑定保留在您的节点上，同时可选地调用您配置的远程提供商。',
    'You gain mesh reach and mandates instead of a single-vendor chat history silo.': '