import re

TERMS_TO_KEEP = {
    'EnvoyMesh', 'EnvoyGo', 'EnvoyAI', 'OpenClaw', 'HomeClaw', 'Hermes', 'OpenHuman',
    'Ed25519', 'libp2p', 'DID', 'MCP', 'A2A', 'RAG', 'IPFS', 'WebRTC', 'TURN', 'STUN',
    'JSON-RPC', 'WebSocket', 'HTTP', 'TCP', 'QUIC', 'mDNS', 'DHT', 'LAN', 'WAN', 'NAT',
    'API', 'CLI', 'QR', 'FCM', 'APNs', 'CallKit', 'VoIP', 'PTY', 'SDK', 'LLM', 'LiteLLM',
    'Ollama', 'Claude', 'Anthropic', 'OpenAI', 'Signal', 'AirDrop', 'Tauri', 'Flutter',
    'React', 'Node.js', 'TypeScript', 'Zod', 'SQLite', 'Helia', 'Kubo', 'Memex',
    'Phase 42I', 'Phase 45', 'Phase 45C', 'Phase 45E', 'Appendix J', 'Appendix K',
    'CHANGELOG.md', 'QuickStart.md', 'README.md', 'node-config.json', 'bridge-config.json',
    'bridge-identity.json', 'bundled-sponsor-friend.json', '.envoy/sensitivity.json',
    'envoy://', 'http://', 'https://', '/ip4/', '/tcp/', '/p2p/', '/p2p-circuit/',
    '@envoy', '@envoymesh/', 'mesh.', 'chat.', 'task.', 'knowledge.', 'library.',
    'vault/', 'notes/', 'documents/', 'inbox/', 'shared_vault/', 'web/', 'digests/',
    'npm', 'node', 'git', 'npm run', 'node-config', 'bridge-config', 'vault-search',
    'connectivity-status', 'relay-status', 'morning-report', 'listPendingApprovals',
    'openclawEnabled', 'bridgeEnabled', 'autonomousKillSwitch', 'openclaw-only',
    'both', 'ext-only', 'off', 'ollama', 'openai-compatible', 'anthropic-compatible',
    'litellm', 'mock', 'trustModeEnabled', 'socialProxyEnabled', 'offlineAgentEnabled',
    'friendAutopilotEnabled', 'onlineAssistantEnabled', 'autoReplyLimits', 'statusMode',
    'aiAccessLevel', 'knowledgeAccess', 'syndicationMaxSensitivity', 'disclosure',
    'debugPrefixInMessageText', 'aiSettings', 'defaultModeForNewContacts', 'manual',
    'assistant', 'auto', 'none', 'assistant_only', 'full', 'public', 'friends',
    'trusted', 'private', 'blocked', 'direct', 'referred', 'stranger', 'owner', 'device',
    'agent', 'peer', 'bond', 'mandate', 'vault', 'library', 'browser', 'terminal',
    'session', 'approval', 'audit', 'digest', 'trigger', 'profile', 'contact',
    'conversation', 'chat', 'group', 'message', 'voice', 'call', 'audio', 'video',
    'file', 'photo', 'gallery', 'share', 'transfer', 'search', 'discovery', 'network',
    'mesh', 'relay', 'bootstrap', 'circuit', 'rendezvous', 'forwarding', 'connectivity',
    'reachability', 'transport', 'encryption', 'signature', 'verification', 'proof',
    'fingerprint', 'hash', 'payload', 'envelope', 'intent', 'correlation', 'latency',
    'timeout', 'policy', 'sensitivity', 'trust', 'tier', 'visibility', 'membership',
    'identity', 'key', 'certificate', 'revocation', 'backup', 'recovery', 'restore',
    'migrate', 'upgrade', 'install', 'uninstall', 'build', 'release', 'version',
    'setup', 'configure', 'deploy', 'fleet', 'operator', 'admin', 'moderation',
    'telemetry', 'gateway', 'orchestration', 'runtime', 'process', 'thread', 'service',
    'daemon', 'watchdog', 'kill switch', 'killSwitch', 'model', 'router', 'provider',
    'endpoint', 'apiKey', 'modelName', 'prompt', 'context', 'memory', 'workspace',
    'plugin', 'extension', 'integration', 'bridge', 'proxy', 'adapter', 'mirror',
    'thin client', 'client', 'server', 'node', 'home node', 'relay node', 'full node',
    'capacitor', 'desktop', 'mobile', 'iOS', 'Android', 'macOS', 'Windows', 'Linux',
    'AppImage', 'DMG', '.exe', 'distribution', 'channel', 'notarization', 'Gatekeeper',
    'firewall', 'permission', 'notification', 'push', 'background', 'battery',
    'optimization', 'signing', 'attribution', 'budget', 'cost', 'maxCost', 'bid',
    'award', 'chain', 'Team job', 'Team jobs', 'cron', 'interval', 'one-shot',
    'daily', 'weekly', 'follow-up', 'check-in', 'proactive', 'autonomous', 'auto-reply',
    'draft', 'gatekeeper', 'escalate', 'acknowledge', 'pending', 'expired', 'chain_award',
    'sync', 'refresh', 'fetch', 'publish', 'unpublish', 'import', 'export', 'archive',
    'delete', 'index', 'chunk', 're-index', 'discover', 'query', 'browse', 'read',
    'write', 'list', 'propose', 'accept', 'reject', 'negotiate', 'run', 'result',
    'partial', 'completed', 'failed', 'cancelled', 'created', 'planned', 'discovering',
    'negotiating', 'waiting_for_peer', 'waiting_for_owner', 'running',
    'collectCompletedResults', 'closeOnFirstCompletedResult', 'requireApprovalFor',
    'allowedActions', 'disallowedActions', 'maxSensitivity', 'expiresAt',
    'Knowledge Base', 'ToolRegistry', 'Bond Engine', 'Inbound Guard', 'Task Runtime',
    'Brain', 'Semantic Firewall', 'Vault', 'Library', 'Browser', 'Terminal',
    'Approvals', 'Activity', 'Profile', 'Settings', 'People', 'Conversations', 'Chat',
    'Groups', 'Rooms', 'Discover', 'Me', 'Identity', 'Agent Network', 'Ext Agent',
    'AI Engine', 'Plugins', 'Automation', 'Notifications', 'Privacy', 'Node',
    'Pairing', 'Home', 'Social', 'HomeRemote', 'Claude Desktop', 'Obsidian',
    'envoy:owner:', 'envoy:device:', 'envoy:agent:', 'envoy_', 'owner ID', 'device ID',
    'agent ID', 'peer ID', 'display name', 'bio', 'avatar', 'thumbnail', 'proof text',
    'pairing queue', 'invitation link', 'multiaddr', 'listening address',
    'advertise address', 'bootstrap address', 'relay address', 'connectivity-status',
    'relay-status', 'mesh.search', 'mesh.findKnowledge', 'mesh.sendMessage', 'mesh.intro',
    'mesh.add-trigger', 'mesh.update-trigger', 'mesh.remove-trigger', 'mesh.list-triggers',
    'mesh.list-pending', 'mesh.approve', 'mesh.reject', 'mesh.reject-all', 'mesh.escalate',
    'mesh.acknowledge-escalation', 'mesh.share_propose', 'mesh.library_request_share',
    'mesh.transfer_status', 'mesh.share_list_pending', 'mesh.task.propose',
    'mesh.task.await_result', 'mesh.capability_provider.start', 'mesh.agent_card.request',
    'mesh.list_agent_network_workers', 'mesh.mcp.list_tools', 'mesh.mcp.call_tool',
    'mesh.library_list', 'mesh.library_read', 'mesh.library_discover', 'mesh.chat_rag_search',
    'mesh.knowledge.query', 'mesh.session-summary', 'mesh.list-sessions',
    'mesh.set-digest-schedule', 'mesh.get-digest-config', 'mesh.set-contact-mode',
    'getMorningReport', 'createNote', 'deleteNote', 'npm install', 'npm run typecheck',
    'npm test', 'npm run node:dev', 'npm run cli', 'npm run setup', './scripts/setup.sh',
    '.\\scripts\\setup.ps1', '--profile', '--relay-server', '--listen', '--bootstrap',
    '--relay', '--include-p2p-trace', '--vault', '--query', '--approvals',
    '/ip4/0.0.0.0/tcp/4001', '/ip4/127.0.0.1/tcp/18789', '/ip4/127.0.0.1/tcp/3031',
    '/ip4/127.0.0.1/tcp/11434/v1', '/ip4/127.0.0.1/tcp/4000/v1',
    '/ip4/127.0.0.1/tcp/8010/message', '/ip4/127.0.0.1/tcp/8020/message',
    '18789', '3031', '11434', '4000', '4001', '8010', '8020',
}

VERB_MAP = {
    'install': '安装', 'installed': '已安装', 'installation': '安装',
    'setup': '设置', 'set up': '设置',
    'configure': '配置', 'configured': '已配置', 'configuration': '配置', 'config': '配置',
    'enable': '启用', 'enabled': '已启用', 'disabling': '禁用', 'disabled': '已禁用', 'disable': '禁用',
    'run': '运行', 'running': '运行', 'runs': '运行', 'started': '已启动', 'start': '启动',
    'stop': '停止', 'stopped': '已停止', 'restart': '重新启动', 'restarted': '已重新启动',
    'open': '打开', 'opens': '打开', 'opened': '已打开', 'close': '关闭', 'closed': '已关闭',
    'view': '查看', 'views': '查看', 'viewing': '查看',
    'review': '审阅', 'reviewing': '审阅', 'reviewed': '已审阅',
    'check': '检查', 'checking': '检查', 'checked': '已检查',
    'verify': '验证', 'verifying': '验证', 'verified': '已验证',
    'confirm': '确认', 'confirming': '确认', 'confirmed': '已确认',
    'test': '测试', 'testing': '测试', 'tested': '已测试',
    'debug': '调试', 'debugging': '调试', 'debugged': '已调试',
    'troubleshoot': '故障排除', 'troubleshooting': '故障排除',
    'diagnose': '诊断', 'diagnosing': '诊断', 'diagnosed': '已诊断', 'diagnosis': '诊断',
    'report': '报告', 'reports': '报告', 'reporting': '报告', 'reported': '已报告',
    'log': '日志', 'logs': '日志', 'logging': '日志', 'logged': '已记录',
    'audit': '审计', 'audits': '审计', 'auditing': '审计', 'audited': '已审计',
    'backup': '备份', 'backups': '备份', 'backing up': '备份', 'backed up': '已备份',
    'restore': '恢复', 'restores': '恢复', 'restoring': '恢复', 'restored': '已恢复',
    'recovery': '恢复', 'recover': '恢复', 'recovering': '恢复', 'recovered': '已恢复',
    'migrate': '迁移', 'migrating': '迁移', 'migrated': '已迁移', 'migration': '迁移',
    'upgrade': '升级', 'upgrading': '升级', 'upgraded': '已升级', 'upgrades': '升级',
    'update': '更新', 'updating': '更新', 'updated': '已更新', 'updates': '更新',
    'build': '构建', 'builds': '构建', 'building': '构建', 'built': '已构建',
    'deploy': '部署', 'deploying': '部署', 'deployed': '已部署', 'deployment': '部署',
    'download': '下载', 'downloading': '下载', 'downloaded': '已下载', 'downloads': '下载',
    'import': '导入', 'importing': '导入', 'imported': '已导入', 'imports': '导入',
    'export': '导出', 'exporting': '导出', 'exported': '已导出', 'exports': '导出',
    'delete': '删除', 'deleting': '删除', 'deleted': '已删除', 'deletion': '删除',
    'remove': '移除', 'removing': '移除', 'removed': '已移除', 'removal': '移除',
    'create': '创建', 'creating': '创建', 'created': '已创建', 'creates': '创建',
    'add': '添加', 'adding': '添加', 'added': '已添加', 'adds': '添加',
    'edit': '编辑', 'editing': '编辑', 'edited': '已编辑', 'edits': '编辑',
    'modify': '修改', 'modifying': '修改', 'modified': '已修改', 'modification': '修改',
    'save': '保存', 'saving': '保存', 'saved': '已保存', 'saves': '保存',
    'write': '写入', 'writing': '写入', 'written': '已写入', 'writes': '写入',
    'read': '读取', 'reading': '读取', 'reads': '读取',
    'search': '搜索', 'searching': '搜索', 'searched': '已搜索', 'searches': '搜索',
    'find': '查找', 'finding': '查找', 'found': '已找到', 'finds': '查找',
    'discover': '发现', 'discovering': '发现', 'discovered': '已发现', 'discovers': '发现',
    'discovery': '发现', 'discoveries': '发现', 'discoverable': '可发现的',
    'browse': '浏览', 'browsing': '浏览', 'browsed': '已浏览', 'browses': '浏览',
    'publish': '发布', 'publishing': '发布', 'published': '已发布', 'publishes': '发布',
    'unpublish': '取消发布', 'unpublishing': '取消发布', 'unpublished': '已取消发布',
    'share': '分享', 'sharing': '分享', 'shared': '已分享', 'shares': '分享',
    'send': '发送', 'sending': '发送', 'sent': '已发送', 'sends': '发送',
    'receive': '接收', 'receiving': '接收', 'received': '已接收', 'receives': '接收',
    'accept': '接受', 'accepting': '接受', 'accepted': '已接受', 'accepts': '接受',
    'reject': '拒绝', 'rejecting': '拒绝', 'rejected': '已拒绝', 'rejects': '拒绝',
    'approve': '批准', 'approving': '批准', 'approved': '已批准', 'approves': '批准',
    'approval': '批准', 'approvals': '批准',
    'deny': '拒绝', 'denying': '拒绝', 'denied': '已拒绝', 'denies': '拒绝',
    'allow': '允许', 'allowing': '允许', 'allowed': '已允许', 'allows': '允许',
    'request': '请求', 'requests': '请求', 'requesting': '请求', 'requested': '已请求',
    'invite': '邀请', 'inviting': '邀请', 'invited': '已邀请', 'invites': '邀请',
    'invitation': '邀请', 'invitations': '邀请',
    'introduce': '介绍', 'introducing': '介绍', 'introduced': '已介绍', 'introduces': '介绍',
    'introduction': '介绍', 'introductions': '介绍',
    'refer': '推荐', 'referring': '推荐', 'referred': '已推荐', 'refers': '推荐',
    'reference': '引用', 'references': '引用', 'referenced': '已引用', 'referencing': '引用',
    'connect': '连接', 'connecting': '连接', 'connected': '已连接', 'connects': '连接',
    'connection': '连接', 'connections': '连接', 'connectivity': '连接性',
    'access': '访问', 'accessing': '访问', 'accessed': '已访问', 'accesses': '访问',
    'permission': '权限', 'permissions': '权限',
    'authorize': '授权', 'authorizing': '授权', 'authorized': '已授权', 'authorizes': '授权',
    'authorization': '授权',
    'authenticate': '认证', 'authenticating': '认证', 'authenticated': '已认证',
    'authentication': '认证',
    'sign': '签名', 'signing': '签名', 'signed': '已签名', 'signs': '签名',
    'signature': '签名', 'signatures': '签名',
    'encrypt': '加密', 'encrypting': '加密', 'encrypted': '已加密', 'encrypts': '加密',
    'encryption': '加密',
    'decrypt': '解密', 'decrypting': '解密', 'decrypted': '已解密', 'decrypts': '解密',
    'decryption': '解密',
    'protect': '保护', 'protecting': '保护', 'protected': '已保护', 'protects': '保护',
    'protection': '保护',
    'threaten': '威胁', 'threatening': '威胁', 'threatened': '受威胁',
    'attack': '攻击', 'attacking': '攻击', 'attacked': '已攻击', 'attacks': '攻击',
    'expose': '暴露', 'exposing': '暴露', 'exposed': '已暴露', 'exposes': '暴露',
    'risk': '风险', 'risks': '风险', 'risky': '有风险的',
    'trust': '信任', 'trusting': '信任', 'trusted': '可信的', 'trusts': '信任',
    'distrust': '不信任', 'distrusting': '不信任', 'distrusted': '不可信的',
    'block': '阻止', 'blocking': '阻止', 'blocked': '已阻止', 'blocks': '阻止',
    'mute': '静音', 'muting': '静音', 'muted': '已静音', 'mutes': '静音',
    'revoke': '撤销', 'revoking': '撤销', 'revoked': '已撤销', 'revokes': '撤销',
    'revocation': '撤销',
    'grant': '授予', 'granting': '授予', 'granted': '已授予', 'grants': '授予',
    'upgrade': '升级', 'upgrading': '升级', 'upgraded': '已升级', 'upgrades': '升级',
    'downgrade': '降级', 'downgrading': '降级', 'downgraded': '已降级', 'downgrades': '降级',
    'pair': '配对', 'pairing': '配对', 'paired': '已配对', 'pairs': '配对',
    'bond': '绑定', 'bonding': '绑定', 'bonded': '已绑定', 'bonds': '绑定',
    'reach': '到达', 'reaching': '到达', 'reached': '已到达', 'reachable': '可到达的',
    'reachability': '可达性',
    'route': '路由', 'routing': '路由', 'routes': '路由',
    'negotiate': '协商', 'negotiating': '协商', 'negotiated': '已协商', 'negotiates': '协商',
    'plan': '规划', 'planning': '规划', 'planned': '已规划', 'plans': '规划',
    'execute': '执行', 'executing': '执行', 'executed': '已执行', 'executes': '执行',
    'complete': '完成', 'completing': '完成', 'completed': '已完成', 'completes': '完成',
    'fail': '失败', 'failing': '失败', 'failed': '已失败', 'fails': '失败',
    'cancel': '取消', 'cancelling': '取消', 'cancelled': '已取消', 'cancels': '取消',
    'escalate': '升级', 'escalating': '升级', 'escalated': '已升级', 'escalates': '升级',
    'acknowledge': '确认', 'acknowledging': '确认', 'acknowledged': '已确认',
    'acknowledges': '确认',
    'queue': '队列', 'queuing': '队列', 'queued': '已排队', 'queues': '队列',
    'expire': '过期', 'expiring': '过期', 'expired': '已过期', 'expires': '过期',
    'merge': '合并', 'merging': '合并', 'merged': '已合并', 'merges': '合并',
    'collect': '收集', 'collecting': '收集', 'collected': '已收集', 'collects': '收集',
    'attach': '连接', 'attaching': '连接', 'attached': '已连接', 'attaches': '连接',
    'detach': '断开', 'detaching': '断开', 'detached': '已断开', 'detaches': '断开',
    'toggle': '切换', 'toggling': '切换', 'toggled': '已切换', 'toggles': '切换',
    'watch': '监视', 'watching': '监视', 'watched': '已监视', 'watches': '监视',
    'monitor': '监控', 'monitoring': '监控', 'monitored': '已监控', 'monitors': '监控',
    'inspect': '检查', 'inspecting': '检查', 'inspected': '已检查', 'inspects': '检查',
    'scan': '扫描', 'scanning': '扫描', 'scanned': '已扫描', 'scans': '扫描',
    'fetch': '获取', 'fetching': '获取', 'fetched': '已获取', 'fetches': '获取',
    'sync': '同步', 'syncing': '同步', 'synced': '已同步', 'syncs': '同步',
    'refresh': '刷新', 'refreshing': '刷新', 'refreshed': '已刷新', 'refreshes': '刷新',
    'index': '索引', 'indexing': '索引', 'indexed': '已索引', 'indexes': '索引',
    'reindex': '重新索引', 'reindexing': '重新索引', 'reindexed': '已重新索引',
    'chunk': '分块', 'chunking': '分块', 'chunked': '已分块', 'chunks': '分块',
    'reproduce': '复制', 'reproducing': '复制', 'reproduced': '已复制', 'reproduces': '复制',
    'resolve': '解决', 'resolving': '解决', 'resolved': '已解决', 'resolves': '解决',
    'persist': '持久化', 'persisting': '持久化', 'persisted': '已持久化', 'persists': '持久化',
    'consume': '消费', 'consuming': '消费', 'consumed': '已消费', 'consumes': '消费',
    'generate': '生成', 'generating': '生成', 'generated': '已生成', 'generates': '生成',
    'trigger': '触发', 'triggering': '触发', 'triggered': '已触发', 'triggers': '触发',
    'schedule': '调度', 'scheduling': '调度', 'scheduled': '已调度', 'schedules': '调度',
    'emit': '发出', 'emitting': '发出', 'emitted': '已发出', 'emits': '发出',
    'inject': '注入', 'injecting': '注入', 'injected': '已注入', 'injects': '注入',
    'derive': '派生', 'deriving': '派生', 'derived': '已派生', 'derives': '派生',
    'derive': '派生', 'deriving': '派生', 'derived': '已派生', 'derives': '派生',
    'derive': '派生', 'deriving': '派生', 'derived': '已派生', 'derives': '派生',
}

ADJ_MAP = {
    'available': '可用', 'availability': '可用性',
    'enabled': '已启用', 'disabled': '已禁用',
    'active': '活跃', 'inactive': '不活跃',
    'running': '运行中', 'stopped': '已停止',
    'connected': '已连接', 'disconnected': '已断开',
    'reachable': '可到达的', 'unreachable': '不可到达的',
    'authorized': '已授权', 'unauthorized': '未授权',
    'authenticated': '已认证', 'unauthenticated': '未认证',
    'encrypted': '已加密', 'unencrypted': '未加密',
    'signed': '已签名', 'unsigned': '未签名',
    'verified': '已验证', 'unverified': '未验证',
    'trusted': '可信的', 'untrusted': '不可信的',
    'blocked': '已阻止', 'unblocked': '未阻止',
    'bonded': '已绑定', 'unbonded': '未绑定',
    'paired': '已配对', 'unpaired': '未配对',
    'approved': '已批准', 'pending': '待处理', 'rejected': '已拒绝',
    'completed': '已完成', 'failed': '已失败', 'cancelled': '已取消',
    'planned': '已规划', 'discovering': '发现中', 'negotiating': '协商中',
    'running': '运行中', 'partial': '部分完成',
    'expired': '已过期', 'valid': '有效', 'invalid': '无效',
    'private': '私有的', 'public': '公开的',
    'friends': '朋友的', 'trusted': '受信任的',
    'direct': '直接的', 'referred': '推荐的',
    'stranger': '陌生人的', 'blocked': '已阻止的',
    'local': '本地的', 'remote': '远程的',
    'internal': '内部的', 'external': '外部的',
    'native': '原生的', 'compatible': '兼容的',
    'personal': '个人的', 'shared': '共享的',
    'sensitive': '敏感的', 'insensitive': '不敏感的',
    'visible': '可见的', 'invisible': '不可见的',
    'readable': '可读的', 'writeable': '可写的',
    'configurable': '可配置的', 'customizable': '可定制的',
    'automated': '自动化的', 'autonomous': '自主的',
    'proactive': '主动的', 'reactive': '被动的',
    'secure': '安全的', 'insecure': '不安全的',
    'private': '私有的', 'confidential': '机密的',
    'anonymous': '匿名的', 'identified': '已识别的',
    'centralized': '集中式的', 'decentralized': '去中心化的',
    'peer-to-peer': '点对点的', 'mesh': '网格的',
    'mobile': '移动的', 'desktop': '桌面的',
    'thin': '瘦的', 'full': '完整的',
    'bundled': '捆绑的', 'standalone': '独立的',
    'built-in': '内置的', 'optional': '可选的',
    'experimental': '实验性的', 'beta': '测试版的',
    'stable': '稳定的', 'available': '可用的',
    'planned': '规划中的', 'parked': '暂停的',
    'production': '生产的', 'development': '开发的',
    'essential': '基本的', 'extended': '扩展的',
    'minimal': '最小的', 'complete': '完整的',
    'hierarchical': '分层的', 'flat': '扁平的',
    'rate-limited': '速率限制的', 'unlimited': '无限制的',
    'policy-based': '基于策略的', 'rule-based': '基于规则的',
    'deterministic': '确定性的', 'probabilistic': '概率性的',
    'encrypted': '加密的', 'signed': '签名的',
    'canonical': '规范的', 'raw': '原始的',
    'attributed': '带有归属的', 'anonymous': '匿名的',
    'federated': '联合的', 'centralized': '集中的',
    'distributed': '分布式的', 'local-first': '本地优先的',
    'event-driven': '事件驱动的', 'polling': '轮询的',
    'push': '推送的', 'pull': '拉取的',
    'streaming': '流式的', 'batch': '批量的',
    'realtime': '实时的', 'asynchronous': '异步的',
    'synchronous': '同步的', 'delayed': '延迟的',
    'inbound': '入站的', 'outbound': '出站的',
    'in-process': '进程内的', 'out-of-process': '进程外的',
    'child': '子的', 'parent': '父的',
    'primary': '主要的', 'secondary': '次要的',
    'default': '默认的', 'custom': '自定义的',
    'global': '全局的', 'local': '本地的',
    'persistent': '持久的', 'temporary': '临时的',
    'volatile': '易失的', 'stable': '稳定的',
    'coordinated': '协调的', 'independent': '独立的',
    'collaborative': '协作的', 'competitive': '竞争的',
}

NOUN_MAP = {
    'installation': '安装', 'installer': '安装程序',
    'setup': '设置', 'configuration': '配置', 'config': '配置',
    'feature': '功能', 'features': '功能', 'capability': '能力', 'capabilities': '能力',
    'option': '选项', 'options': '选项', 'preference': '偏好设置', 'preferences': '偏好设置',
    'setting': '设置', 'settings': '设置',
    'limitation': '限制', 'limitations': '限制', 'availability': '可用性',
    'requirement': '要求', 'requirements': '要求', 'prerequisite': '前提条件', 'prerequisites': '前提条件',
    'recommendation': '推荐', 'recommendations': '推荐',
    'choice': '选择', 'selection': '选择',
    'usage': '使用', 'use': '使用',
    'runtime': '运行时', 'process': '进程', 'thread': '线程', 'service': '服务',
    'daemon': '守护进程', 'watchdog': '看门狗',
    'gateway': '网关', 'orchestrator': '编排器', 'orchestration': '编排',
    'engine': '引擎', 'model': '模型', 'router': '路由器', 'provider': '提供商',
    'endpoint': '端点', 'apiKey': 'API 密钥', 'modelName': '模型名称',
    'prompt': '提示', 'context': '上下文', 'memory': '内存', 'session': '会话',
    'workspace': '工作空间', 'plugin': '插件', 'extension': '扩展', 'integration': '集成',
    'bridge': '桥', 'proxy': '代理', 'adapter': '适配器', 'mirror': '镜像',
    'client': '客户端', 'server': '服务器', 'node': '节点',
    'home node': '主节点', 'relay node': '中继节点', 'full node': '完整节点',
    'capacitor': 'Capacitor', 'desktop': '桌面', 'mobile': '移动',
    'device': '设备', 'devices': '设备',
    'agent': '智能体', 'agents': '智能体', 'assistant': '助手',
    'owner': '所有者', 'owners': '所有者', 'identity': '身份', 'identities': '身份',
    'peer': '对等节点', 'peers': '对等节点', 'contact': '联系人', 'contacts': '联系人',
    'group': '群组', 'groups': '群组', 'conversation': '对话', 'conversations': '对话',
    'chat': '聊天', 'message': '消息', 'messages': '消息', 'voice': '语音', 'call': '通话',
    'audio': '音频', 'video': '视频', 'file': '文件', 'files': '文件', 'photo': '照片',
    'photos': '照片', 'gallery': '相册', 'avatar': '头像', 'thumbnail': '缩略图',
    'share': '分享', 'transfer': '传输', 'search': '搜索', 'discovery': '发现',
    'network': '网络', 'networks': '网络', 'mesh': '网格', 'mesh network': '网格网络',
    'relay': '中继', 'relays': '中继', 'bootstrap': '引导', 'circuit': '电路',
    'rendezvous': '会合', 'forwarding': '转发', 'connectivity': '连接性', 'reachability': '可达性',
    'transport': '传输', 'protocol': '协议', 'protocols': '协议',
    'envelope': '信封', 'envelopes': '信封', 'payload': '负载', 'payloads': '负载',
    'intent': '意图', 'intents': '意图',
    'encryption': '加密', 'signature': '签名', 'signatures': '签名', 'verification': '验证',
    'proof': '证明', 'fingerprint': '指纹', 'hash': '哈希',
    'correlation': '关联', 'latency': '延迟', 'timeout': '超时',
    'policy': '策略', 'sensitivity': '敏感度', 'trust': '信任', 'tier': '等级',
    'visibility': '可见性', 'membership': '成员资格',
    'key': '密钥', 'keys': '密钥', 'certificate': '证书', 'certificates': '证书',
    'revocation': '撤销', 'backup': '备份', 'recovery': '恢复', 'restore': '恢复',
    'migration': '迁移', 'upgrade': '升级', 'update': '更新', 'version': '版本',
    'release': '发布', 'releases': '发布', 'build': '构建', 'builds': '构建',
    'deployment': '部署', 'fleet': '集群', 'operator': '操作员', 'admin': '管理员',
    'moderation': '审核', 'telemetry': '遥测',
    'bond': '绑定', 'bonds': '绑定', 'mandate': '授权', 'mandates': '授权',
    'vault': '保险库', 'library': '库', 'browser': '浏览器', 'terminal': '终端',
    'approval': '批准', 'approvals': '批准', 'audit': '审计', 'digest': '摘要',
    'trigger': '触发器', 'triggers': '触发器', 'profile': '资料', 'profiles': '资料',
    'knowledge': '知识', 'knowledge base': '知识库', 'RAG': 'RAG',
    'note': '笔记', 'notes': '笔记', 'document': '文档', 'documents': '文档',
    'folder': '文件夹', 'folders': '文件夹', 'path': '路径', 'paths': '路径',
    'index': '索引', 'chunk': '块', 'chunking': '分块', 're-index': '重新索引',
    'search': '搜索', 'query': '查询', 'browse': '浏览', 'read': '读取', 'write': '写入',
    'publish': '发布', 'unpublish': '取消发布', 'import': '导入', 'export': '导出',
    'archive': '归档', 'delete': '删除',
    'propose': '提议', 'accept': '接受', 'reject': '拒绝', 'negotiate': '协商',
    'result': '结果', 'results': '结果', 'partial': '部分结果',
    'job': '任务', 'jobs': '任务', 'team job': '团队任务', 'team jobs': '团队任务',
    'chain': '链', 'award': '奖励', 'bid': '出价', 'budget': '预算', 'cost': '成本',
    'schedule': '调度', 'cron': '定时', 'interval': '间隔', 'one-shot': '一次性',
    'daily': '每日', 'weekly': '每周', 'follow-up': '跟进', 'check-in': '签到',
    'proactive': '主动', 'autonomous': '自主', 'auto-reply': '自动回复', 'draft': '草稿',
    'gatekeeper': '守门员', 'escalation': '升级', 'acknowledgement': '确认',
    'pending': '待处理', 'expired': '过期', 'chain_award': '链奖励',
    'sync': '同步', 'refresh': '刷新', 'fetch': '获取',
    'notification': '通知', 'notifications': '通知', 'push': '推送',
    'background': '后台', 'foreground': '前台',
    'permission': '权限', 'permissions': '权限', 'firewall': '防火墙',
    'signing': '签名', 'attribution': '归属',
    'DID': 'DID', 'owner ID': '所有者 ID', 'device ID': '设备 ID', 'agent ID': '智能体 ID',
    'peer ID': '对等节点 ID', 'display name': '显示名称', 'bio': '简介',
    'proof text': '证明文本', 'pairing queue': '配对队列', 'invitation link': '邀请链接',
    'multiaddr': '多地址', 'listening address': '监听地址', 'advertise address': '广告地址',
    'bootstrap address': '引导地址', 'relay address': '中继地址',
    'capability': '能力', 'capabilities': '能力',
}

PREPOSITION_MAP = {
    'in': '在', 'on': '在', 'at': '在', 'to': '到', 'from': '从', 'for': '为', 'with': '与',
    'without': '没有', 'through': '通过', 'via': '通过', 'over': '通过', 'under': '在...下',
    'above': '在...上', 'below': '在...下', 'between': '在...之间', 'among': '在...之中',
    'against': '反对', 'along': '沿着', 'around': '围绕', 'before': '在...之前', 'after': '在...之后',
    'during': '在...期间', 'since': '自从', 'until': '直到', 'beyond': '超越', 'within': '在...之内',
    'outside': '在...之外', 'into': '进入', 'onto': '到...上', 'off': '离开', 'out': '出来',
    'up': '向上', 'down': '向下', 'back': '回来', 'forward': '向前', 'away': '离开',
    'together': '一起', 'apart': '分开', 'aside': '旁边', 'around': '周围', 'about': '关于',
    'across': '穿过', 'throughout': '贯穿', 'toward': '朝向', 'towards': '朝向',
}

ADVERB_MAP = {
    'locally': '本地地', 'remotely': '远程地',
    'directly': '直接地', 'indirectly': '间接地',
    'privately': '私', 'publicly': '公开地',
    'securely': '安全地', 'insecurely': '不安全地',
    'autonomously': '自主地', 'manually': '手动地',
    'proactively': '主动地', 'reactively': '被动地',
    'automatically': '自动地', 'explicitly': '明确地',
    'implicitly': '隐式地', 'silently': '默默地',
    'deliberately': '故意地', 'accidentally': '意外地',
    'successfully': '成功地', 'unsuccessfully': '不成功地',
    'partially': '部分地', 'completely': '完全地',
    'quickly': '快速地', 'slowly': '缓慢地',
    'periodically': '定期地', 'continuously': '持续地',
    'immediately': '立即', 'eventually': '最终',
    'currently': '当前', 'previously': '以前',
    'primarily': '主要地', 'secondarily': '次要地',
    'additionally': '另外', 'alternatively': '或者',
    'consequently': '因此', 'furthermore': '此外',
    'however': '然而', 'nevertheless': '尽管如此',
    'otherwise': '否则', 'specifically': '具体地',
    'generally': '通常', 'typically': '典型地',
    'potentially': '潜在地', 'actually': '实际上',
    'approximately': '大约', 'exactly': '精确地',
}

HEADINGS_MAP = {
    '# EnvoyMesh Guidebook': '# EnvoyMesh 指南',
    '## How to read this guide': '## 如何阅读本指南',
    '## Feature status labels': '## 功能状态标签',
    '## Product terminology used in this guide': '## 本指南使用的产品术语',
    '# Table of Contents': '# 目录',
    '## Part I — Discover EnvoyMesh': '## 第一部分 — 认识 EnvoyMesh',
    '### 1. Welcome to EnvoyMesh': '### 1. 欢迎来到 EnvoyMesh',
    '#### 1.1 A private network for people and AI agents': '#### 1.1 面向人类和 AI 智能体的私有网络',
    '#### 1.2 Local-first and peer-to-peer by design': '#### 1.2 设计上优先本地和点对点',
    '#### 1.3 No central account required': '#### 1.3 无需中央帐户',
    '#### 1.4 Your identity, relationships, and data belong to you': '#### 1.4 您的身份、关系和数据属于您自己',
    '#### 1.5 Direct connections and optional relays': '#### 1.5 直接连接和可选中继',
    '#### 1.6 Personal agents and external agents': '#### 1.6 个人智能体和外部智能体',
    '#### 1.7 Trusted multi-agent collaboration': '#### 1.7 可信多智能体协作',
    '#### 1.8 Open protocols and interoperability': '#### 1.8 开放协议和互操作性',
    '#### 1.9 Major features at a glance': '#### 1.9 主要功能一览',
    '#### 1.10 Current availability and limitations': '#### 1.10 当前可用性和限制',
    '### 2. Why EnvoyMesh?': '### 2. 为什么选择 EnvoyMesh？',
    '#### 2.1 Private communication without a central platform': '#### 2.1 无需中央平台的私密通信',
    '#### 2.2 Self-sovereign identity across your devices': '#### 2.2 跨设备的自主身份',
    '#### 2.3 AI assistance under your control': '#### 2.3 由您掌控的 AI 助手',
    '#### 2.4 Trusted knowledge sharing': '#### 2.4 可信知识共享',
    '#### 2.5 Safe task delegation': '#### 2.5 安全的任务委托',
    '#### 2.6 Collaboration among agents you choose': '#### 2.6 您选择的智能体之间的协作',
    '#### 2.7 Local models, remote models, and external agents': '#### 2.7 本地模型、远程模型和外部智能体',
    '#### 2.8 Auditability instead of invisible automation': '#### 2.8 可审计性而非隐形自动化',
    '#### 2.9 When EnvoyMesh is the right choice': '#### 2.9 何时适合使用 EnvoyMesh',
    '#### 2.10 When another solution may be a better fit': '#### 2.10 何时其他解决方案更合适',
    '### 3. What You Can Do': '### 3. 您可以做什么',
    '#### 3.1 Connect with trusted people': '#### 3.1 与信任的人建立连接',
    '#### 3.2 Exchange private messages': '#### 3.2 交换私密消息',
    '#### 3.3 Create group conversations': '#### 3.3 创建群组对话',
    '#### 3.4 Send audio messages and make voice calls': '#### 3.4 发送语音消息和进行语音通话',
    '#### 3.5 Share files and profile photos': '#### 3.5 分享文件和资料照片',
    '#### 3.6 Talk to your personal AI agent': '#### 3.6 与您的个人 AI 智能体对话',
    '#### 3.7 Connect OpenClaw, HomeClaw, Hermes, or OpenHuman': '#### 3.7 连接 OpenClaw、HomeClaw、Hermes 或 OpenHuman',
    '#### 3.8 Search local and trusted knowledge': '#### 3.8 搜索本地和可信知识',
    '#### 3.9 Publish and browse mesh content': '#### 3.9 发布和浏览网格内容',
    '#### 3.10 Delegate work to another agent': '#### 3.10 将工作委托给另一个智能体',
    '#### 3.11 Run Team jobs across several agents': '#### 3.11 在多个智能体上运行团队任务',
    '#### 3.12 Connect MCP and A2A applications': '#### 3.12 连接 MCP 和 A2A 应用',
    '#### 3.13 Use terminals remotely': '#### 3.13 远程使用终端',
    '#### 3.14 Operate a private or community relay': '#### 3.14 运行私有或社区中继',
    '### 4. How EnvoyMesh Works': '### 4. EnvoyMesh 如何工作',
    '#### 4.1 A plain-language system overview': '#### 4.1 系统概览（通俗易懂版）',
    '#### 4.2 Owners, devices, agents, and peers': '#### 4.2 所有者、设备、智能体和对等节点',
    '#### 4.3 Contacts, bonds, and trust levels': '#### 4.3 联系人、绑定和信任等级',
    '#### 4.4 Signed messages and verifiable senders': '#### 4.4 签名消息和可验证发送者',
    '#### 4.5 Personal agents and external-agent bridges': '#### 4.5 个人智能体和外部智能体桥接',
    '#### 4.6 Local knowledge, the Library, and the Vault': '#### 4.6 本地知识、库和保险库',
    '#### 4.7 Tasks, mandates, and approvals': '#### 4.7 任务、授权和审批',
    '#### 4.8 Agent Network membership': '#### 4.8 智能体网络成员资格',
    '#### 4.9 Direct networking and relay assistance': '#### 4.9 直接网络和中继协助',
    '#### 4.10 Activity records and end-to-end auditing': '#### 4.10 活动记录和端到端审计',
    '### 5. Common Use Cases': '### 5. 常见用例',
    '#### 5.1 A private personal AI across devices': '#### 5.1 跨设备的私密个人 AI',
    '#### 5.2 A family or friends mesh': '#### 5.2 家庭或朋友网络',
    '#### 5.3 Trusted research and knowledge exchange': '#### 5.3 可信研究和知识交流',
    '#### 5.4 A small-team Agent Network': '#### 5.4 小型团队智能体网络',
    '#### 5.5 Multi-agent planning and report generation': '#### 5.5 多智能体规划和报告生成',
    '#### 5.6 OpenClaw with trusted mesh contacts': '#### 5.6 OpenClaw 与可信网格联系人',
    '#### 5.7 HomeClaw as an external EnvoyMesh agent': '#### 5.7 HomeClaw 作为外部 EnvoyMesh 智能体',
    '#### 5.8 Hermes as an external EnvoyMesh agent': '#### 5.8 Hermes 作为外部 EnvoyMesh 智能体',
    '#### 5.9 OpenHuman as an external EnvoyMesh agent': '#### 5.9 OpenHuman 作为外部 EnvoyMesh 智能体',
    '#### 5.10 Claude Desktop using EnvoyMesh through MCP': '#### 5.10 通过 MCP 使用 EnvoyMesh 的 Claude Desktop',
    '#### 5.11 External A2A clients delegating tasks': '#### 5.11 委托任务的外部 A2A 客户端',
    '#### 5.12 A self-hosted relay fleet': '#### 5.12 自托管中继集群',
    '### 6. Product and Protocol Comparisons': '### 6. 产品和协议比较',
    '#### 6.1 EnvoyMesh and centralized messengers': '#### 6.1 EnvoyMesh 与集中式信使',
    '#### 6.2 EnvoyMesh and cloud AI assistants': '#### 6.2 EnvoyMesh 与云 AI 助手',
    '#### 6.3 EnvoyMesh and standalone OpenClaw': '#### 6.3 EnvoyMesh 与独立 OpenClaw',
    '#### 6.4 EnvoyMesh and external agent runtimes': '#### 6.4 EnvoyMesh 与外部智能体运行时',
    '#### 6.5 EnvoyMesh and MCP': '#### 6.5 EnvoyMesh 与 MCP',
    '#### 6.6 EnvoyMesh and A2A': '#### 6.6 EnvoyMesh 与 A2A',
    '#### 6.7 EnvoyMesh native Agent Network versus public marketplaces': '#### 6.7 EnvoyMesh 原生智能体网络与公共市场',
    '#### 6.8 Native protocols versus interoperability bridges': '#### 6.8 原生协议与互操作性桥',
    '## Part II — Install and Get Started': '## 第二部分 — 安装和入门',
    '### 7. Choose Your Setup': '### 7. 选择您的设置',
    '#### 7.1 Desktop only': '#### 7.1 仅桌面',
    '#### 7.2 Desktop with EnvoyGo mobile access': '#### 7.2 桌面配合 EnvoyGo 移动访问',
    '#### 7.3 Desktop with the bundled EnvoyAI agent': '#### 7.3 桌面配合捆绑的 EnvoyAI 智能体',
    '#### 7.4 Desktop with an external agent': '#### 7.4 桌面配合外部智能体',
    '#### 7.5 Desktop with local or remote models': '#### 7.5 桌面配合本地或远程模型',
    '#### 7.6 Personal relay or community relay': '#### 7.6 个人中继或社区中继',
    '#### 7.7 Small-team and organization deployments': '#### 7.7 小型团队和组织部署',
    '#### 7.8 Recommended first-time setup': '#### 7.8 推荐的首次设置',
    '### 8. Install EnvoyMesh': '### 8. 安装 EnvoyMesh',
    '#### 8.1 System requirements': '#### 8.1 系统要求',
    '#### 8.2 Install on macOS': '#### 8.2 在 macOS 上安装',
    '#### 8.3 Install on Windows': '#### 8.3 在 Windows 上安装',
    '#### 8.4 Install EnvoyGo on iOS': '#### 8.4 在 iOS 上安装 EnvoyGo',
    '#### 8.5 Install EnvoyGo on Android': '#### 8.5 在 Android 上安装 EnvoyGo',
    '#### 8.6 Install from source': '#### 8.6 从源代码安装',
    '#### 8.7 Verify the installation': '#### 8.7 验证安装',
    '#### 8.8 Application data locations': '#### 8.8 应用数据位置',
    '#### 8.9 Update EnvoyMesh': '#### 8.9 更新 EnvoyMesh',
    '#### 8.10 Uninstall without losing identity or data': '#### 8.10 卸载而不丢失身份或数据',
    '### 9. Platform and Package Differences': '### 9. 平台和包差异',
    '#### 9.1 Desktop and mobile feature comparison': '#### 9.1 桌面和移动功能比较',
    '#### 9.2 macOS packaging': '#### 9.2 macOS 打包',
    '#### 9.3 Windows packaging': '#### 9.3 Windows 打包',
    '#### 9.4 OpenClaw extensions bundled on macOS': '#### 9.4 macOS 上捆绑的 OpenClaw 扩展',
    '#### 9.5 Essential OpenClaw extension selection on Windows': '#### 9.5 Windows 上的基本 OpenClaw 扩展选择',
    '#### 9.6 Full and slim desktop bundles': '#### 9.6 完整和精简桌面捆绑包',
    '#### 9.7 Optional IPFS sidecars': '#### 9.7 可选的 IPFS 侧车',
    '#### 9.8 Features requiring a home node': '#### 9.8 需要主节点的功能',
    '#### 9.9 Features available as an EnvoyGo mobile mirror': '#### 9.9 作为 EnvoyGo 移动镜像可用的功能',
    '#### 9.10 Legacy mobile experiments and current product boundaries': '#### 9.10 遗留移动实验和当前产品边界',
    '### 10. Create Your Identity': '### 10. 创建您的身份',
    '#### 10.1 What your EnvoyMesh identity represents': '#### 10.1 您的 EnvoyMesh 身份代表什么',
    '#### 10.2 Create an owner identity': '#### 10.2 创建所有者身份',
    '#### 10.3 Create your first device identity': '#### 10.3 创建您的第一个设备身份',
    '#### 10.4 Create or activate your agent identity': '#### 10.4 创建或激活您的智能体身份',
    '#### 10.5 Set your display profile': '#### 10.5 设置您的显示资料',
    '#### 10.6 Understand your DID': '#### 10.6 了解您的 DID',
    '#### 10.7 Protect your cryptographic keys': '#### 10.7 保护您的加密密钥',
    '#### 10.8 Back up identity and recovery data': '#### 10.8 备份身份和恢复数据',
    '#### 10.9 Add another device': '#### 10.9 添加另一个设备',
    '#### 10.10 Revoke a lost or compromised device': '#### 10.10 撤销丢失或受损的设备',
    '### 11. Tour the Application': '### 11. 应用导览',
    '#### 11.1 Home and node status': '#### 11.1 主页和节点状态',
    '#### 11.2 Conversations': '#### 11.2 对话',
    '#### 11.3 Contacts and discovery': '#### 11.3 联系人和发现',
    '#### 11.4 Groups': '#### 11.4 群组',
    '#### 11.5 Knowledge Base and Library': '#### 11.5 知识库和库',
    '#### 11.6 Browser': '#### 11.6 浏览器',
    '#### 11.7 Team jobs': '#### 11.7 团队任务',
    '#### 11.8 Terminals': '#### 11.8 终端',
    '#### 11.9 Approvals and activity': '#### 11.9 审批和活动',
    '#### 11.10 Profile': '#### 11.10 资料',
    '#### 11.11 Settings': '#### 11.11 设置',
    '#### 11.12 Connection and agent status indicators': '#### 11.12 连接和智能体状态指示器',
    '### 12. Connect Your First Contact': '### 12. 连接您的第一个联系人',
    '#### 12.1 What pairing and bonding do': '#### 12.1 配对和绑定的作用',
    '#### 12.2 Pair with a QR code': '#### 12.2 使用二维码配对',
    '#### 12.3 Pair with an invitation link': '#### 12.3 使用邀请链接配对',
    '#### 12.4 Pair on a local network': '#### 12.4 在本地网络上配对',
    '#### 12.5 Verify identity information': '#### 12.5 验证身份信息',
    '#### 12.6 Choose an appropriate trust level': '#### 12.6 选择适当的信任等级',
    '#### 12.7 Accept a bond request': '#### 12.7 接受绑定请求',
    '#### 12.8 Send the first message': '#### 12.8 发送第一条消息',
    '#### 12.9 Confirm direct or relay-assisted delivery': '#### 12.9 确认直接或中继辅助送达',
    '#### 12.10 Troubleshoot pairing': '#### 12.10 配对故障排除',
    '#### 12.11 Bundled sponsor contact': '#### 12.11 捆绑的赞助联系人',
    '### 13. Connect EnvoyGo': '### 13. 连接 EnvoyGo',
    '#### 13.1 How EnvoyGo works with a home node': '#### 13.1 EnvoyGo 如何与主节点配合工作',
    '#### 13.2 Pair the mobile app': '#### 13.2 配对移动应用',
    '#### 13.3 Confirm the home connection': '#### 13.3 确认主节点连接',
    '#### 13.4 Use chat and contacts': '#### 13.4 使用聊天和联系人',
    '#### 13.5 Use remote terminals': '#### 13.5 使用远程终端',
    '#### 13.6 View Team jobs': '#### 13.6 查看团队任务',
    '#### 13.7 Browse mesh content': '#### 13.7 浏览网格内容',
    '#### 13.8 Receive notifications': '#### 13.8 接收通知',
    '#### 13.9 Make and receive voice calls': '#### 13.9 拨打和接听语音通话',
    '#### 13.10 Revoke a lost phone': '#### 13.10 撤销丢失的手机',
    '#### 13.11 Current mobile limitations': '#### 13.11 当前移动限制',
    '### 14. First-Day Tutorials': '### 14. 首日教程',
    '#### 14.1 Send a private message': '#### 14.1 发送私密消息',
    '#### 14.2 Create a group conversation': '#### 14.2 创建群组对话',
    '#### 14.3 Send an audio message': '#### 14.3 发送语音消息',
    '#### 14.4 Make a voice call': '#### 14.4 进行语音通话',
    '#### 14.5 Share a file': '#### 14.5 分享文件',
    '#### 14.6 Ask EnvoyAI a question': '#### 14.6 向 EnvoyAI 提问',
    '#### 14.7 Add knowledge to your Library': '#### 14.7 向您的库添加知识',
    '#### 14.8 Search your Vault': '#### 14.8 搜索您的保险库',
    '#### 14.9 Ask a bonded agent for knowledge': '#### 14.9 向绑定的智能体请求知识',
    '#### 14.10 Approve a sensitive action': '#### 14.10 审批敏感操作',
    '#### 14.11 Start a simple Team job': '#### 14.11 启动简单的团队任务',
    '#### 14.12 Connect an external agent': '#### 14.12 连接外部智能体',
    '## Part III — People, Profiles, and Conversations': '## 第三部分 — 人员、资料和对话',
    '### 15. Contacts and Bonds': '### 15. 联系人和绑定',
    '#### 15.1 View and search contacts': '#### 15.1 查看和搜索联系人',
    '#### 15.2 Understand contact identity': '#### 15.2 了解联系人身份',
    '#### 15.3 Contact profiles and photos': '#### 15.3 联系人资料和照片',
    '#### 15.4 Online, offline, and connection states': '#### 15.4 在线、离线和连接状态',
    '#### 15.5 Direct, referred, public, and blocked trust': '#### 15.5 直接、推荐、公开和阻止信任',
    '#### 15.6 Change a contact\'s trust level': '#### 15.6 更改联系人的信任等级',
    '#### 15.7 Refer or introduce a contact': '#### 15.7 推荐或介绍联系人',
    '#### 15.8 Mute, block, or remove a contact': '#### 15.8 静音、阻止或移除联系人',
    '#### 15.9 Restore a connection': '#### 15.9 恢复连接',
    '#### 15.10 Contact privacy and disclosure settings': '#### 15.10 联系人隐私和披露设置',
    '### 16. Private Messaging': '### 16. 私密消息',
    '#### 16.1 Start a conversation': '#### 16.1 开始对话',
    '#### 16.2 Human-to-human messages': '#### 16.2 人与人消息',
    '#### 16.3 Human-to-agent messages': '#### 16.3 人与智能体消息',
    '#### 16.4 Replies and conversation continuity': '#### 16.4 回复和对话连续性',
    '#### 16.5 Message delivery states': '#### 16.5 消息送达状态',
    '#### 16.6 Offline behavior and retries': '#### 16.6 离线行为和重试',
    '#### 16.7 Search conversation history': '#### 16.7 搜索对话历史',
    '#### 16.8 Draft assistance': '#### 16.8 草稿辅助',
    '#### 16.9 Manage conversation data': '#### 16.9 管理对话数据',
    '#### 16.10 Message privacy and security': '#### 16.10 消息隐私和安全',
    '### 17. Group Conversations': '### 17. 群组对话',
    '#### 17.1 Create a group': '#### 17.1 创建群组',
    '#### 17.2 Invite members': '#### 17.2 邀请成员',
    '#### 17.3 Send group messages': '#### 17.3 发送群组消息',
    '#### 17.4 Manage membership': '#### 17.4 管理成员',
    '#### 17.5 Leave a group': '#### 17.5 离开群组',
    '#### 17.6 Group trust boundaries': '#### 17.6 群组信任边界',
    '#### 17.7 Group delivery and offline members': '#### 17.7 群组送达和离线成员',
    '#### 17.8 Group troubleshooting': '#### 17.8 群组故障排除',
    '### 18. Audio and Voice Calls': '### 18. 音频和语音通话',
    '#### 18.1 Record and send an audio message': '#### 18.1 录制并发送语音消息',
    '#### 18.2 Play and manage audio attachments': '#### 18.2 播放和管理音频附件',
    '#### 18.3 Start a voice call': '#### 18.3 发起语音通话',
    '#### 18.4 Answer or decline a call': '#### 18.4 接听或拒绝通话',
    '#### 18.5 Call status and controls': '#### 18.5 通话状态和控制',
    '#### 18.6 Background calls and mobile notifications': '#### 18.6 后台通话和移动通知',
    '#### 18.7 STUN and TURN connectivity': '#### 18.7 STUN 和 TURN 连接',
    '#### 18.8 Call privacy': '#### 18.8 通话隐私',
    '#### 18.9 Voice-call troubleshooting': '#### 18.9 语音通话故障排除',
    '#### 18.10 Video calls — planned, not currently available': '#### 18.10 视频通话 — 计划中，当前不可用',
    '### 19. Files, Photos, and Profile Sharing': '### 19. 文件、照片和资料分享',
    '#### 19.1 Share a file': '#### 19.1 分享文件',
    '#### 19.2 Accept or decline an incoming share': '#### 19.2 接受或拒绝传入的分享',
    '#### 19.3 Check transfer progress': '#### 19.3 检查传输进度',
    '#### 19.4 Verify file integrity': '#### 19.4 验证