#!/usr/bin/env python3
import re
import os

TERMS = {
    'EnvoyMesh': 'EnvoyMesh',
    'EnvoyGo': 'EnvoyGo',
    'EnvoyAI': 'EnvoyAI',
    'OpenClaw': 'OpenClaw',
    'HomeClaw': 'HomeClaw',
    'Hermes': 'Hermes',
    'OpenHuman': 'OpenHuman',
    'Claude': 'Claude',
    'Agent Network': '智能体网络',
    'Team jobs': '团队任务',
    'mesh': '网络',
    'libp2p': 'libp2p',
    'Ed25519': 'Ed25519',
    'DID': 'DID',
    'bond': '绑定',
    'bonds': '绑定',
    'peer': '对等节点',
    'owner': '所有者',
    'device': '设备',
    'agent': '智能体',
    'mandate': '授权',
    'vault': '保险库',
    'Vault': '保险库',
    'Library': '库',
    'RAG': 'RAG',
    'knowledge': '知识',
    'knowledge.query': 'knowledge.query',
    'JSON-RPC': 'JSON-RPC',
    'WebSocket': 'WebSocket',
    'JSONL': 'JSONL',
    'correlation ID': '关联ID',
    'audit': '审计',
    'policy': '策略',
    'Bond Engine': '绑定引擎',
    'trust': '信任',
    'trust tier': '信任等级',
    'direct': '直接',
    'referred': '推荐',
    'public': '公开',
    'blocked': '阻止',
    'stranger': '陌生人',
    'friends': '朋友',
    'sensitivity': '敏感度',
    'sensitivity label': '敏感度标签',
    'social': '社交',
    'Social': 'Social',
    'chat': '聊天',
    'message': '消息',
    'chat.message': 'chat.message',
    'profile': '资料',
    'Profile': '资料',
    'display name': '显示名称',
    'avatar': '头像',
    'contacts': '联系人',
    'groups': '群组',
    'voice call': '语音通话',
    'audio message': '语音消息',
    'file sharing': '文件共享',
    'terminal': '终端',
    'Browser': '浏览器',
    'relay': '中继',
    'circuit relay': '电路中继',
    'MCP': 'MCP',
    'A2A': 'A2A',
    'agent card': '智能体卡片',
    'task': '任务',
    'task lifecycle': '任务生命周期',
    'approval': '审批',
    'inbound guard': '入站守卫',
    'semantic firewall': '语义防火墙',
    'bootstrap': '引导',
    'community relay': '社区中继',
    'private relay': '私有中继',
    'rendezvous': '会合',
    'forwarding': '转发',
    'NAT': 'NAT',
    'TCP': 'TCP',
    'QUIC': 'QUIC',
    'mDNS': 'mDNS',
    'DHT': 'DHT',
    'LAN': '局域网',
    'WAN': '广域网',
    'payload': '负载',
    'envelope': '信封',
    'signature': '签名',
    'canonical JSON': '规范JSON',
    'node-config.json': 'node-config.json',
    'bridge-config.json': 'bridge-config.json',
    'envoy://': 'envoy://',
    '/ip4/': '/ip4/',
    '/tcp/': '/tcp/',
    '/p2p/': '/p2p/',
    '/p2p-circuit': '/p2p-circuit',
    'multiaddr': '多地址',
    'discovery': '发现',
    'search': '搜索',
    'federated search': '联合搜索',
    'index': '索引',
    'chunk': '块',
    'syndicated knowledge': '联合知识',
    'publish': '发布',
    'content': '内容',
    'visibility': '可见性',
    'Markdown': 'Markdown',
    'PDF': 'PDF',
    'library.read': 'library.read',
    'push notifications': '推送通知',
    'notifications': '通知',
    'settings': '设置',
    'Settings': '设置',
    'AI': 'AI',
    'model': '模型',
    'models': '模型',
    'model provider': '模型提供商',
    'local model': '本地模型',
    'remote model': '远程模型',
    'inference': '推理',
    'prompt': '提示',
    'LiteLLM': 'LiteLLM',
    'OpenAI': 'OpenAI',
    'HTTP': 'HTTP',
    'external agent': '外部智能体',
    'bridge': '桥接',
    'Ext Agent': '外部智能体',
    'endpoint': '端点',
    'localhost': 'localhost',
    '127.0.0.1': '127.0.0.1',
    'port': '端口',
    'API': 'API',
    'JSON': 'JSON',
    'JavaScript': 'JavaScript',
    'TypeScript': 'TypeScript',
    'npm': 'npm',
    'node': '节点',
    'home node': '主节点',
    'Home Node': '主节点',
    'NodeService': 'NodeService',
    'node runtime': '节点运行时',
    'relay server': '中继服务器',
    '--listen': '--listen',
    '--bootstrap': '--bootstrap',
    '--relay': '--relay',
    '--profile': '--profile',
    'connectivity-status': 'connectivity-status',
    'relay-status': 'relay-status',
    'CLI': 'CLI',
    'PTY': 'PTY',
    'shell': 'shell',
    'remote shell': '远程shell',
    'SSH': 'SSH',
    'TURN': 'TURN',
    'WebRTC': 'WebRTC',
    'CallKit': 'CallKit',
    'VoIP': 'VoIP',
    'FCM': 'FCM',
    'APNs': 'APNs',
    'iOS': 'iOS',
    'Android': 'Android',
    'macOS': 'macOS',
    'Windows': 'Windows',
    'desktop': '桌面',
    'Desktop': '桌面',
    'mobile': '移动',
    'Mobile': '移动',
    'thin client': '瘦客户端',
    'full node': '全节点',
    'Capacitor': 'Capacitor',
    'Tauri': 'Tauri',
    'Flutter': 'Flutter',
    'React': 'React',
    'Vite': 'Vite',
    'Electron': 'Electron',
    'installer': '安装程序',
    'installation': '安装',
    'setup': '设置',
    'build': '构建',
    'source': '源码',
    'release': '版本',
    'release notes': '版本说明',
    'CHANGELOG.md': 'CHANGELOG.md',
    'QuickStart.md': 'QuickStart.md',
    'Version': '版本',
    'Edition': '版本类型',
    'Revised': '修订日期',
    'Languages': '语言',
    'Audience': '受众',
    'Purpose': '目的',
    'Complete Guidebook Edition': '完整指南版',
    'Available': '可用',
    'Beta': 'Beta',
    'Experimental': '实验性',
    'Compatibility preset': '兼容性预设',
    'Planned': '计划中',
    'Parked': '暂停',
    'Operator': '操作员',
    'Created': '已创建',
    'Running': '运行中',
    'completed': '已完成',
    'failed': '失败',
    'cancelled': '已取消',
    'Phase': '阶段',
    'Appendix': '附录',
    'Part': '部分',
    'Figure': '图',
    'chat list': '聊天列表',
    'thread': '线程',
    'conversation': '对话',
    'Conversations': '对话',
    'People': '联系人',
    'Rooms': '房间',
    'New Group': '新建群组',
    'Me': '我',
    'Home': '首页',
    'connectivity': '连接性',
    'connection status': '连接状态',
    'reachability': '可达性',
    'online': '在线',
    'offline': '离线',
    'pending': '待处理',
    'sent': '已发送',
    'delivered': '已送达',
    'read': '已读',
    'allow': '允许',
    'deny': '拒绝',
    'outcome': '结果',
    'send': '发送',
    'receive': '接收',
    'accept': '接受',
    'reject': '拒绝',
    'request': '请求',
    'bond request': '绑定请求',
    'pairing': '配对',
    'QR code': '二维码',
    'invitation link': '邀请链接',
    'proof': '证明',
    'introduction': '介绍',
    'vouch': '担保',
    'mute': '静音',
    'block': '阻止',
    'remove': '移除',
    'restore': '恢复',
    'revoke': '撤销',
    'rotate': '轮换',
    'credentials': '凭证',
    'keys': '密钥',
    'key': '密钥',
    'private key': '私钥',
    'public key': '公钥',
    'keypair': '密钥对',
    'identity': '身份',
    'owner identity': '所有者身份',
    'device identity': '设备身份',
    'agent identity': '智能体身份',
    'peer ID': '对等ID',
    'device certificate': '设备证书',
    'certificate': '证书',
    'backup': '备份',
    'backups': '备份',
    'security': '安全',
    'privacy': '隐私',
    'cost': '成本',
    'budget': '预算',
    'expiry': '过期',
    'termination policy': '终止策略',
    'startup': '启动',
    'restart': '重启',
    'upgrade': '升级',
    'update': '更新',
    'uninstall': '卸载',
    'notarization': '公证',
    'firewall prompts': '防火墙提示',
    'Windows Firewall': 'Windows防火墙',
    'encrypted': '加密',
    'integrity': '完整性',
    'replay': '重放',
    'rate-limited': '速率限制',
    'latency': '延迟',
    'sync': '同步',
    'automation': '自动化',
    'orchestration': '编排',
    'orchestrator': '编排器',
    'delegation': '委托',
    'delegate': '委托',
    'in-app': '应用内',
    'microphone': '麦克风',
    'audio clip': '音频片段',
    'recording': '录制',
    'playback': '播放',
    'remote': '远程',
    'remote control': '远程控制',
}

SECTION_TRANSLATIONS = {
    '# EnvoyMesh Guidebook': '# EnvoyMesh 指南',
    '**Version:**': '**版本：**',
    '**Edition:**': '**版本类型：**',
    '**Revised:**': '**修订日期：**',
    '**Languages:**': '**语言：**',
    '**Audience:**': '**受众：**',
    '**Purpose:**': '**目的：**',
    '## How to read this guide': '## 如何阅读本指南',
    '## Feature status labels': '## 功能状态标签',
    '## Product terminology used in this guide': '## 本指南使用的产品术语',
    '# Table of Contents': '# 目录',
    '## Part I — Discover EnvoyMesh': '## 第一部分 — 认识 EnvoyMesh',
    '### 1. Welcome to EnvoyMesh': '### 1. 欢迎来到 EnvoyMesh',
    '#### 1.1 A private network for people and AI agents': '#### 1.1 面向人类和AI智能体的私有网络',
    '#### 1.2 Local-first and peer-to-peer by design': '#### 1.2 设计上优先本地和点对点',
    '#### 1.3 No central account required': '#### 1.3 无需中央账户',
    '#### 1.4 Your identity, relationships, and data belong to you': '#### 1.4 您的身份、关系和数据属于您自己',
    '#### 1.5 Direct connections and optional relays': '#### 1.5 直接连接和可选中继',
    '#### 1.6 Personal agents and external agents': '#### 1.6 个人智能体和外部智能体',
    '#### 1.7 Trusted multi-agent collaboration': '#### 1.7 可信多智能体协作',
    '#### 1.8 Open protocols and interoperability': '#### 1.8 开放协议和互操作性',
    '#### 1.9 Major features at a glance': '#### 1.9 主要功能一览',
    '#### 1.10 Current availability and limitations': '#### 1.10 当前可用性和限制',
    '### 2. Why EnvoyMesh?': '### 2. 为什么选择 EnvoyMesh？',
    '#### 2.1 Private communication without a central platform': '#### 2.1 无需中央平台的私密通信',
    '#### 2.2 Self-sovereign identity across your devices': '#### 2.2 跨设备的自主身份',
    '#### 2.3 AI assistance under your control': '#### 2.3 由您掌控的AI助手',
    '#### 2.4 Trusted knowledge sharing': '#### 2.4 可信知识共享',
    '#### 2.5 Safe task delegation': '#### 2.5 安全的任务委托',
    '#### 2.6 Collaboration among agents you choose': '#### 2.6 您选择的智能体之间的协作',
    '#### 2.7 Local models, remote models, and external agents': '#### 2.7 本地模型、远程模型和外部智能体',
    '#### 2.8 Auditability instead of invisible automation': '#### 2.8 可审计性而非隐形自动化',
    '#### 2.9 When EnvoyMesh is the right choice': '#### 2.9 何时适合使用 EnvoyMesh',
    '#### 2.10 When another solution may be a better fit': '#### 2.10 何时其他解决方案更合适',
    '### 3. What You Can Do': '### 3. 您可以做什么',
    '#### 3.1 Connect with trusted people': '#### 3.1 与信任的人建立连接',
    '#### 3.2 Exchange private messages': '#### 3.2 交换私密消息',
    '#### 3.3 Create group conversations': '#### 3.3 创建群组对话',
    '#### 3.4 Send audio messages and make voice calls': '#### 3.4 发送语音消息和进行语音通话',
    '#### 3.5 Share files and profile photos': '#### 3.5 共享文件和资料照片',
    '#### 3.6 Talk to your personal AI agent': '#### 3.6 与您的个人AI智能体对话',
    '#### 3.7 Connect OpenClaw, HomeClaw, Hermes, or OpenHuman': '#### 3.7 连接 OpenClaw、HomeClaw、Hermes 或 OpenHuman',
    '#### 3.8 Search local and trusted knowledge': '#### 3.8 搜索本地和可信知识',
    '#### 3.9 Publish and browse mesh content': '#### 3.9 发布和浏览网络内容',
    '#### 3.10 Delegate work to another agent': '#### 3.10 将工作委托给另一个智能体',
    '#### 3.11 Run Team jobs across several agents': '#### 3.11 在多个智能体上运行团队任务',
    '#### 3.12 Connect MCP and A2A applications': '#### 3.12 连接 MCP 和 A2A 应用',
    '#### 3.13 Use terminals remotely': '#### 3.13 远程使用终端',
    '#### 3.14 Operate a private or community relay': '#### 3.14 运行私有或社区中继',
    '### 4. How EnvoyMesh Works': '### 4. EnvoyMesh 如何工作',
    '#### 4.1 A plain-language system overview': '#### 4.1 系统概览（通俗易懂版）',
    '#### 4.2 Owners, devices, agents, and peers': '#### 4.2 所有者、设备、智能体和对等节点',
    '#### 4.3 Contacts, bonds, and trust levels': '#### 4.3 联系人、绑定和信任等级',
    '#### 4.4 Signed messages and verifiable senders': '#### 4.4 签名消息和可验证发送者',
    '#### 4.5 Personal agents and external-agent bridges': '#### 4.5 个人智能体和外部智能体桥接',
    '#### 4.6 Local knowledge, the Library, and the Vault': '#### 4.6 本地知识、库和保险库',
    '#### 4.7 Tasks, mandates, and approvals': '#### 4.7 任务、授权和审批',
    '#### 4.8 Agent Network membership': '#### 4.8 智能体网络成员资格',
    '#### 4.9 Direct networking and relay assistance': '#### 4.9 直接网络和中继协助',
    '#### 4.10 Activity records and end-to-end auditing': '#### 4.10 活动记录和端到端审计',
    '### 5. Common Use Cases': '### 5. 常见用例',
    '#### 5.1 A private personal AI across devices': '#### 5.1 跨设备的私密个人AI',
    '#### 5.2 A family or friends mesh': '#### 5.2 家庭或朋友网络',
    '#### 5.3 Trusted research and knowledge exchange': '#### 5.3 可信研究和知识交流',
    '#### 5.4 A small-team Agent Network': '#### 5.4 小型团队智能体网络',
    '#### 5.5 Multi-agent planning and report generation': '#### 5.5 多智能体规划和报告生成',
    '#### 5.6 OpenClaw with trusted mesh contacts': '#### 5.6 与可信网络联系人一起使用 OpenClaw',
    '#### 5.7 HomeClaw as an external EnvoyMesh agent': '#### 5.7 将 HomeClaw 作为外部 EnvoyMesh 智能体',
    '#### 5.8 Hermes as an external EnvoyMesh agent': '#### 5.8 将 Hermes 作为外部 EnvoyMesh 智能体',
    '#### 5.9 OpenHuman as an external EnvoyMesh agent': '#### 5.9 将 OpenHuman 作为外部 EnvoyMesh 智能体',
    '#### 5.10 Claude Desktop using EnvoyMesh through MCP': '#### 5.10 通过 MCP 使用 EnvoyMesh 的 Claude Desktop',
    '#### 5.11 External A2A clients delegating tasks': '#### 5.11 委托任务的外部 A2A 客户端',
    '#### 5.12 A self-hosted relay fleet': '#### 5.12 自托管中继集群',
    '### 6. Product and Protocol Comparisons': '### 6. 产品和协议比较',
    '#### 6.1 EnvoyMesh and centralized messengers': '#### 6.1 EnvoyMesh 与集中式信使',
    '#### 6.2 EnvoyMesh and cloud AI assistants': '#### 6.2 EnvoyMesh 与云AI助手',
    '#### 6.3 EnvoyMesh and standalone OpenClaw': '#### 6.3 EnvoyMesh 与独立 OpenClaw',
    '#### 6.4 EnvoyMesh and external agent runtimes': '#### 6.4 EnvoyMesh 与外部智能体运行时',
    '#### 6.5 EnvoyMesh and MCP': '#### 6.5 EnvoyMesh 与 MCP',
    '#### 6.6 EnvoyMesh and A2A': '#### 6.6 EnvoyMesh 与 A2A',
    '#### 6.7 EnvoyMesh native Agent Network versus public marketplaces': '#### 6.7 EnvoyMesh 原生智能体网络与公共市场',
    '#### 6.8 Native protocols versus interoperability bridges': '#### 6.8 原生协议与互操作性桥接',
    '## Part II — Install and Get Started': '## 第二部分 — 安装和入门',
    '### 7. Choose Your Setup': '### 7. 选择您的设置',
    '#### 7.1 Desktop only': '#### 7.1 仅桌面',
    '#### 7.2 Desktop with EnvoyGo mobile access': '#### 7.2 桌面配合 EnvoyGo 移动访问',
    '#### 7.3 Desktop with the bundled EnvoyAI agent': '#### 7.3 桌面配合捆绑的 EnvoyAI 智能体',
    '#### 7.4 Desktop with an external agent': '#### 7.4 桌面配合外部智能体',
    '#### 7.5 Desktop with local or remote models': '#### 7.5 桌面配合本地或远程模型',
    '#### 7.6 Personal relay or community relay': '#### 7.6 个人中继或社区中继',
    '#### 7.7 Small-team and organization deployments': '#### 7.7 小型团队和组织部署',
    '#### 7.8 Recommended first-time setup': '#### 7.8 推荐的首次设置',
    '### 8. Install EnvoyMesh': '### 8. 安装 EnvoyMesh',
    '#### 8.1 System requirements': '#### 8.1 系统要求',
    '#### 8.2 Install on macOS': '#### 8.2 在 macOS 上安装',
    '#### 8.3 Install on Windows': '#### 8.3 在 Windows 上安装',
    '#### 8.4 Install EnvoyGo on iOS': '#### 8.4 在 iOS 上安装 EnvoyGo',
    '#### 8.5 Install EnvoyGo on Android': '#### 8.5 在 Android 上安装 EnvoyGo',
    '#### 8.6 Install from source': '#### 8.6 从源码安装',
    '#### 8.7 Verify the installation': '#### 8.7 验证安装',
    '#### 8.8 Application data locations': '#### 8.8 应用数据位置',
    '#### 8.9 Update EnvoyMesh': '#### 8.9 更新 EnvoyMesh',
    '#### 8.10 Uninstall without losing identity or data': '#### 8.10 卸载而不丢失身份或数据',
    '### 9. Platform and Package Differences': '### 9. 平台和包差异',
    '#### 9.1 Desktop and mobile feature comparison': '#### 9.1 桌面和移动功能比较',
    '#### 9.2 macOS packaging': '#### 9.2 macOS 打包',
    '#### 9.3 Windows packaging': '#### 9.3 Windows 打包',
    '#### 9.4 OpenClaw extensions bundled on macOS': '#### 9.4 macOS 上捆绑的 OpenClaw 扩展',
    '#### 9.5 Essential OpenClaw extension selection on Windows': '#### 9.5 Windows 上的必要 OpenClaw 扩展选择',
    '#### 9.6 Full and slim desktop bundles': '#### 9.6 完整和精简桌面包',
    '#### 9.7 Optional IPFS sidecars': '#### 9.7 可选 IPFS 辅助组件',
    '#### 9.8 Features requiring a home node': '#### 9.8 需要主节点的功能',
    '#### 9.9 Features available as an EnvoyGo mobile mirror': '#### 9.9 EnvoyGo 移动镜像可用的功能',
    '#### 9.10 Legacy mobile experiments and current product boundaries': '#### 9.10 遗留移动实验和当前产品边界',
    '### 10. Create Your Identity': '### 10. 创建您的身份',
    '#### 10.1 What your EnvoyMesh identity represents': '#### 10.1 您的 EnvoyMesh 身份代表什么',
    '#### 10.2 Create an owner identity': '#### 10.2 创建所有者身份',
    '#### 10.3 Create your first device identity': '#### 10.3 创建您的第一个设备身份',
    '#### 10.4 Create or activate your agent identity': '#### 10.4 创建或激活您的智能体身份',
    '#### 10.5 Set your display profile': '#### 10.5 设置您的显示资料',
    '#### 10.6 Understand your DID': '#### 10.6 理解您的 DID',
    '#### 10.7 Protect your cryptographic keys': '#### 10.7 保护您的加密密钥',
    '#### 10.8 Back up identity and recovery data': '#### 10.8 备份身份和恢复数据',
    '#### 10.9 Add another device': '#### 10.9 添加另一台设备',
    '#### 10.10 Revoke a lost or compromised device': '#### 10.10 撤销丢失或受损的设备',
    '### 11. Tour the Application': '### 11. 应用程序导览',
    '#### 11.1 Home and node status': '#### 11.1 首页和节点状态',
    '#### 11.2 Conversations': '#### 11.2 对话',
    '#### 11.3 Contacts and discovery': '#### 11.3 联系人与发现',
    '#### 11.4 Groups': '#### 11.4 群组',
    '#### 11.5 Knowledge Base and Library': '#### 11.5 知识库和库',
    '#### 11.6 Browser': '#### 11.6 浏览器',
    '#### 11.7 Team jobs': '#### 11.7 团队任务',
    '#### 11.8 Terminals': '#### 11.8 终端',
    '#### 11.9 Approvals and activity': '#### 11.9 审批和活动',
    '#### 11.10 Profile': '#### 11.10 资料',
    '#### 11.11 Settings': '#### 11.11 设置',
    '#### 11.12 Connection and agent status indicators': '#### 11.12 连接和智能体状态指示器',
    '### 12. Connect Your First Contact': '### 12. 连接您的第一个联系人',
    '#### 12.1 What pairing and bonding do': '#### 12.1 配对和绑定的作用',
    '#### 12.2 Pair with a QR code': '#### 12.2 使用二维码配对',
    '#### 12.3 Pair with an invitation link': '#### 12.3 使用邀请链接配对',
    '#### 12.4 Pair on a local network': '#### 12.4 在本地网络上配对',
    '#### 12.5 Verify identity information': '#### 12.5 验证身份信息',
    '#### 12.6 Choose an appropriate trust level': '#### 12.6 选择适当的信任等级',
    '#### 12.7 Accept a bond request': '#### 12.7 接受绑定请求',
    '#### 12.8 Send the first message': '#### 12.8 发送第一条消息',
    '#### 12.9 Confirm direct or relay-assisted delivery': '#### 12.9 确认直接或中继辅助送达',
    '#### 12.10 Troubleshoot pairing': '#### 12.10 排查配对问题',
    '#### 12.11 Bundled sponsor contact': '#### 12.11 捆绑的赞助商联系人',
    '### 13. Connect EnvoyGo': '### 13. 连接 EnvoyGo',
    '#### 13.1 How EnvoyGo works with a home node': '#### 13.1 EnvoyGo 如何与主节点协作',
    '#### 13.2 Pair the mobile app': '#### 13.2 配对移动应用',
    '#### 13.3 Confirm the home connection': '#### 13.3 确认主连接',
    '#### 13.4 Use chat and contacts': '#### 13.4 使用聊天和联系人',
    '#### 13.5 Use remote terminals': '#### 13.5 使用远程终端',
    '#### 13.6 View Team jobs': '#### 13.6 查看团队任务',
    '#### 13.7 Browse mesh content': '#### 13.7 浏览网络内容',
    '#### 13.8 Receive notifications': '#### 13.8 接收通知',
    '#### 13.9 Make and receive voice calls': '#### 13.9 拨打和接听语音通话',
    '#### 13.10 Revoke a lost phone': '#### 13.10 撤销丢失的手机',
    '#### 13.11 Current mobile limitations': '#### 13.11 当前移动限制',
    '### 14. First-Day Tutorials': '### 14. 第一天教程',
    '#### 14.1 Send a private message': '#### 14.1 发送私密消息',
    '#### 14.2 Create a group conversation': '#### 14.2 创建群组对话',
    '#### 14.3 Send an audio message': '#### 14.3 发送语音消息',
    '#### 14.4 Make a voice call': '#### 14.4 进行语音通话',
    '#### 14.5 Share a file': '#### 14.5 共享文件',
    '#### 14.6 Ask EnvoyAI a question': '#### 14.6 向 EnvoyAI 提问',
    '#### 14.7 Add knowledge to your Library': '#### 14.7 向您的库中添加知识',
    '#### 14.8 Search your Vault': '#### 14.8 搜索您的保险库',
    '#### 14.9 Ask a bonded agent for knowledge': '#### 14.9 向绑定的智能体询问知识',
    '#### 14.10 Approve a sensitive action': '#### 14.10 审批敏感操作',
    '#### 14.11 Start a simple Team job': '#### 14.11 启动简单的团队任务',
    '#### 14.12 Connect an external agent': '#### 14.12 连接外部智能体',
    '## Part III — People, Profiles, and Conversations': '## 第三部分 — 人员、资料和对话',
    '### 15. Contacts and Bonds': '### 15. 联系人与绑定',
    '#### 15.1 View and search contacts': '#### 15.1 查看和搜索联系人',
    '#### 15.2 Understand contact identity': '#### 15.2 理解联系人身份',
    '#### 15.3 Contact profiles and photos': '#### 15.3 联系人资料和照片',
    '#### 15.4 Online, offline, and connection states': '#### 15.4 在线、离线和连接状态',
    '#### 15.5 Direct, referred, public, and blocked trust': '#### 15.5 直接、推荐、公开和阻止信任',
    '#### 15.6 Change a contact’s trust level': '#### 15.6 更改联系人的信任等级',
    '#### 15.7 Refer or introduce a contact': '#### 15.7 推荐或介绍联系人',
    '#### 15.8 Mute, block, or remove a contact': '#### 15.8 静音、阻止或移除联系人',
    '#### 15.9 Restore a connection': '#### 15.9 恢复连接',
    '#### 15.10 Contact privacy and disclosure settings': '#### 15.10 联系人隐私和披露设置',
    '### 16. Private Messaging': '### 16. 私密消息',
    '#### 16.1 Start a conversation': '#### 16.1 开始对话',
    '#### 16.2 Human-to-human messages': '#### 16.2 人对人消息',
    '#### 16.3 Human-to-agent messages': '#### 16.3 人对智能体消息',
    '#### 16.4 Replies and conversation continuity': '#### 16.4 回复和对话连续性',
    '#### 16.5 Message delivery states': '#### 16.5 消息送达状态',
    '#### 16.6 Offline behavior and retries': '#### 16.6 离线行为和重试',
    '#### 16.7 Search conversation history': '#### 16.7 搜索对话历史',
    '#### 16.8 Draft assistance': '#### 16.8 草稿辅助',
    '#### 16.9 Manage conversation data': '#### 16.9 管理对话数据',
    '#### 16.10 Message privacy and security': '#### 16.10 消息隐私和安全',
    '### 17. Group Conversations': '### 17. 群组对话',
    '#### 17.1 Create a group': '#### 17.1 创建群组',
    '#### 17.2 Invite members': '#### 17.2 邀请成员',
    '#### 17.3 Send group messages': '#### 17.3 发送群组消息',
    '#### 17.4 Manage membership': '#### 17.4 管理成员',
    '#### 17.5 Leave a group': '#### 17.5 离开群组',
    '#### 17.6 Group trust boundaries': '#### 17.6 群组信任边界',
    '#### 17.7 Group delivery and offline members': '#### 17.7 群组送达和离线成员',
    '#### 17.8 Group troubleshooting': '#### 17.8 群组排查',
    '### 18. Audio and Voice Calls': '### 18. 音频和语音通话',
    '#### 18.1 Record and send an audio message': '#### 18.1 录制和发送语音消息',
    '#### 18.2 Play and manage audio attachments': '#### 18.2 播放和管理音频附件',
    '#### 18.3 Start a voice call': '#### 18.3 发起语音通话',
    '#### 18.4 Answer or decline a call': '#### 18.4 接听或拒绝通话',
    '#### 18.5 Call status and controls': '#### 18.5 通话状态和控制',
    '#### 18.6 Background calls and mobile notifications': '#### 18.6 后台通话和移动通知',
    '#### 18.7 STUN and TURN connectivity': '#### 18.7 STUN 和 TURN 连接',
    '#### 18.8 Call privacy': '#### 18.8 通话隐私',
    '#### 18.9 Voice-call troubleshooting': '#### 18.9 语音通话排查',
    '#### 18.10 Video calls — planned, not currently available': '#### 18.10 视频通话 — 计划中，当前不可用',
    '### 19. Files, Photos, and Profile Sharing': '### 19. 文件、照片和资料共享',
    '#### 19.1 Share a file': '#### 19.1 共享文件',
    '#### 19.2 Accept or decline an incoming share': '#### 19.2 接受或拒绝传入的共享',
    '#### 19.3 Check transfer progress': '#### 19.3 检查传输进度',
    '#### 19.4 Verify file integrity': '#### 19.4 验证文件完整性',
    '#### 19.5 Share profile photos': '#### 19.5 共享资料照片',
    '#### 19.6 Manage your profile gallery': '#### 19.6 管理您的资料图库',
    '#### 19.7 Choose visibility and sensitivity': '#### 19.7 选择可见性和敏感度',
    '#### 19.8 Remove shared content': '#### 19.8 移除共享内容',
    '#### 19.9 Troubleshoot file transfers': '#### 19.9 排查文件传输',
    '### 20. Profiles and Presence': '### 20. 资料和在线状态',
    '#### 20.1 Edit your human profile': '#### 20.1 编辑您的人类资料',
    '#### 20.2 Edit your agent profile': '#### 20.2 编辑您的智能体资料',
    '#### 20.3 Display names and descriptions': '#### 20.3 显示名称和描述',
    '#### 20.4 Profile photos and galleries': '#### 20.4 资料照片和图库',
    '#### 20.5 Identity details and DIDs': '#### 20.5 身份详情和 DID',
    '#### 20.6 What bonded contacts can see': '#### 20.6 绑定联系人可以看到什么',
    '#### 20.7 Profile synchronization': '#### 20.7 资料同步',
    '#### 20.8 Privacy defaults': '#### 20.8 隐私默认值',
    '## Part IV — Your Personal AI': '## 第四部分 — 您的个人AI',
    '### 21. Meet EnvoyAI': '### 21. 认识 EnvoyAI',
    '#### 21.1 What EnvoyAI is': '#### 21.1 EnvoyAI 是什么',
    '#### 21.2 OpenClaw as the bundled agent runtime': '#### 21.2 作为捆绑智能体运行时的 OpenClaw',
    '#### 21.3 How EnvoyAI differs from the external-agent bridge': '#### 21.3 EnvoyAI 与外部智能体桥接的区别',
    '#### 21.4 What EnvoyAI can access': '#### 21.4 EnvoyAI 可以访问什么',
    '#### 21.5 Mesh tools available to EnvoyAI': '#### 21.5 EnvoyAI 可用的网络工具',
    '#### 21.6 Policy and approval controls': '#### 21.6 策略和审批控制',
    '#### 21.7 Start, stop, and inspect the agent': '#### 21.7 启动、停止和检查智能体',
    '#### 21.8 Current limitations': '#### 21.8 当前限制',
    '### 22. AI Engine Modes': '### 22. AI 引擎模式',
    '#### 22.1 Built-in only': '#### 22.1 仅内置',
    '#### 22.2 Built-in plus external agent': '#### 22.2 内置加外部智能体',
    '#### 22.3 External agent only': '#### 22.3 仅外部智能体',
    '#### 22.4 No AI': '#### 22.4 无 AI',
    '#### 22.5 Choose the right mode': '#### 22.5 选择正确的模式',
    '#### 22.6 Change the active external agent': '#### 22.6 更改活动的外部智能体',
    '#### 22.7 Startup settings versus runtime settings': '#### 22.7 启动设置与运行时设置',
    '#### 22.8 Diagnose agent availability': '#### 22.8 诊断智能体可用性',
    '### 23. Models and Providers': '### 23. 模型和提供商',
    '#### 23.1 Model routing overview': '#### 23.1 模型路由概述',
    '#### 23.2 Configure a local model': '#### 23.2 配置本地模型',
    '#### 23.3 Configure a remote provider': '#### 23.3 配置远程提供商',
    '#### 23.4 Configure LiteLLM': '#### 23.4 配置 LiteLLM',
    '#### 23.5 Choose a default model': '#### 23.5 选择默认模型',
    '#### 23.6 Configure fallback behavior': '#### 23.6 配置回退行为',
    '#### 23.7 Context-window considerations': '#### 23.7 上下文窗口考虑',
    '#### 23.8 Provider privacy': '#### 23.8 提供商隐私',
    '#### 23.9 Cost controls': '#### 23.9 成本控制',
    '#### 23.10 Troubleshoot model calls': '#### 23.10 排查模型调用',
    '### 24. Agent Style, Mode, and Contact Behavior': '### 24. 智能体风格、模式和联系人行为',
    '#### 24.1 Agent communication style': '#### 24.1 智能体沟通风格',
    '#### 24.2 Agent operating modes': '#### 24.2 智能体操作模式',
    '#### 24.3 Per-contact modes': '#### 24.3 每联系人模式',
    '#### 24.4 Per-contact disclosure rules': '#### 24.4 每联系人披露规则',
    '#### 24.5 Social proxy behavior': '#### 24.5 社交代理行为',
    '#### 24.6 Proactive check-ins': '#### 24.6 主动检查',
    '#### 24.7 Pause or restrict automation': '#### 24.7 暂停或限制自动化',
    '#### 24.8 Reset agent behavior': '#### 24.8 重置智能体行为',
    '### 25. Sessions and Memory': '### 25. 会话和记忆',
    '#### 25.1 What a session is': '#### 25.1 会话是什么',
    '#### 25.2 Conversation context': '#### 25.2 对话上下文',
    '#### 25.3 Short-term and long-term memory': '#### 25.3 短期和长期记忆',
    '#### 25.4 Search memory': '#### 25.4 搜索记忆',
    '#### 25.5 Session summaries': '#### 25.5 会话摘要',
    '#### 25.6 Correct outdated memory': '#### 25.6 纠正过时记忆',
    '#### 25.7 Delete memory': '#### 25.7 删除记忆',
    '#### 25.8 Retention and privacy': '#### 25.8 保留和隐私',
    '#### 25.9 Memory across devices': '#### 25.9 跨设备记忆',
    '#### 25.10 Current chat-history integration boundaries': '#### 25.10 当前聊天历史集成边界',
    '### 26. Tools': '### 26. 工具',
    '#### 26.1 What an agent tool is': '#### 26.1 智能体工具是什么',
    '#### 26.2 Browse available mesh tools': '#### 26.2 浏览可用的网络工具',
    '#### 26.3 Knowledge and Library tools': '#### 26.3 知识和库工具',
    '#### 26.4 Contact and messaging tools': '#### 26.4 联系人和消息工具',
    '#### 26.5 File-sharing tools': '#### 26.5 文件共享工具',
    '#### 26.6 Task and Agent Network tools': '#### 26.6 任务和智能体网络工具',
    '#### 26.7 Approval and escalation tools': '#### 26.7 审批和升级工具',
    '#### 26.8 MCP tools': '#### 26.8 MCP 工具',
    '#### 26.9 Enable or disable access': '#### 26.9 启用或禁用访问',
    '#### 26.10 Review tool executions': '#### 26.10 查看工具执行',
    '### 27. Triggers, Schedules, and Digests': '### 27. 触发器、计划和摘要',
    '#### 27.1 Create a trigger': '#### 27.1 创建触发器',
    '#### 27.2 Update or remove a trigger': '#### 27.2 更新或移除触发器',
    '#### 27.3 Schedule reminders and actions': '#### 27.3 计划提醒和操作',
    '#### 27.4 Configure activity digests': '#### 27.4 配置活动摘要',
    '#### 27.5 Morning reports and discovery summaries': '#### 27.5 早晨报告和发现摘要',
    '#### 27.6 Follow-ups and proactive checks': '#### 27.6 跟进和主动检查',
    '#### 27.7 Quiet hours and notification preferences': '#### 27.7 安静时间和通知偏好',
    '#### 27.8 Review automation history': '#### 27.8 查看自动化历史',
    '#### 27.9 Stop an automation': '#### 27.9 停止自动化',
    '### 28. Approvals and Escalations': '### 28. 审批和升级',
    '#### 28.1 Why EnvoyMesh asks for approval': '#### 28.1 为什么 EnvoyMesh 需要审批',
    '#### 28.2 Review a pending action': '#### 28.2 查看待处理操作',
    '#### 28.3 Check the contact, data, and capability scope': '#### 28.3 检查联系人、数据和能力范围',
    '#### 28.4 Approve an action': '#### 28.4 批准操作',
    '#### 28.5 Reject one or all actions': '#### 28.5 拒绝一个或所有操作',
    '#### 28.6 Escalation reasons': '#### 28.6 升级原因',
    '#### 28.7 Acknowledge an escalation': '#### 28.7 确认升级',
    '#### 28.8 Expired approvals': '#### 28.8 过期审批',
    '#### 28.9 Agent Network award approvals': '#### 28.9 智能体网络奖励审批',
    '#### 28.10 Avoid approval fatigue': '#### 28.10 避免审批疲劳',
    '## Part V — Knowledge, Library, and the Web': '## 第五部分 — 知识、库和网络',
    '### 29. Knowledge System Overview': '### 29. 知识系统概述',
    '#### 29.1 Knowledge Base, Library, Vault, and RAG': '#### 29.1 知识库、库、保险库和 RAG',
    '#### 29.2 Local-first storage': '#### 29.2 本地优先存储',
    '#### 29.3 Notes, files, and structured information': '#### 29.3 笔记、文件和结构化信息',
    '#### 29.4 Visibility and sensitivity': '#### 29.4 可见性和敏感度',
    '#### 29.5 Search and retrieval': '#### 29.5 搜索和检索',
    '#### 29.6 Trusted remote knowledge': '#### 29.6 可信远程知识',
    '#### 29.7 Provenance and hashes': '#### 29.7 来源和哈希',
    '#### 29.8 Publishing and browsing': '#### 29.8 发布和浏览',
    '#### 29.9 IPFS integration': '#### 29.9 IPFS 集成',
    '### 30. Create and Organize Knowledge': '### 30. 创建和组织知识',
    '#### 30.1 Create a Markdown note': '#### 30.1 创建 Markdown 笔记',
    '#### 30.2 Edit and preview a note': '#### 30.2 编辑和预览笔记',
    '#### 30.3 Organize folders': '#### 30.3 组织文件夹',
    '#### 30.4 Add files': '#### 30.4 添加文件',
    '#### 30.5 Choose public, friends, trusted, or private visibility': '#### 30.5 选择公开、朋友、可信或私密可见性',
    '#### 30.6 Manage metadata': '#### 30.6 管理元数据',
    '#### 30.7 Use the Obsidian integration': '#### 30.7 使用 Obsidian 集成',
    '#### 30.8 Import and export content': '#### 30.8 导入和导出内容',
    '#### 30.9 Delete knowledge safely': '#### 30.9 安全删除知识',
}

SENTENCE_TRANSLATIONS = {
    'This guide reflects the EnvoyMesh 0.1.0 repository state at the revision date.': '本指南反映了修订日期时 EnvoyMesh 0.1.0 存储库的状态。',
    'It is written for end users, not as a content-outline stub.': '它是为最终用户编写的，而不是作为内容大纲存根。',
    'Feature status can differ by platform and deployment—verify each Beta or Experimental capability in your build (release notes, Settings labels, and Appendix J) before relying on it in production.': '功能状态可能因平台和部署而异——在生产中依赖它之前，请验证您的构建（版本说明、设置标签和附录J）中的每个Beta或实验性功能。',
    '- **Parts I–XIV** explain the product for end users and operators.': '- **第一至十四部分**向最终用户和操作员解释该产品。',
    '- **Part XV** is for website editors and content operators and is optional for end users.': '- **第十五部分**适用于网站编辑和内容运营商，对于最终用户来说是可选的。',
    'Task lifecycle names such as *Created* / *Task planned* / *Running* are EnvoyMesh states, not product **Planned** / **Available** status labels.': '任务生命周期名称（例如*已创建* / *任务已计划* / *运行中*）是 EnvoyMesh 状态，而不是产品**计划中** / **可用**状态标签。',
    '- **Mobile** in this guide means **EnvoyGo** (thin client paired to a home node), unless a section explicitly discusses legacy mobile experiments.': '- 本指南中的**移动**指的是**EnvoyGo**（与主节点配对的瘦客户端），除非某节明确讨论遗留移动实验。',
    '- **Available** — implemented and intended for current use.': '- **可用** — 已实施并供当前使用。',
    '- **Beta** — implemented, but still receiving validation or product polish.': '- **Beta** — 已实施，但仍在接受验证或产品完善。',
    '- **Experimental** — usable for evaluation; behavior or interfaces may change.': '- **实验性** — 可用于评估；行为或界面可能会改变。',
    '- **Compatibility preset** — EnvoyMesh includes configuration for the integration, while part of the integration is maintained by another project.': '- **兼容性预设** — EnvoyMesh 包括集成的配置，而部分集成由另一个项目维护。',
    '- **Planned** — designed or documented, but not currently available as a complete product feature.': '- **计划中** — 已设计或记录，但目前不作为完整的产品功能提供。',
    '- **Parked** — intentionally deferred without a committed release date.': '- **暂停** — 有意推迟，没有承诺的发布日期。',
    '- **Desktop** — available through the EnvoyMesh desktop application or home node.': '- **桌面** — 通过 EnvoyMesh 桌面应用程序或主节点可用。',
    '- **Mobile** — available in EnvoyGo, the current EnvoyMesh mobile product (home-paired thin client).': '- **移动** — 在当前的 EnvoyMesh 移动产品 EnvoyGo（与家庭配对的瘦客户端）中可用。',
    '- **Operator** — intended for node, relay, or fleet administrators.': '- **操作员** — 适用于节点、中继或集群管理员。',
    '- **EnvoyAI / OpenClaw** is the richer bundled agent integration included with EnvoyMesh.': '- **EnvoyAI / OpenClaw**是 EnvoyMesh 中包含的更丰富的捆绑智能体集成。',
    '- **HomeClaw** and **Hermes** are built-in external-agent compatibility presets.': '- **HomeClaw**和**Hermes**是内置的外部智能体兼容性预设。',
    '- **OpenHuman** is a built-in compatibility preset that is disabled by default.': '- **OpenHuman**是内置兼容性预设，默认为禁用状态。',
    'Agent-side code for HomeClaw, Hermes, and OpenHuman is maintained by their respective projects; EnvoyMesh provides the bridge, presets, policy boundary, and mesh tools.': 'HomeClaw、Hermes 和 OpenHuman 的智能体端代码由各自的项目维护；EnvoyMesh 提供桥接、预设、策略边界和网络工具。',
    '- **Agent Network** means bonded people allowing their opted-in local agents to collaborate.': '- **智能体网络**指的是绑定的人员允许其选择加入的本地智能体进行协作。',
    'It is not a public agent marketplace.': '它不是公共智能体市场。',
    '- **Team jobs** is the user-facing name for multi-agent collaboration.': '- **团队任务**是多智能体协作的面向用户的名称。',
    'Source code and older documentation may call these workflows **chains**.': '源代码和旧文档可能将这些工作流程称为**链**。',
    '- **EnvoyGo** is the current mobile product: a thin client that pairs to a home EnvoyMesh node.': '- **EnvoyGo**是当前的移动产品：与主 EnvoyMesh 节点配对的瘦客户端。',
    'The earlier Capacitor mobile tree (in-process full node) is a legacy experiment and is not the primary mobile application.': '早期的 Capacitor 移动树（进程内全节点）是一个遗留实验，不是主要的移动应用程序。',
    'Running EnvoyGo itself as a full mesh node is parked (Appendix J.6).': '将 EnvoyGo 本身作为全网格节点运行已暂停（附录J.6）。',
    'EnvoyMesh connects people and AI agents through a private mesh rather than a central account service.': 'EnvoyMesh 通过私有网络而不是中央账户服务连接人员和AI智能体。',
    'Each participant keeps a local identity, chooses trusted contacts (bonded at one of four user-selectable trust tiers — blocked, public, referred, or direct; `self` is the implicit tier for your own owner, devices, and agents), and decides which agents, tools, and information may cross those relationships.': '每个参与者保留本地身份，选择可信联系人（绑定在四个用户可选的信任等级之一——阻止、公开、推荐或直接；`self`是您自己的所有者、设备和智能体的隐式等级），并决定哪些智能体、工具和信息可以跨越这些关系。',
    'The home node stores identity, policy, conversations, tasks, and knowledge locally.': '主节点本地存储身份、策略、对话、任务和知识。',
    'Peer-to-peer transport is preferred, so routine communication does not depend on a hosted application database.': '点对点传输是首选，因此常规通信不依赖托管应用程序数据库。',
    'You create cryptographic identities instead of registering a global username and password.': '您创建加密身份，而不是注册全局用户名和密码。',
    'Public relays may help peers find and reach each other, but they are not an account authority.': '公共中继可以帮助对等节点找到并联系彼此，但它们不是账户权威。',
    'Owner keys establish control, bonds record relationships, and sensitivity labels protect data.': '所有者密钥建立控制，绑定记录关系，敏感度标签保护数据。',
    'Backups therefore matter: losing the only copy of an owner key can mean losing continuity of that identity.': '因此备份很重要：丢失所有者密钥的唯一副本可能意味着失去该身份的连续性。',
    'EnvoyMesh first attempts a direct peer path.': 'EnvoyMesh 首先尝试直接对等路径。',
    'When NAT, firewalls, or mobility prevent that path, an optional relay supplies rendezvous and forwarding without becoming the application brain.': '当NAT、防火墙或移动性阻止该路径时，可选中继提供会合和转发，而不会成为应用程序的核心。',
    'EnvoyAI is the bundled OpenClaw-based assistant.': 'EnvoyAI 是基于捆绑的 OpenClaw 的助手。',
    'A separate bridge can connect HomeClaw, Hermes, OpenHuman, or a custom HTTP agent without giving that external process raw P2P keys.': '一个独立的桥接可以连接 HomeClaw、Hermes、OpenHuman 或自定义 HTTP 智能体，而无需向该外部进程提供原始 P2P 密钥。',
    'Agent Network lets bonded owners opt their local agents into Team jobs.': '智能体网络允许绑定的所有者选择他们的本地智能体参与团队任务。',
    'The requesting node plans work, eligible workers execute locally, and the orchestrator combines attributed results.': '请求节点计划工作，合格的工作者在本地执行，编排器合并归因结果。',
    'Native signed EnvoyMesh envelopes remain the internal protocol.': '本地签名的 EnvoyMesh 信封仍然是内部协议。',
    'MCP exposes tools to compatible applications, while A2A publishes agent discovery and task interfaces at the network edge.': 'MCP 向兼容的应用程序公开工具，而 A2A 在网络边缘发布智能体发现和任务接口。',
    'Available areas include messaging, groups, audio, voice calls, files, profiles, personal AI, knowledge and RAG, external-agent bridges, Team jobs, terminals, Browser, relays, MCP, and A2A.': '可用领域包括消息传递、群组、音频、语音通话、文件、资料、个人AI、知识和RAG、外部智能体桥接、团队任务、终端、浏览器、中继、MCP和A2A。',
    'Some capabilities remain platform-specific or deferred.': '某些功能仍然特定于平台或被推迟。',
    'In particular, video calls, broad anonymous worker recruitment, full-node EnvoyGo operation, global reputation, commerce, Filecoin persistence, and a complete hierarchical relay graph are not current general features.': '特别是，视频通话、广泛的匿名工作者招募、全节点 EnvoyGo 操作、全球声誉、商业、Filecoin 持久化和完整的分层中继图不是当前的一般功能。',
    'EnvoyMesh treats messaging as signed peer traffic rather than rows in a hosted database.': 'EnvoyMesh 将消息传递视为签名的对等流量，而不是托管数据库中的行。',
    'You choose who appears in your contact list, and conversations stay on devices you control unless you explicitly share outward.': '您选择谁出现在您的联系人列表中，对话保留在您控制的设备上，除非您明确向外共享。',
    'This differs from centralized messengers that can change terms, scan content, or freeze accounts without your keys.': '这与集中式信使不同，集中式信使可以在没有您的密钥的情况下更改条款、扫描内容或冻结账户。',
    'Your owner identity is an Ed25519 keypair, not a username registered by a vendor.': '您的所有者身份是一个 Ed25519 密钥对，而不是供应商注册的用户名。',
    'Devices and agents derive from that owner with signed certificates and mandates, so you can prove continuity across laptops, desktops, and paired phones.': '设备和智能体通过签名证书和授权从该所有者派生，因此您可以证明在笔记本电脑、台式机和配对手机之间的连续性。',
    'Losing the only copy of an owner key can end that identity\'s history, so backup and recovery planning matter from day one.': '丢失所有者密钥的唯一副本可能会结束该身份的历史，因此备份和恢复计划从第一天起就很重要。',
    'EnvoyAI and external agents run on your home node under bond policy, mandate limits, and optional human approvals.': 'EnvoyAI 和外部智能体在您的主节点上运行，遵循绑定策略、授权限制和可选的人工审批。',
    'You decide which models, tools, and contacts an agent may use instead of accepting a vendor\'s default automation scope.': '您决定智能体可以使用哪些模型、工具和联系人，而不是接受供应商的默认自动化范围。',
    'Remote model providers receive only prompts the node approves after its semantic firewall and policy checks.': '远程模型提供商只接收节点在其语义防火墙和策略检查后批准的提示。',
    'Notes and files live in your Vault, appear in the Library UI, and can be shared with sensitivity labels that the Bonds engine enforces.': '笔记和文件存储在您的保险库中，显示在库界面中，并可以通过绑定引擎强制执行的敏感度标签进行共享。',
    'Bonded contacts can query your public or friends-tier material through `knowledge.query`, while strangers see only the public sub-graph and are rate-limited.': '绑定联系人可以通过`knowledge.query`查询您的公开或朋友级材料，而陌生人只能看到公开子图并受到速率限制。',
    'Publishing for browsing uses separate web-content paths and visibility rules described in Part V.': '用于浏览的发布使用第五部分描述的单独的网页内容路径和可见性规则。',
    'Task delegation uses owner-signed mandates that cap cost, sensitivity, allowed actions, and expiry.': '任务委托使用所有者签名的授权，限制成本、敏感度、允许的操作和过期时间。',
    'An agent cannot silently exceed those bounds; risky steps can require explicit approval before execution.': '智能体不能默默地超出这些界限；有风险的步骤可能需要在执行前获得明确批准。',
    'This makes autonomous work legible rather than a black box running on someone else\'s servers.': '这使得自主工作变得清晰，而不是在别人的服务器上运行的黑匣子。',
    'Agent Network is opt-in collaboration among bonded owners, not an anonymous worker marketplace.': '智能体网络是绑定所有者之间的选择性协作，而不是匿名工作者市场。',
    'Team jobs let your local agent plan work and call workers you already trust, with attributed results returned to the orchestrator.': '团队任务让您的本地智能体计划工作并调用您已经信任的工作者，归因结果返回给编排器。',
    'You stay in control of which contacts\' agents may participate.': '您始终控制哪些联系人的智能体可以参与。',
    'EnvoyMesh supports local inference, configured remote providers, and external HTTP agents such as HomeClaw or Hermes through a single bridge at a time.': 'EnvoyMesh 支持本地推理、配置的远程提供商，以及通过单个桥接同时支持 HomeClaw 或 Hermes 等外部 HTTP 智能体。',
    'The node signs mesh traffic on the agent\'s behalf without handing over Ed25519 keys.': '节点代表智能体对网络流量进行签名，而不移交 Ed25519 密钥。',
    'Mix providers to balance privacy, latency, and capability without locking into one vendor stack.': '混合提供商以平衡隐私、延迟和能力，而不锁定到一个供应商堆栈。',
    'Operations append JSONL audit events with correlation IDs that stitch multi-step flows together.': '操作附加带有关联ID的JSONL审计事件，这些关联ID将多步骤流程缝合在一起。',
    'You can review what an agent attempted, what policy allowed or denied, and which peer participated.': '您可以查看智能体尝试了什么、策略允许或拒绝了什么，以及哪个对等节点参与了。',
    'This audit trail complements chat history when diagnosing automation or sharing disputes.': '在诊断自动化或共享争议时，此审计轨迹补充了聊天历史。',
    'EnvoyMesh fits when you want cryptographic identity, explicit trust tiers, local-first storage, and agent tooling under your policy.': '当您需要加密身份、明确的信任等级、本地优先存储以及在您的策略下的智能体工具时，EnvoyMesh 是合适的选择。',
    'It works well for small trusted groups, personal AI with mesh reach, and teams that need verifiable messaging plus delegated tasks.': '它非常适合小型可信团体、具有网络覆盖范围的个人AI以及需要可验证消息传递和委托任务的团队。',
    'Start with one home node and a few bonded contacts before expanding relays or Agent Network membership.': '在扩展中继或智能体网络成员之前，从一个主节点和几个绑定联系人开始。',
    'A global consumer messenger with effortless signup, massive groups, and vendor-managed moderation may serve you better than running a home node.': '具有轻松注册、庞大群组和供应商管理审核功能的全球消费者信使可能比运行主节点更好地为您服务。',
    'Likewise, if you only need a single cloud chatbot with no peer relationships or local vault, a hosted assistant is simpler.': '同样，如果您只需要一个没有对等关系或本地保险库的云聊天机器人，托管助手会更简单。',
    'EnvoyMesh rewards operators willing to own keys, backups, and trust decisions.': 'EnvoyMesh 奖励愿意拥有密钥、备份和信任决策的操作员。',
    'Add contacts through introductions, QR pairing, or relay-assisted discovery once you verify their public key fingerprint.': '验证联系人的公钥指纹后，通过介绍、二维码配对或中继辅助发现添加联系人。',
    'Bonds record trust tiers—blocked, public, referred, or direct—that gate what each peer may request.': '绑定记录信任等级——阻止、公开、推荐或直接——控制每个对等节点可能请求的内容。',
    'You can upgrade or downgrade trust as relationships change without migrating to a new account.': '当关系发生变化时，您可以升级或降级信任，而无需迁移到新账户。',
    'Send one-to-one chat as signed envelopes with human-to-human role policy enforced by the protocol.': '发送一对一聊天作为签名信封，协议强制执行人与人角色策略。',
    'Messages prefer direct libp2p paths and fall back to circuit relay when NAT blocks a straight connection.': '消息首选直接libp2p路径，当NAT阻止直连时回退到电路中继。',
}

def translate_line(line):
    if line in SECTION_TRANSLATIONS:
        return SECTION_TRANSLATIONS[line]
    
    if line in SENTENCE_TRANSLATIONS:
        return SENTENCE_TRANSLATIONS[line]
    
    for en, zh in TERMS.items():
        line = re.sub(r'\b' + re.escape(en) + r'\b', zh, line, flags=re.IGNORECASE)
    
    return line

def translate_file(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    lines = content.split('\n')
    translated_lines = []
    
    in_code_block = False
    in_svg = False
    
    for line in lines:
        if line.startswith('```'):
            in_code_block = not in_code_block
            translated_lines.append(line)
            continue
        
        if '<svg' in line:
            in_svg = True
            translated_lines.append(line)
            continue
        
        if '</svg>' in line:
            in_svg = False
            translated_lines.append(line)
            continue
        
        if in_code_block or in_svg:
            translated_lines.append(line)
            continue
        
        if line.startswith('<figure') or line.startswith('</figure') or line.startswith('<figcaption') or line.startswith('</figcaption'):
            translated_lines.append(line)
            continue
        
        if line.startswith('- ') or line.startswith('• ') or line.startswith('* ') or line.startswith('**'):
            translated_lines.append(translate_line(line))
            continue
        
        if line.strip() == '':
            translated_lines.append(line)
            continue
        
        translated_lines.append(translate_line(line))
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(translated_lines))

if __name__ == '__main__':
    input_file = '/Users/shileipeng/Documents/mygithub/EnvoyMesh/EnvoyMesh_GuideBook_0.1.0.md'
    output_file = '/Users/shileipeng/Documents/mygithub/EnvoyMesh/EnvoyMesh_GuideBook_0.1.0.zh-CN.md'
    translate_file(input_file, output_file)
    print(f"Translation complete! Output saved to {output_file}")