/**
 * `@envoymesh/api/core` — the **reusable** half of the package's surface.
 *
 * GENERATED by `node scripts/generate-core-surface.mjs` — **do not hand-edit**.
 * `--check` fails when this file and the manifest disagree.
 *
 * ## Why this entry point exists
 *
 * The classifier's third condition seeds a module `product-bound` when it imports
 * a non-core `@envoymesh/*` package — and until declared subpath entry points
 * became their own specifier, `@envoymesh/api/core` was indistinguishable from
 * `@envoymesh/api`, so the only lever was all-or-nothing: either the whole
 * package (including its product surface) was core, or every module importing
 * any part of it was tainted.
 *
 * This entry point is the alternative. It re-exports **only** the modules the
 * Axis-1 manifest calls `reusable` (109 of the barrel's 135 re-export
 * statements; 26 product-bound modules are deliberately absent — `NodeService`
 * itself among them). A reusable module can therefore import the contract it
 * needs from `@envoymesh/api/core`, while importing `@envoymesh/api` still
 * means "the whole product surface" and still taints.
 *
 * Design and rationale: `docs/envoymesh-refactoring-plan.md` §8.17.2.
 */

export * from "./envoy-ai-thread.js";
export { ENVOYMESH_VERSION } from "./version.js";
export type {
  OpenClawPluginInfo,
  OpenClawPluginDetail,
} from "./openclaw-plugin.js";
export * from "./model-thinking.js";
export * from "./author-content-draft.js";
export * from "./ai-knowledge-base.js";
export * from "./embedding-presets.js";
export * from "./ai-embedding-limits.js";
export * from "./rag-index-status.js";
export * from "./chat-model-probe.js";
export * from "./auto-reply-limits.js";
export * from "./agent-circle.js";
export * from "./envoy-pair-uri.js";
export * from "./pairing-token.js";
export * from "./envoy-contact-link.js";
export * from "./envoy-url.js";
export * from "./setup-sponsor-friend.js";
export * from "./wan-join-invite-limits.js";
export * from "./chat-device-auth.js";
export * from "./chat-actor.js";
export * from "./agent-network-mode.js";
export * from "./ext-agent.js";
export * from "./approval-queue.js";
export * from "./task-dispatcher.js";
export * from "./default-bootstrap.js";
export type { RelayJoinDecision, RelayJoinRateLimiter } from "./community-relay-join.js";
export * from "./relay-roster.js";
export * from "./core-node-service.js";
export type {
  Artifact,
  CompositeArtifact,
  CompositeArtifactPart,
  FileArtifact,
  ChainReport,
  ChainReportSection,
  StructuredArtifact,
  TextArtifact,
  TaskResultPayload,
} from "@envoymesh/protocol";
export * from "./document-autonomy.js";
export * from "./profile-media.js";
export * from "./strip-image-metadata.js";
export * from "./owner-agent-types.js";
export * from "./owner-agent-tool-allowlist.js";
export * from "./transfer-status.js";
export * from "./chain-input-delivery.js";
export * from "./chain-artifact-delivery.js";
export * from "./knowledge-syndication.js";
export * from "./kb-plugin.js";
export * from "./envoy-disclosure.js";
export * from "./emp-supported-capabilities.js";
export * from "./agent-network-membership.js";
export * from "./agent-network-score.js";
export * from "./chain-team-strategy.js";
export * from "./chain-speculation.js";
export * from "./agent-network-diagnostics.js";
export * from "./capability-intent-routing.js";
export * from "./capability-provider.js";
export * from "./capability-route-executor.js";
export * from "./social-proxy-session.js";
export * from "./document-acquisition.js";
export * from "./friend-autopilot.js";
export * from "./ipfs-pinning.js";
export * from "./wan-join-invite.js";
export * from "./company-invite.js";
export * from "./shop.js";
export * from "./kiosk-status.js";
export * from "./fleet-manifest.js";
export * from "./fleet-workers-ensure.js";
export * from "./fleet-bootstrap.js";
export * from "./h2a-wire-semantics.js";
export * from "./owner-did-presentation.js";
export type { ResolveDidImportResult, ResolvedDidImport } from "./did-import.js";
export * from "./wan-two-nat-checklist.js";
export * from "./discovery-hop.js";
export * from "./discovery-privacy.js";
export type { UnsignedDiscoveryReferralAttestation } from "./discovery-referral-attestation.js";
export * from "./sync-state.js";
export type { PairingPayload, PairWithHomeNodeParams } from "@envoymesh/protocol";
export type { ModelProviderConfig, ModelProviderMode } from "./model-provider-config.js";
export * from "./terminal.js";
export * from "./terminal-agent.js";
export * from "./pi-agent.js";
export * from "./eh-user-question.js";
export * from "./eh-turn-hints.js";
export * from "./eh-prompt-busy.js";
export * from "./eh-activity.js";
export * from "./eh-timeouts.js";
export * from "./eh-turn.js";
export * from "./eh-chat-history.js";
export * from "./eh-timeline.js";
export * from "./pi-timeline.js";
export * from "./ext-timeline.js";
export * from "./coding-ui-bucket.js";
export * from "./coding-harness.js";
export * from "./coding-harness-runtime.js";
export * from "./coding-review-ref.js";
export * from "./coding-heartbeat.js";
export * from "./coding-schedule.js";
export * from "./eh-turn-review.js";
export * from "./eh-ux-telemetry.js";
export * from "./eh-chat-task.js";
export * from "./eh-permission.js";
export * from "./eh-files-changed.js";
export * from "./ai-bot.js";
export * from "./pi-native-providers.js";
export * from "./envoy-local.js";
export * from "./terminal-wire.js";
export * from "./home-remote.js";
export { bondTrustRank } from "./bond-trust-rank.js";
export {
  chatRoomThreadKey,
  parseChatRoomThreadKey,
  isChatRoomThreadKey,
} from "./chat-room-thread.js";
export {
  deriveLocationDiscoveryTopics,
  locationSearchTopics,
  encodeGeohash,
  decodeGeohash,
  NEARBY_GEOHASH_PRECISION,
  normalizeLocationSlug,
  normalizeCountryCode,
  parseGeoDiscoveryTopic,
  formatGeoTopicLabel,
  geohashNeighborPrefixes,
  GEO_TOPIC_PREFIX,
  hashDiscoveryTag,
  hashGeoDiscoveryTopics,
  geoDiscoveryTagHashesFromProfile,
  matchGeoDiscoveryTagHashes,
  friendMatchingGeoSearchTopics,
  friendMatchingGeoTagHashes,
  resolveFriendMatchingGeoInput,
} from "./discovery-location.js";
export type { FriendMatchingGeoScope } from "./discovery-location.js";
export type { DiscoveryLocation, DiscoveryLocationPrecision } from "@envoymesh/protocol";
export {
  profileCapabilityTags,
  profileCapabilityDiscoveryTopics,
  syncProfileTagsToManifestCapabilities,
} from "./profile-capabilities.js";
export type { ProfileCapabilityEntry } from "./profile-capabilities.js";
export * from "./web-content-default-templates.js";
export * from "./a2a-bridge-types.js";
export * from "./a2a-agent-card.js";
