// AUTO-GENERATED by scripts/sync-version.mjs — do not edit manually.
// Source of truth: VERSION file at repo root.
// Declared in `@envoymesh/protocol` and re-exported here unchanged: the
// harness layer reads it, and importing it from this package classified
// harness modules `product-bound` (E9's third condition).
export { ENVOYMESH_VERSION } from "@envoymesh/protocol";
